### ISSUE TITLE
Browser back-/forward button: dialogue "leave page?"

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#102]
As a user I prefer to be asked whether I want to leave the page (in this case the ROA graph) or stay there when I accidentally use the browser back-/forward button. Otherwise all the changes I made in the ROA graph are completely lost and I am back in the webapp. 
This is true for the whole webapp but seems to be especially important for the ROA style.

Consider trigger: close, navigate, refresh

**Comment by bfrgottscma** [comment]
Tested in Firefox:
backward button: English dialogue
refresh+home button: German dialogue

**Comment by ruegenbfr** [comment]
Its not a bug its a (browser specific) feature.
