### ISSUE TITLE
Create legend in roa view

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#107]
The user wants to see  a legend in roa view.

**Comment by bfrgottscma** [comment]
The legand should be placed outside of the country, company, lot and measurement boxes, below the ROA graph.
Please use the entities from the ROA style palett as entities for the legend and display them similar to the mockup below (e.g. box on the left (empty), name of the box on the right). 

Mockup from EFSA ROA:
![grafik.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/988ed5a8-ab68-4e51-99aa-045afe8e9587)
