### ISSUE TITLE
Pipeline as code

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/fcl-client#119]
Re-implement the fcl-client deployment pipeline in a Jenkins declarative pipeline script and commit it to source control.

Use the mibi-client pipeline script as a template.

**Comment by dptolle** [comment]
@bfrgottscma @draaw If possible I would like to give this Ticket a critical priority.

**Comment by birgitlewicki** [comment]
fixed vulnerability issues:
upgraded openlayers@4.6.5 to ol@5.3.3

**Comment by birgitlewicki** [comment]
- Setup jenkins pipeline for fcl-client qa on fcllab-dev-001.bfr.berlin.

- Setup jenkins pipeline for fcl-server qa on fcllab-dev-001.bfr.berlin.

**Comment by birgitlewicki** [comment]
- Setup jenkins pipeline for fcl-client audit on fcllab-001.bfr.berlin.

- Setup jenkins pipeline for fcl-server audit on fcllab-001.bfr.berlin.
