### ISSUE TITLE
Save ROA style status + reload it into fcl client

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#122]
As a user I want to save the state of the ROA style, especially when I made changes within the ROA style (e.g. adding additional information, changes in names, changing the size and position of boxes and arrows, ...).

I also want to load the saved data back into the fcl client.

**Comment by afalenski** [comment]
Works very well. See attached file. I used the sample data, made a font bold, coloured a station box in green and changed an arrow to a double line. All could be saved and also reloaded. 

The attached TXT is an XML. Rename filetype and load file into ROA-Style Web App. XML is not allowed in ZenHub.
[https://app.zenhub.com/files/61294409/eb0ba92b-c1a1-4a24-b0e5-3aad248aeb4c/download](https://app.zenhub.com/files/61294409/eb0ba92b-c1a1-4a24-b0e5-3aad248aeb4c/download)
