### ISSUE TITLE
Optimize positions and sizes of boxes

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#126]
When creating the ROA I want to have the position and size of the boxes positioned and sized in a space-saving way (reduce empty space within boxes) so I do not have to re-arrange the boxes manually.

For examples ee email Alex+Marion 17.04.19

**Comment by afalenski** [comment]
Positions and sizes are optimised. However, using the small network from the Norovirus_Scenario.json you get a VERY wide layout. This is not optimal. 
This ticket is done. I will create another one for the new feature request.
