### ISSUE TITLE
Switching between ROA and GIS view: Menu and buttons in toolbar not functional anymore

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#138]
Switching from GIS view to ROA style and back to GIS view (via the tracing view button): Menu and buttons in toolbar not functional anymore.

**Comment by afalenski** [comment]
How to reproduce the bug:
- Go to the FCL Web main page and login
- Click on button 'Tracing View'
- Click on button 'Load Example Data'
- Click on hamburger menu, then on GIS
- Click on button 'ROA Style'
- Click on button 'Tracing View'
Now the hamburger menu button does not work anymore.
