### ISSUE TITLE
Make farm-to-fork layout the standard layout

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#147]
As an FCL Web App user I would like to see my data or sample data in the tracing view directly in the farm-to-fork layout. This is the visualisation users can understand fastest and easiest and thus should be the standard layout.
This new standard layout should only be used if the dataset does not include any information about the position of stations in the graph view. 
If this visualisation is computationally too intensive (limit 100 stations), set a maximum station/delivery number above which a message appears and the Fruchterman-Reingold is used. 
Message text: "The number of stations and deliveries is high and thus the Fruchterman-Reingold layout will be displayed. If you would like to see data in the farm-to-fork layout, select it from 'Apply Layout' in the context menu and wait until the visualisation is complete."

**Comment by ruegenbfr** [comment]
In aggreement with @bfrgottscma the user will be not notified about the fallback to Fruchterman-Reingold layout because a newbie might be confused by this information and other users are probably aware of it respectively know what to do.

**Comment by ruegenbfr** [comment]
Remark:
If the farm-to-fork-layout is used automatically after uploading a json, it behaves different to the farm-to-fork layout triggered manually by the user. The automatic farm-to-fork layouting uses a maximum time limit of 10 seconds for the vertex sorting step during the layout phase, to limit the layout running time. The manually triggered layouting does not use a maximum time limit.
