### ISSUE TITLE
"Save image" button not functional anymore

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#148]

**Comment by birgitlewicki** [comment]
Fixed by switching back to previous version of html2canvas@1.0.0-rc.1

**Comment by bfrgottscma** [comment]
Tested in Firefox and Chrome
"Save image" allows to save a png but throws an error message

ERROR 
TypeError: Actions must have a type property Stack trace: [object Object]

Afterwards "Save image" and "download data" buttons are not functional anymore and  "upload data" button is only partly functional (dialogue is opened + you can select a file to load but it does not load)
