### ISSUE TITLE
Highlighting: Switch on/off specific highlighting condition

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#162]
As a user I want to be able to easily (one click?) switch on/off specific highlighting conditions. 
E.g. hide names of stations while containing the content of this highlighting condition to be able to switch on later. I do not want to repeat the highlighting because in case of manually selected stations/deliveries this is very laborious and error prone.

Use slider instead of button "activate" / "inactivate". Mouse-over text "activate" or "inactivate"

Mockup from AF to discuss:
Slider: If highlighting is set inactive: Font "Backward trace" and "7" become grey, L-Button (legend) becomes white (as if inactivated). As soon as the slider is set active, the L-Button becomes blue again (active on legend).
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/b4afa0ae-1359-4957-8e38-5d9f0c499359)

**Comment by afalenski** [comment]
[x] The user can switch on and off a highlighting condition with one click. Clicking on the blue A-button disables the highlighting condition. The station shape (e.g. pentagon symbol) changes to a circle. The A-button becomes white.
- There is no slider. It is a button with an "A". This is not what is in described in ticket and mockup.
- The "A" is not centered.
To be discussed what needs to be changed.

**Comment by bfrgottscma** [comment]
Works but some of the details specified in the mockup were not implemented. Discuss during sprint review.

**Comment by ruegenbfr** [comment]
In agreement with PO "A" button was replaced by slider.
Done.

**Comment by afalenski** [comment]
Great. Looks fantastic, works fast (for small datasets) and is intuitively understood. 
There is a mouseover text with a helpful description.
When deactivating a highlighting rule, the highlighting name, the number and the "L" in the legend button become grey. The legend button becomes white. 
When deactivating the visualisation in the legend, then deactivating and reactivating the highlighting rule, the legend visualisation is still deactivated as expected.

Performance:
Very fast with small datasets. Using the Baby tea large dataset it takes about 1s to deactivate/activate a highlighting rule in Chrome and about 1.5s in Firefox

Done.

Tested with datasets
- Baby Tea scenario Step 1 (9 stations, 16 deliveries)
- Baby Tea scenario Step 3 (810 stations, 4070 deliveries)

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
- Firefox 88.0.1 (64-Bit)
