### ISSUE TITLE
Properties of stations

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#166]
Improve property dialogue to make it more user friendly: see mockup

![Mockup station properties.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/775d9f46-3da7-4ff0-8caa-79cb6d246627)

Do not show (or put it on the bottom of the dialogue)
Observed	none
Forward Trace	false
Backward Trace false
Outbreak	false
Cross Contamination false
Common Link	false

"city", "country", "housenumber", "street", "zip"  --> remove "", First letter as capital letter

Solution:
- remove ''
- remove dialog positioning buttons
- add vip entries according to mockup
- enlist other entries in a collapse section
- use empty dialog title
- change 'Properties:' to 'Station XY:'
- add 'Incoming deliveries' and 'Outgoing deliveries' header

**Comment by ruegenbfr** [comment]
Remark: 
The Label 'Properties:' was not changed to 'Station XY:' but to 'XY' (as given in the mockup).
