### ISSUE TITLE
Check performance of webapp in browsers

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#171]
In contrast to Chrome, the performance of the webapp is really bad in Firefox (e.g. with a network having only 310 stations). E.g. panning the network or moving stations is only possible with a big time delay.

Check FireFox and Chrome.

Use data in:
Check webapp folder on network drive for test dataset.

Apply solution! See below.

**Comment by bfrgottscma** [comment]
Tested in Firefox and Chrome (panning the network, moving one or more stations, select one or more stations, merge/unmerge deliveries, merge/unmerge stations) --> everything fine
