### ISSUE TITLE
Loading example data not always possible

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#189]
When I load a specific data file (see network drive: "NorovirusScenario_Score merged_gerundet_Export aus Webapp"), trying to load the example data afterwards is not possible

(Edit: in contrast to other data files, the "NorovirusScenario_Score merged_gerundet_Export aus Webapp" is a JSON that was already exported from the  web app; a weight is set)

The following errors are thrown in Chrome and Firefox

Error in Chrome: 

core.js:15724 ERROR TypeError: Cannot set property 'contained' of undefined
    at data.service.ts:101
    at Array.forEach (<anonymous>)
    at DataService.push../src/app/tracing/services/data.service.ts.DataService.applyGroupSettings (data.service.ts:100)
    at DataService.push../src/app/tracing/services/data.service.ts.DataService.updateCache (data.service.ts:207)
    at DataService.push../src/app/tracing/services/data.service.ts.DataService.applyState (data.service.ts:235)
    at DataService.push../src/app/tracing/services/data.service.ts.DataService.getData (data.service.ts:22)
    at GraphService.push../src/app/tracing/graph/graph.service.ts.GraphService.applyState (graph.service.ts:296)
    at GraphService.push../src/app/tracing/graph/graph.service.ts.GraphService.getData (graph.service.ts:38)
    at SchemaGraphComponent.push../src/app/tracing/graph/components/schema-graph.component.ts.SchemaGraphComponent.applyState (schema-graph.component.ts:474)
    at SafeSubscriber._next (schema-graph.component.ts:129)

Error in Firefox
ERROR 
TypeError: member is undefined Stack trace: ./src/app/tracing/services/data.service.ts/DataService.prototype.applyGroupSettings/<@https://fcllab-dev-001.bfr.berlin/main.js:11616:21 ./src/app/tracing/services/data.service.ts/DataService.prototype.applyGroupSettings@https://fcllab-dev-001.bfr.berlin/main.js:11615:17 ./src/app/tracing/services/data.service.ts/DataService.prototype.updateCache@https://fcllab-dev-001.bfr.berlin/main.js:11695:13 ./src/app/tracing/services/data.service.ts/DataService.prototype.applyState@https://fcllab-dev-001.bfr.berlin/main.js:11720:13 ./src/app/tracing/services/data.service.ts/DataService.prototype.getData@https://fcllab-dev-001.bfr.berlin/main.js:11583:9 ./src/app/tracing/graph/graph.service.ts/GraphService.prototype.applyState@https://fcllab-dev-001.bfr.berlin/main.js:6177:20 ./src/app/tracing/graph/graph.service.ts/GraphService.prototype.getData@https://fcllab-dev-001.bfr.berlin/main.js:5951:9 ./src/app/tracing/graph/components/schema-graph.component.ts/SchemaGraphComponent.prototype.applyState@https://fcllab-dev-001.bfr.berlin/main.js:5761:23 ./src/app/tracing/graph/components/schema-graph.component.ts/SchemaGraphComponent.prototype.ngOnInit/this.graphTypeSubscription</_this.graphStateSubscription<@https://fcllab-dev-001.bfr.berlin/main.js:5493:308 ./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub@https://fcllab-dev-001.bfr.berlin/vendor.js:337692:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337630:17 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:337576:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/filter.js/FilterSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:342034:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/distinctUntilChanged.js/DistinctUntilChangedSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:341535:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/map.js/MapSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:342595:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/map.js/MapSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:342595:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/Subject.js/Subject.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337319:17 ./node_modules/rxjs/_esm5/internal/ReplaySubject.js/ReplaySubject.prototype.nextInfiniteTimeWindow@https://fcllab-dev-001.bfr.berlin/vendor.js:337138:9 StoreDevtools/liftedStateSubscription<@https://fcllab-dev-001.bfr.berlin/vendor.js:144109:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub@https://fcllab-dev-001.bfr.berlin/vendor.js:337692:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337630:17 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:337576:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/scan.js/ScanSubscriber.prototype._tryNext@https://fcllab-dev-001.bfr.berlin/vendor.js:344202:9 ./node_modules/rxjs/_esm5/internal/operators/scan.js/ScanSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:344189:20 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js/WithLatestFromSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:346533:17 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/Notification.js/Notification.prototype.observe@https://fcllab-dev-001.bfr.berlin/vendor.js:336818:41 ./node_modules/rxjs/_esm5/internal/operators/observeOn.js/ObserveOnSubscriber.dispatch@https://fcllab-dev-001.bfr.berlin/vendor.js:343180:9 ./node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js/AsyncAction.prototype._execute@https://fcllab-dev-001.bfr.berlin/vendor.js:347141:13 ./node_modules/rxjs/_esm5/internal/scheduler/QueueAction.js/QueueAction.prototype.execute@https://fcllab-dev-001.bfr.berlin/vendor.js:347289:13 ./node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js/AsyncScheduler.prototype.flush@https://fcllab-dev-001.bfr.berlin/vendor.js:347231:25 ./node_modules/rxjs/_esm5/internal/scheduler/QueueAction.js/QueueAction.prototype.schedule@https://fcllab-dev-001.bfr.berlin/vendor.js:347283:9 ./node_modules/rxjs/_esm5/internal/Scheduler.js/Scheduler.prototype.schedule@https://fcllab-dev-001.bfr.berlin/vendor.js:337243:16 ./node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js/AsyncScheduler.prototype.schedule@https://fcllab-dev-001.bfr.berlin/vendor.js:347219:20 ./node_modules/rxjs/_esm5/internal/operators/observeOn.js/ObserveOnSubscriber.prototype.scheduleMessage@https://fcllab-dev-001.bfr.berlin/vendor.js:343185:25 ./node_modules/rxjs/_esm5/internal/operators/observeOn.js/ObserveOnSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:343188:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype.notifyNext@https://fcllab-dev-001.bfr.berlin/vendor.js:342879:9 ./node_modules/rxjs/_esm5/internal/InnerSubscriber.js/InnerSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:336766:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/map.js/MapSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:342595:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/mergeMap.js/MergeMapSubscriber.prototype.notifyNext@https://fcllab-dev-001.bfr.berlin/vendor.js:342879:9 ./node_modules/rxjs/_esm5/internal/InnerSubscriber.js/InnerSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:336766:9 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/operators/skip.js/SkipSubscriber.prototype._next@https://fcllab-dev-001.bfr.berlin/vendor.js:344558:13 ./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337553:13 ./node_modules/rxjs/_esm5/internal/Subject.js/Subject.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:337319:17 ./node_modules/rxjs/_esm5/internal/BehaviorSubject.js/BehaviorSubject.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:336730:9 ./node_modules/@ngrx/store/fesm5/store.js/ActionsSubject.prototype.next@https://fcllab-dev-001.bfr.berlin/vendor.js:144443:9 ./node_modules/@ngrx/store/fesm5/store.js/Store.prototype.dispatch@https://fcllab-dev-001.bfr.berlin/vendor.js:144879:9 ./src/app/main-page/container/toolbar-action-container/toolbar-action-container.component.ts/ToolbarActionContainerComponent.prototype.loadExampleData/<@https://fcllab-dev-001.bfr.berlin/main.js:1320:13 ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@https://fcllab-dev-001.bfr.berlin/polyfills.js:3288:17 onInvoke@https://fcllab-dev-001.bfr.berlin/vendor.js:78760:24 ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@https://fcllab-dev-001.bfr.berlin/polyfills.js:3287:37 ./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@https://fcllab-dev-001.bfr.berlin/polyfills.js:3047:24 scheduleResolveOrReject/<@https://fcllab-dev-001.bfr.berlin/polyfills.js:3786:29 ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@https://fcllab-dev-001.bfr.berlin/polyfills.js:3320:17 onInvokeTask@https://fcllab-dev-001.bfr.berlin/vendor.js:78751:24 ./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@https://fcllab-dev-001.bfr.berlin/polyfills.js:3319:41 ./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@https://fcllab-dev-001.bfr.berlin/polyfills.js:3092:28 drainMicroTaskQueue@https://fcllab-dev-001.bfr.berlin/polyfills.js:3498:25 ./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@https://fcllab-dev-001.bfr.berlin/polyfills.js:3399:21 invokeTask@https://fcllab-dev-001.bfr.berlin/polyfills.js:4641:9 globalZoneAwareCallback@https://fcllab-dev-001.bfr.berlin/polyfills.js:4678:21 
core.js:15724

**Comment by ruegenbfr** [comment]
Dublicate of #215
