### ISSUE TITLE
Font size/node size: select point size

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#198]
As a user I want to be able to set font size and node size to a specific point size (eg. 10, 12, 14, ...points) via dropdown menu.
Also take into account the behavior of font and node size when zooming in or out --> size should be stable even if zoomed

As in desktop app.

**Comment by ruegenbfr** [comment]
Additionally to the options in the desktop app I added 50 for node size.

**Comment by bfrgottscma** [comment]
@ruegenbfr  How do you decide on the initial node and font size when loading a graph for the first time?
