### ISSUE TITLE
Not used webapp uses cpu and increases memory usage

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#220]
A loaded webapp which is not actively used uses 8% CPU and increases memory usage over time.

Webapp is sometimes also slow when in use. If you check memory usage, Firefox sometimes needs 2GB memory.

Please check the current status of the problem. Memory consumption has higher priority.

**Comment by ruegenbfr** [comment]
CPU consumption is caused (mainly) by cytoscape. 
The increased memory usage is due to cytoscape related memory leakage. The reason is not cytoscape itself but its incomplete integration (the cleanup method 'destroy' was not explicitly called).  

Solution: Cytoscape objects are cleaned up explicitly.

**Comment by afalenski** [comment]
Tested with dataset 'Scenario_3_All-Stations.json': 
- Loading dataset: 234 MB RAM
- Changing from graph to GIS and back does not enlarge RAM usage: 279 MB (back to graph: 234 MB)
- Merge Deliveries productwise: 244 MB
- Merge Deliveries labelwise: 377 MB
- Merge Deliveries lotwise: 390 MB
changing to and fro several times:
- Memory usage up to 630 MB

Result: Before, the RAM usage was up to 1 GB and now it is 630 MB at maximum
