### ISSUE TITLE
Script to monitor availability of FCL web app (test and prod)

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#233]
As product owner I would like to be informed as soon as possible if FCL web (test and prod) as is not available. Please monitor automatically e.g. via script once or twice per day.

**Comment by birgitlewicki** [comment]
Implemented Jenkins job check_url with shell script in the build step

**Comment by bfrgottscma** [comment]
Please run job at 6 am and at 12 noon

**Comment by birgitlewicki** [comment]
As discussed the job is running now at

6am
12noon
4pm
