### ISSUE TITLE
Legend in saved image has artefacts

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#246]
Legend in the saved image has artefacts. It should look like in the graph/map view

![X_legend_graph.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/4e87ef25-8b0f-4bd2-a72e-de1d7fdc5306)

**Comment by ruegenbfr** [comment]
This artefact does not show on safari (13.0.2), but on Chrome (79.0.) and Firefox (60.7.).
