### ISSUE TITLE
Harmonize type of business 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#247]
The station activity information for the roa report is retrieved from the "typeOfBusiness" property of a station.

**But**, the desktop app deliveres this information in the "type of business" property of a station (because the supply chain reader names the column this way). Only the destiller to json workflow delivers this information in the "typeOfBusiness" property of a station.

Proposed short term solution:
use work around: Accept both writings in the webapp. Prioritize typeOfBusiness

Proposed long term solution:
JSON Export in desktop app should replace "type of business" by "typeOfBusiness"
JSON Import in desktop app should replace "typeOfBusiness" by "type of business"

**Comment by bfrgottscma** [comment]
Short term solution is done. New ticket for long term solution needs to be written
