### ISSUE TITLE
GIS view: Avoid overlay of stations on frame

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#248]
If GIS information of several stations is missing, they are shown on a frame but they are all on the same spot and you can not see how many stations it is or read the labels of the stations anymore.

As a user I would expect that the overlay of those stations on the frame is prevented automatically as it is done in the desktop app. The functionality "avoid overlay" was not implemented. The JSON file contains ("avoidOverlay":true) but this is not displayed in the Web App. Please fix.

Mockup=FCL desktop

![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/0b0ea42b-2daa-49b6-84d4-d425950778a7)
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/d6b67c6a-9a87-4f9f-a48e-e43f46707abc)

**Comment by ruegenbfr** [comment]
Done.

The avoid overlay feature in the web app was implemented similar to the avoid overlay feature within the desktop app with all its consequences:
- the positions of the nodes which are to 'close' to each other are temporary changed to avoid an overlay
- this reposition behaviour is dependent on the node size and the zoom level
- it effects nodes with and nodes without gis information

**Comment by afalenski** [comment]
The solution does not always work:
- It works with test file GIS-Test_AvoidOverlay_fcl-c280-248.json
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/d180a200-4fb3-47b7-bd2b-354dae3a49b1)
- It does not work with test file GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/9f927a95-6813-4ce7-8bf9-fbab267ef49e)
In both screenshots, zoom was set to maximum. Please note that in the second example the stations "La source des herbes" and "Natürlicher Leben" are on top of each other. Please also note that the red border is not as wide as in the first example (screenshots were not scaled or changed).
[Test files](https://app.zenhub.com/files/61294409/ccae3c07-934a-4b47-a323-dc8a69a70099/download)

**Comment by ruegenbfr** [comment]
Both examples work for me. Did you forget to recheck the "Avoid Overlay in GIS Graph"-checkbox? Because on uploading a model the avoidOverlay setting from the model file is applied.

**Comment by bfrgottscma** [comment]
Works fine for me.

**Comment by bfrgottscma** [comment]
To be changed: 
Only apply for station without GIS data (not for stations with GIS data (separate ticket for those, mockup needed))
Avoid overlay as default (if not specified in uploaded dataset)
Make behavior zoom dependent.

**Comment by ruegenbfr** [comment]
- "Avoid Overlay" is only applied for nodes without gis
- the "Avoid Overlay" option was removed from "Graph Settings" tab
- the "Avoid Overlay" setting from the imported json is not used
- this feature is always applied

Just to be clear:
- the "Avoid Overlay" node cloud changes its size relative to the zoom but the positions of the nodes without gis is zoom independent

**Comment by afalenski** [comment]
The frame disappears when zooming in:
- GIS-Test_AvoidOverlay_fcl-c280-248.json: station "La source des herbes"
- GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json: station "Natürlicher Leben" (in Chrome and Firefox)
Obviously only for stations which are on the left of the border.

The following was seen with dataset GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json:
Deliveries disappear in highest zoom level:
- delivery to station "Top Vera Foods" (only in Chrome)
- both deliveries connected to station "Tea traders cooperative" (in Chrome and new Firefox, not in ESR version)

Only 2 out of 3 deliveries are shown in higher zoom levels
- between station "August Arzneiöle" and "La Source des Herbes". When setting "merge all deliveries", the delivery line disappears completely in the highest zoom level. (Only in Chrome)

Please fix.

Tested with datasets
GIS-Test_AvoidOverlay_fcl-c280-248.json
GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
- Firefox 88.0.1 (64-Bit)

**Comment by afalenski** [comment]
The frame stays in Chrome visible when zooming in, so this was fixed.

The following was seen with dataset GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json:
Deliveries disappear in highest zoom level:
- delivery to station "Top Vera Foods"
- both deliveries connected to station "Tea traders cooperative"
- Only 5 out of 12 deliveries are shown at "La Source des Herbes"
- between station "August Arzneiöle" and "La Source des Herbes". When setting "merge all deliveries", the delivery line disappears completely in the highest zoom level.
- NEW: In highest zoom level, the remaining deliveries are shown with a very very thin light grey line, barely visible.
**Please fix.**

Tested with datasets
- GIS-Test_AvoidOverlay_fcl-c280-248.json
- GIS-Test_AvoidOverlay_fcl-c248_Scenario_1_Outbreak-Baby-Tea2.json

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)

**Comment by ruegenbfr** [comment]
The disappearing deliveries and other delivery rendering issues are caused by hardware acceleration in chrome. 

To fix this the user has to:
- enter **chrome://flags** in address bar in Chrome
- set **Accelerated 2D canvas** to **Disabled**

Unfortunately, this behavior cannot be switched off from code.
This needs to be added in FAQ.

Please note that this issue is rather related to ticket , since it the higher zoom allows the detection of these issues.

**Comment by afalenski** [comment]
Yes, this fixes the problem in Chrome.
In Firefox this was not a problem.
Done.
