### ISSUE TITLE
Wider space between arrows for several deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#255]
At the moment, the space between the arrows is relatively narrow.

As a user I prefer to have a wider space between the arrows for several deliveries to be able to read the labels for the deliveries. Ideally space is a little bit wider as the font size if delivery labels are shown. If they are not shown, the space can be as narrow as now.

**Comment by ruegenbfr** [comment]
Solution:
The inter edge space is adapted to fontsize, label existence and edge thickness

If between a pair of node at least one edge with a label exist, the distance between all edges between this pair of nodes respects the fontsize. Otherwise the edge distance is much smaller.
