### ISSUE TITLE
Properties of deliveries (one selected)

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#260]
As a user I would like to have most relevant information on top of the property list and less relevant information on the bottom (--> this only affects the dialogue in case one delivery is selected, selection of several dialogues has different dialogue)

+ see mockup to improve dialogue

![Mockup delivery properities.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/72ca39a0-547f-4705-97e4-e914d5d2e79e)

Solution:
- remove ''
- remove dialog positioning buttons
- add vip entries according to mockup
- enlist other entries in a collapse section
- use empty dialog title
- change 'Properties:' to 'Delivery XY:'

**Comment by ruegenbfr** [comment]
Remark:
The Label 'Properties:' was not changed to 'Delivery `<Product name>`:' but to '`<Product name>`' (as given in the mockup).

Attention:
The list header '`<Product name>`' is a bit misleading since these are the properties of a delivery not a product.
