### ISSUE TITLE
Use proper Gis information extraction columns 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#261]
The user wants to export data with gis information from the desktop app and use the gis view in the web app.
But the gis view is not available.

Problem:
Currently the GIS information is extracted from the wrong columns 'GeocodingLatitude' and 'GeocodingLongitude'.
But the Desktop-App is putting the GIS info in the columns 'Latitude' and 'Longitude'.

Solution:
Use correct extraction columns.

**Comment by bfrgottscma** [comment]
GIS columns not shown in the station properties

**Comment by afalenski** [comment]
Example data (column name "Latitude") as well as BabyTea Scenario data (column name "GeocodingLatitude") are shown on a map using "Mapnik". Done.
