### ISSUE TITLE
Create basic component for the right side bar

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#273]
As a user I would like to have the right side bar opened when clicking on the hamburger menu (upper right).
The side bar should show the basic structure of 3 tabs (filter, highlighting, settings) according to the mockup.
When openening the side bar it overlaps partially the graph.

minimum: 1/4 of viewport
maximum: 1/2 of viewport

Default: filter tab is active when opening hamburger menu for the first time.

The current UI status should be saved for the app session

**Think of Tests**
- [ ] Excel testsheet needed
- [x] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

![Mockup_Highlighting_Settings_20200216small.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/38a3fcfd-23fd-46a5-aabf-143f30d3de03)

**Comment by bfrgottscma** [comment]
There is some empty space above the right sidebar. If possible, please remove it

**Comment by birgitlewicki** [comment]
The font size of the header tab is fixed in #281

The empty space above the right sidebar is a firefox specific feature. In chrome this space is absent. Currently this is not fixed.
