### ISSUE TITLE
fix problems in active gis view wo stations with gis info

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#280]
Situation: Gis view is active, Stations with and stations without gis infos are visible. 

User-Action: The user makes all stations with gis info invisible. 

--> Only the boundary with stations wo gis infos remain

User-Action: The user clicks on autofit.

--> boundary and stations wo gis infos are not visible anymore, the map zooms into nirvana

Concept needed!

**Comment by afalenski** [comment]
When making stations without GIS-Info invisible and using autofit, the map zooms so that all stations can be seen, as expected. Done.
