### ISSUE TITLE
Complex filter functionality in Station table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#284]
As a user I would like to use complex filters according to the mockup (+ also see desktop app). Values can be selected via drop-down menu. 

In addition, the count of data lines available after the filter application should be displayed in the table footer/status bar 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [x] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by birgitlewicki** [comment]
The complex filter functionality is implemented according to the mockup except the request:

"It is also possible to use the following complex filter:
Property = 'ID', operation = 'in' and then select several IDs which will all be shown as concatenate in the value field"

which needs some concept discussion.

**Comment by bfrgottscma** [comment]
Unfortunately I discovered a bug: When having complex filters active and adding a column to the data table, the chosen complex filters are "deleted" but still remain active. Hence it is not possible to "unfilter" the data.
