### ISSUE TITLE
Sort function in Station table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#285]
As a user I would like to be able to sort the entries in the table (ascending, descending) for each column separately.

It should be visible in the column header via a small icon, that this specific column is currently sorted ascending or descending.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by birgitlewicki** [comment]
The described sorting behavior is already the default behavior of the table. As at this point we don't need yet a custom sorting behavior nothing is to be implemented for this functionality.

The more-columns button behavior is changed: it is fixed now on the left side of the table.
