### ISSUE TITLE
fix styling of hovered and selected edges

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#291]
In the station property dialog the incoming and outgoing deliveries are listed.

If the user hovers with the mouse over a node/edge in the station dialog, the represented edge/edges in the graph view is/are highlighted by an overlay.

But if the edge is selected in the graph view the overlay is not visible.

Please temporarily discard selection overlay when in properties mode, only show hovering of incoming/outgoing deliveries. When properties mode is closed, the previous selection should be restored.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/291?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
Issue is solved differently (initial ticket was based on the assumption that showing both the selection ad the overlay is not possible). Now, the selection is still visible when hovering overs with the mouse over an edge in the station dialog AND the represented edge/edges in the graph view is/are highlighted by an overlay.

Great solution!

Tested in Windows 10
- Firefox 97.0.1 (64-Bit)
- Chrome Version 98.0.4758.102 (Offizieller Build) (64-Bit)
