### ISSUE TITLE
show correct Lot Number in roa report and delivery properties

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#299]
The user wants to se the lot number and not the lot id.  

Info: 
The lot number is encoded in the column 'Lot Number'.
The lot id is encoded in the column 'Lot ID'.

**Comment by ruegenbfr** [comment]
The 'Lot Number' is supposed to contain the identifier of a lot which was collected in the field. 
The 'Lot ID' is supposed to contain a unique (within the model) (DB) identifier of the lot which historically was provided by the desktop app.

However, the distiller workflow puts the value which was supposed to be contained in the property 'Lot Number' in the property 'Lot ID'.

Since the report is supposed to be used for distiller outputs the web app default for the lot identifier is 'Lot ID'.

**Comment by ruegenbfr** [comment]
#### Solution:
Import columns are mapped as follows:
- If 'Lot ID' and 'Lot Number' are given: (json is probably from desktop app)
lot: 'Lot Number'
lotId: 'Lot ID'
- else, if 'Lot ID' and 'Refid' are given (distiller import)
lot: 'Lot ID'
refId: 'Refid'
- else, if 'Lot Number' is given:
lot: 'Lot Number'
- else if 'Lot ID' is given:
lot: 'Lot ID'

Please note: 'lot' is the internal property for the lot number, which was collected by investigator. 'lotId' is the internal property for a unique lot identifier (db identifier for a lot fcl desktop).

**Comment by afalenski** [comment]
- Dataset was uploaded
- colum ref ID or Lot ID was selected for visualisation in the delivery filter tab
- ROAstyle button was clicked as well as "Generate Report"
In every case the correct lot number was shown. Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset
- Scenario_1_Outbreak-Baby-Tea.json
- Distiller2FCL_Uploaded_FToF_AndDownloaded.json

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
