### ISSUE TITLE
integrate Date Delivery and Date Delivery Arrival to deliveries 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#300]
Currently only the internal delivery property 'date' is used for tracing analysis. But this field is not set. The desktop app delivers 'Date Delivery' and 'Date Delivery Arrival'. 
Please integrate this information for tracing analysis.

**Comment by bfrgottscma** [comment]
descisions taken after TC with ruegenbfr:

- integrate date delivery and date delivery arrival
- integrate this information for estimation of crosscontamination events
- add into graph settings tab: possibility to select three options for crosscontamination: ignore delivery dates, consider delivery dates, consider estimated delivery dates
- write docu on how delivery dates are estimated and why

**Comment by ruegenbfr** [comment]
Here is a test json file: [Test-Json](https://app.zenhub.com/files/61294409/cff11b33-1c6e-45da-8b3e-7f364e0897b8/download)

**Comment by afalenski** [comment]
@bfrgottscma I like the functionality in principle. However, I think the current implementation needs way to much explanation (see also the full page documentation by Marco). Perhaps different wording or mouseover texts would help. Please test yourself.

**Comment by bfrgottscma** [comment]
I like the functionality as well. For me the ticket is done.

The documentation will be revised by PO and Dev to make it as userfriendly as possible. Nevertheless we need the detailled description of the process to make the algorithm transparent for the user. 
 
Wording is fine for me. Especially "ignore dates" and "use explicit dates" should be clear. For "use deduced dates" I would expect the user to read the documentation if he/she does not understand. 
Mouseovers (with link to documentation!) surely help and will be handled in a separate ticket.
