### ISSUE TITLE
Add visibility column for station table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#302]
As a user I would like to be able to see in the data table if a station is visible/invisible in the graph.

Visible stations should be displayed with an open eye. Invisible stations should be displayed with a closed eye and whole data line should be displayed in grey. 
Icons must be created first.

I would like to be able sort this column.

I would like to be able to filter this column: Eye:grey=no filter, black eye=display only visible stations; black closed eye=show only invisible stations; no dropdown the user needs to repeat clicking until the desired filter option is active

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by birgitlewicki** [comment]
The state of an invisible station is realized with a strikethrough eye icon and not with a closed eye icon. This is in contrast to the request of the mockup. All other features of this ticket are realized as given in the mockup.

**Comment by bfrgottscma** [comment]
Only the left half of the sorting icon is clickable, for all other columns the whole sorting icon is clickable (I know, I am very picky here but this confused me at first)

**Comment by birgitlewicki** [comment]
The sorting icon of the visibility column is now clickable due to a smaller eye icon
