### ISSUE TITLE
Include data protection declaration

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#306]
As a user I want to be informed about data protection. Please add a data protection declaration (mockup see Mibi portal)

Please first develop the infrastructure and fill with content later
P/O creates the respective documents. 

Add English version on FCL Web website.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by birgitlewicki** [comment]
The content of the declaration and notice probably need some updates, eg the date in the footer.

**Comment by birgitlewicki** [comment]
Current date of declaration and notice fixed.
