### ISSUE TITLE
Ask user for consent to GDPR

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#308]
As a user manager I want every user to accept the information concerning the General Data Protection regulation (GDPR).

During the registration process: The user has to tick a checkbox next to the text "I have read and accept the Privacy Policy".  Per default, checkbox needs to be empty so that the user actively needs to consent to this. Without ticking the box, registration is not possible.

The word "Privacy Policy" should be a link. By clicking it, a pop-up window with the document is opened. Information (name, email address etc) that the user entered during the registration process should still be there when returning to the registration form.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
To clarify:
- Which document (please provide link)?
- How to detect change in GPDR?

**Comment by bfrgottscma** [comment]
When clicking on the link " data protection notice of FCL Web" in the Privacy Policy dialogue, the data protection notice of FCL Web is opened in the background and "deletes" the data filled into the registration form. Instead, the data protection notice of FCL Web should open in a new tab.

**Comment by birgitlewicki** [comment]
This is fixed in the frame of ticket #317

All links to the Privacy Policy now opens in a new tab where the "data protection notice" can be clicked and viewed as usual.

**Comment by afalenski** [comment]
User entries stay in the form when clicking on the Privacy Policy link during registration. Done.
