### ISSUE TITLE
Add "Created with FCL" image

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#309]
As a product owner I would like to have the "Created with FCL by BfR" image in the ROA style graph and the exported PDF thereof. It should be positioned below the legend as in the graph or the GIS view

**Comment by ruegenbfr** [comment]
FCL creates only the initial graph. An "Created with FCL" image could be inserted. If unchanged this image would be in the exported pdf.
But what about protection against user manipulations? (The user could remove this object by accident)

**Comment by bfrgottscma** [comment]
It would be good to have it protected against user manipulation but I doubt it is possible. Is it possible to check for the presence of the image when creating the PDF and if it is not there it should be added below the legend automatically?
