### ISSUE TITLE
Change of GDPR: Ask for consent

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#317]
As product owner, I need to get consent of the users if there is a change to the Datenschutzhinweise: After logging in into the account and before showing the profile page the user gets a popup and has to tick a box next to the text: "Die Datenschutzhinweise wurden geändert. Ich habe die geänderten Datenschutzhinweise gelesen und akzeptiere sie." Without consent the user can only log out.

To track if the user consented to latest GDPR, date of consent and date of publication of lastest GDPR could be compared.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
When I logged in into the test account I had to confirm the changed GDPR. Done.
