### ISSUE TITLE
Table Footer: Always visible/fixed

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#321]
As a user I would like to see the table footer with the column count at all times, even when the data table is longer or if table settings are expanded or when sidewards scroll bar is present.

Table footer should be positioned above sidewards scroll bar.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
Table footer is always visible also in large tables with >60 rows and >7 columns and when sidescrolling. Done.
