### ISSUE TITLE
Ask user for consent to newsletter

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#324]
Consent for receiving an email newsletter should be asked during the registration process. Consent is not mandatory. Text next to the checkbox: "I agree to receive occasional email newsletters on e.g. new features of FCL Web or user trainings. I can unsubscribe anytime by sending an email to foodrisklabs@bfr.bund.de."

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The checkbox is present on the registration page and can be clicked. When clicked and after having submitted the registration form, the user receives an email with agree button. Done.
