### ISSUE TITLE
Improve example data

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#325]
As a user I would like to have nice example data to test the functions of FCL Web. 

P/O: Please translate in English, add type of business, amount, brand name; add some sample data (all three types: negative, probable, confirmed); use the field address instead of the single columns for street, housenumber, ...

Developer: Please include the updated version of the example data

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Please have a look at the translated data set.
