### ISSUE TITLE
Implement a variety of example data sets

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#326]
As a user I would like to have a variety of example data sets to test (different scenarios --> e.g. crosscontamination, geoclustering).

Developer: Implement the example data as a dropdown menu in the header. Clicking "Load Example Data" opens a drop down menu. In case of multi-staged example scenarios, the dropdown menu should be expandable to the right hand side (e.g. for Baby tea scenario).
Menu points should be named according to the file name or , in case of multi-staged scenarios, according to the directory name (main menu point) and file names (expanded menu points).

When loading FCL Web, it is important that not all example data are preloaded to prevent performance problems (e.g. Babytea 3 is very big). Each example file should be only loaded when requested. 

P/O: Develop a set of example data -> for now Baby tea scenario.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/326?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI

**Comment by afalenski** [comment]
- Dropdown menu is present
- datasets are selectable
- menu items have a shorter name than the filename, which I like.
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/447aa659-197f-4553-bdd7-09a8d76e1cc0)
@bfrgottscma Is this what you had in mind? For me it is done.

**Comment by bfrgottscma** [comment]
Looks good. Done
