### ISSUE TITLE
Tracing properties cannot be set anymore on stations

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#327]
The user cannot set anymore tracing properties (e.g. Mark as outbreak) by clicking the relevant item the context menu.

**Comment by bfrgottscma** [comment]
Unfortunately it still does not work when trying to set tracing properties in a dataset extracted as JSON from the NRW system (see file send via email or in the testfiles in the webapp folder)

**Comment by ruegenbfr** [comment]
Reason: The tracing properties have not been initialized on data import.
