### ISSUE TITLE
Set trace does not affect stations on FW and BW trace

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#333]
When loading the file "Scenario_2_LaSource.json" from the test files and showing the forward and backward trace of a station, the stations on the fw and bw trace do not change their color in the graph and in the data table.

It works in part if you also set a station on the forward trace as outbreak but it should work independent of that (as it is in the example data).

![tracing properties not set correctly.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/0a9743ad-ee58-4523-8808-f259e7e3f0ef)

**Comment by ruegenbfr** [comment]
This issue was caused by a missing attribute mapping definition.
