### ISSUE TITLE
Create components of the filter tab for deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#335]
The deliveries subtab should contain 3 filter boxes, a table and a table footer/status bar. As default, only the "Filter in all columns" filter box should be visible. The other two filter boxes can be activated by clicking on a "More filters" button.
The table footer/status bar should display the count of data lines currently visible in the table.

The current UI status should be saved for the app session

**Comment by afalenski** [comment]
- Filter boxes, table and table footer are visible. 
- The "Filter in all columns" filter is the only one directly usable. The other filters can be shown when clicking the "More filters... click to open" button. 
- Footer shows row count. 
- The filters keep their settings when logging out and logging back in. Only when the browser page is updated (F5) are the filters shown in the default view.
