### ISSUE TITLE
Create deliveries table with test data

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#336]
use example data; use structure of existing data table of current webapp

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Done and tested (see comments in fcl-c335, 337-340, 343).

**Comment by bfrgottscma** [comment]
Obsolete.
