### ISSUE TITLE
Predefined filter functionality for delivieries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#337]
As a user I would like to be able to use predefined filters according to the current webapp --> Filter "Show type" --> all, trace-only, selected-only.

In addition, the count of data lines available after the filter application should be displayed in the table footer

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The "Pre-defined Filters" allow to show only selected deliveries or only traced deliveries or all. The table footer shows the row count. Done.
