### ISSUE TITLE
Add-more-columns functionality for Delivieries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#338]
As default, the data table shows the VIP columns: ....

As a user I would like to be able to customize my data table by adding or removing columns. For this, a button (three dots) should be added as a frozen column on the left side of the data table .

When the table gets to wide, please add a scroll bar. 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Columns can be added via the three-dots-button. When there are more than 5 columns, a horizontal scroll bar appears. Done.
