### ISSUE TITLE
Sort function in Deliveries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#339]
As a user I would like to be able to sort the entries in the table (ascending, descending) for each column separately.

Sorting icons should be displayed in every column of the data table according to the mockup. It should be visible that this specific column is currently sorted ascending or descending.

Click on header name to sort columns. grey: no sorting, black: ascending/descending; triangle shows sorting direction

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
String columns, boolean columns and number columns are sortable by clicking the column header. Ascending/descending is shown with black arrows (like ^). Done.
