### ISSUE TITLE
Filter in all columns functionality in Deliveries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#340]
As a user I would like to be able to filter all entries in all columns of the Deliveries table. The filter should be applied real-time while typing. The filter does not have to be case-sensitive.

In addition, the count of data lines available after the filter application should be displayed in the table footer (extra ticket)

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The filters all work toghether and are applied in real-time. 
Filter-Test with example data: 
- Column filter 'Target' = "re"
- Filter in all delivery data = "bread"
- Select flour, salt, milk, sugar and saffron delivered to Grindel; Pre-defined filters = "Show only selected"
- Complex filters: Lot contains "1" AND "2"

The search is not case-sensitive. Row count is shown in the table footer. Done.
