### ISSUE TITLE
Complex filter functionality in Deliveries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#341]
As a user I would like to use complex filters (for mockup see station table + also see desktop app). Values can be selected via drop-down menu.

In addition, the count of data lines available after the filter application should be displayed in the table footer/status bar 

As a user I would like to be supported when adding a new filter condition: filter condition in the new line should be prefilled --> only value should be empty, all other fields should be filled like line above

As a user I would like to have the filter condition cleared when pressing the "-"button and only one filter condition is present

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Values can be selected via dropdown menu
- this is *true* for columns amount, delivery date arrival, target ID, source ID, ID, source, target, lot, product.
- this is _not true_ for boolean columns selected, backward, forward, cross contamination, kill contamination. It would be helpful if also boolean column values are shown in a dropdown menu. As this is not possible in the stations filter, this will be covered in a new ticket.
- this is _not true_ for double values: Score
- this is _not true_ for column delivery date, although it works for column delivery date arrival. **Please add dropdown functionality.**
- _Unknown_ dropdown functionality: Observed is not available for deliveries.
- Weight?

The number of data rows is shown in the status bar.
When adding a new filter condition the column and the operator are prefilled.
The minus button clears a complex filter row and leaves an empty complex filter row if only one condition exists and is cleared.

@ruegenbfr What about the column 'weight'? Its values are always 0. Does weight exist for deliveries? If not, this column should not be available in the complex filter and not in the delivery filter table.

**Comment by ruegenbfr** [comment]
Value Proposals are fixed.
Filter update on autocomplete selection was fixed.
Conditions with empty values are ignored.

BUT: 
The task: 'In addition, the count of data lines available after the filter application should be displayed in the table footer/status bar'
was not implemented. This should be part of another ticket.

**Comment by afalenski** [comment]
Dropdown functionality for column 'delivery date arrival' works now in Edge, Firefox and Chrome.

**Please add dropdown functionality** for column 'delivery date' using Firefox and Edge (it works in Chrome).

**Comment by ruegenbfr** [comment]
"Please add dropdown functionality for column 'delivery date' using Firefox and Edge (it works in Chrome). Use Baby tea dataset to test before pushing ticket into Review lane."
Functionality was tested on FireFox, Chrome, Edge, Safari before putting it into QA lane. (On MacOSX)
I just tested it again on FireFox and Chrome (on APC [Win10]) and it still worked fine.

**Comment by afalenski** [comment]
Boolean columns offer true (if applicable) and false.
DropDown works for delivery date and delivery date arrival in Firefox and Edge.
Done.
