### ISSUE TITLE
Filter functionality for single columns of Delivieries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#342]
As a user I would like to be able to filter the entries in single columns of the table separately.

After applying the filter, the count of data lines currently shown in the table should be displayed in the table footer.

It should be visible in the column header via a small icon, that this specific column is currently affected by a filter.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
It is possible to filter in columns and the number of rows is shown in the footer.
@bfrgottscma We do not have an icon in the column header of the stations filter. Is it correct, that you would like to have such an icon in the deliveries filter? If yes, this ticket is not completely done.

**Comment by bfrgottscma** [comment]
The icon in the column header is not needed anymore since the filter field always shows the search which was typed in. with that you can identify a filtered column.
