### ISSUE TITLE
Add a "Clear all filters" functionality for deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#343]
As a user I would like to be able to delete all active filters at once without having to click through several filter options. The "Filter in all columns" text field could be a bit shorter and the "Clear all filters" button could be positioned on the right side of it.
**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The 'Clear all filters' button was tested for these filters:
- Column filters (a single filter and two / three together)
- 'Filter in all delivery data' in combination with column filters
- Complex filter in combination with column filters
- 'Filter in all delivery data' in combination with the complex filter and with 2 column filters

The 'Clear all filters' button works in all cases. Done.
