### ISSUE TITLE
Add visibility column for deliveries table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#345]
As a user I would like to be able to see in the data table if a delivery is visible/invisible in the graph.

Visible deliveries should be displayed with an open eye. Invisible deliveries should be displayed with a closed eye and whole data line should be displayed in grey.

I would like to be able sort this column.

I would like to be able to filter this column: Eye:grey=no filter, black eye=display only visible deliveries; black closed eye=show only invisible deliveries; no dropdown the user needs to repeat clicking until the desired filter option is active

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
I cannot set a delivery invisible in the Web App. When I set a station invisible, the hidden deliveries are still shown in black letters in the deliveries filter tab. When I sort by visibility in the deliveries filter tab I get an empty table both for visible and invisible. To me the ticket is not done.

**Comment by bfrgottscma** [comment]
Deliveries are only defined as invisible, if they are set to invisible (not possible so far; separate ticket will be created) or if they are attached to a stations that was set as invisible.

A variable "invisible" has to be created for deliveries, that states true or false.

Deliveries that are merged and therefore not visible should not be defined as invisible.

**Comment by ruegenbfr** [comment]
Done.

Instead of the '**black closed eye**' that was mentioned in the proposal a crossed black eye was used as filter marker to to show only invisible deliveries (analog to the station filter table).

**Please note**: 
Deliveries that are merged **are visible** (only by a single edge). Only visible deliveries are merged.

**Comment by afalenski** [comment]
- The data table shows invisible deliveries in a grey font and the eye is crossed out
- Visible deliveries are shown with open eye and in a black font.
- Deliveries can be filtered and sorted for visibility
a) via the eye button in the filter column header
b) via column "Invisible" (true/false)

Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.101 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
