### ISSUE TITLE
Display invisible delivieries as ghost

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#349]
As a user I would like to temporarily see invisible deliveries (and according stations) as a ghost (in grey) in the graph when hovering over an invisible deliviery in the data table.

If the two connected stations are marked as invisible, both are also shown temporarily.

If two stations with 2 deliveries are visible and 1 delivery is invisible, reorder all three deliveries and show the invisible delivery in grey when hovering over delivery name.

The ghost should be put to front temporarily, as long as the mouse hovers over an invisible delivery in the data table.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Invisible station is shown in grey and on top when hovering over its name, country or ToB in the filter table. Deliveries are also made visible in grey. Done.

**Comment by ruegenbfr** [comment]
Done.
