### ISSUE TITLE
Sync selection of filter table and graph/map

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#352]
A graph/map selection should be reflected in the filter table and vice versa.

Should work for one or more stations as well as deliveries.

- It should be possible to select some stations/deliveries in the graph/map view or in the filter table. This should be done via pressing the strg button (select several single rows) or via pressing the shift button + additional click (select several rows below each other). 
- When selecting one or more stations/deliveries via a frame (left click + mouse drag), the selection should also be visualised in the filter table.

- Colours: See fcl-client#353

- When clicking into the canvas (empty space) or somewhere on the map, the selection in the graph/map and table should be discarded. 
- Also, when clicking on a non-selected entry in the filter table, the selection should be discarded and only the single new selection should be highlighted.
- If only one station/delivery is selected in the filter table, a second click onto this table row should deselect it in the filter table and in the graph/on the map.

@ruegenbfr Should it be possible to select stations AND deliveries at the same time via mouse drag (frame selection)? The same question arises when a user selects for example 2 stations and 2 deliveries via Strg+click. What should FCL Web do here? Should it be possible for example to select full trace for all?

**Comment by ruegenbfr** [comment]
The solution deviates from the specification above as follows:

- When clicking into the canvas (empty space) or somewhere on the map, the selection in the graph/map and table should be discarded. (**only if the shift button is not pressed**, otherwise nothing happens)
- when clicking on an **~~non-selected~~** entry (without **shift** or **Strg**) in the filter table, the previous selection is discarded and only the single new selection should be highlighted. (analog to the known behaviour in the graph)
- If only one station/delivery is selected in the filter table, a second click onto this table row (**with pressed _Strg_-key[_Cmd_-key on Mac]**)should deselect it in the filter table and in the graph/on the map. (**this behaviour is similar to file selection in file browser**)

**Please note furthermore:**
For consistency reasons the behaviour of make stations/deliveries invisible changed. The old behaviour was that the selection for elements which were made invisible was discarded. The new behaviour maintains the selection for these element, because otherwise the related selected row(s) in the filter table get(s) deselected.

**Comment by afalenski** [comment]
- Stations or deliveries selected in the graph / on the map are also selected (highlighted in blue) in the filter table and vice versa.
- Stations and / or deliveries are selectable (also both at the same time): Single rows, several rows in succession (using Shift) and several dispersed rows (using Ctrl). 
- Selecting one or more stations/deliveries can also be done via a frame (left click + mouse drag)
- Rows selected in the filter table become BfR blue and the font becomes white.
- Grey text from invisible stations / deliveries stays in the same grey
- The row over which the mouse arrow hovers becomes darker blue than BfR blue.
- When clicking into the canvas (empty space) or somewhere in the graph / on the map, the selection in the graph/map and table is discarded.
- If only one station/delivery is selected in the filter table / in the graph / on the map, a second click onto this table row while pressing Ctrl/Cmd or Shift deselects it in the filter table and in the graph / on the map.
- When clicking on a non-selected entry (without Shift or Ctrl) in the filter table, the previous selection is discarded and only the single new selection is highlighted.
- When making stations/deliveries invisible, they stay selected, now.

In the outdated Firefox Quantum 68.9.0esr (64-Bit) selecting and deselecting is slow, in the other two browsers it is okay.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.124 (Offizieller Build) (64-Bit)
- Firefox 89.0.2 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
