### ISSUE TITLE
Allow Row Selection in Filter Table

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#353]
The user wants to select one or more rows in the filter table.

Selected rows in the table should get a background in BfR blue (colour #034ea2, which is also the standard colour in Highlighting). For better readability, the black text in selected rows should become white. Grey text from invisible stations / deliveries should stay in the same grey because this is easily readable with a blue background.

**Comment by ruegenbfr** [comment]
Selected rows have the specified BfR blue. 
Only selected rows over which the mouse pointer is hovering appear a bit darker. Please check whether this is suitable. This approach was choosen because unselected rows over which the mouse pointer is hovering appear darker too. This seems to be useful if the table has a lot of columns and the user is scrolling sideways. The hover indicator makes it easier to keep track of the row of interest.

**Comment by afalenski** [comment]
- Rows are selectable: Single rows, several rows in succession (using Shift) and several dispersed rows (using Ctrl).
- Rows selected in the filter table become BfR blue and the font becomes white.
- Grey text from invisible stations / deliveries stays in the same grey
- Darker blue for the row over which the mouse arrow hovers is good.
Done.

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.124 (Offizieller Build) (64-Bit)
- Firefox 89.0.2 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
