### ISSUE TITLE
Changing of tracing settings or visibilities resets filter table column widths

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#357]
If the user changes the width of the filter table columns width manually, they should not be resets by changing the tracing settings (e.g. mark a station as outbreak) or visibilities.

Reproduce:
- Load Example
- Change column width of a filter table column
- Mark a station as outbreak

--> Column width is reseted

**Comment by afalenski** [comment]
Column widths are not affected by changing analysis settings in the graph anymore. Done.
