### ISSUE TITLE
Repeated F2F layout messes up graph

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#359]
When applying the F2F layout repeatedly, the graph is messed up increasingly. The arrow heads become very big, the font behaves weird (letters are overlaying each other), arrows with strange curvature and the graph becomes very narrow and crowded. Repeated F2F also affects the zoom which contributes to messing up the graph. This occurs when using the example data but even more drastically when e.g. using Scenario_1_Outbreak-Baby-Tea from the test data folder. This behaviour is also present when using constraint-based layout but only to a mild extent. Behaviour can be reset when applying Fruchterman-Reingold.

![F2F messes up graph.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/8e85105e-0729-418b-99a1-854a47b0a764)

As a user, I would expect, that the F2F layout is deterministic and does not change when applied repeatedly. Also zoom status should not be affected. Only when window size is altered in between, the layout of the graph should be adapted when F2F layout is applied afterwards. Also arrow head size should not increase.

**Comment by ruegenbfr** [comment]
Arrow size are zoom independent now. Label issues are solved. Repeated F2F always produces the same result (for the same graph).
