### ISSUE TITLE
F2F should use full window width

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#360]
When loading e.g. Scenario_1_Outbreak-Baby-Tea and applying the F2F layout, the network does not use the full width of the window. Therefore it is hard to read especially the delivery labels and the graph looks very crowded.

As a user I am expecting the F2F layout to use the full width.

**Comment by bfrgottscma** [comment]
In my opinion, this is much better since the graph refactoring. Ticket can be closed if you agree, @afalenski.

**Comment by afalenski** [comment]
Is good. Can be improved, but will be in new ticket. Done.
