### ISSUE TITLE
Show Group Members In Station Filter Tab

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#361]
The user wants to see group members in filter tab.
Currently only visible stations and stations marked as invisible are shown in the table.
Group members don't belong to these groups. 
Currently the user cannot filter for group members.

Solution:

Display the group (e.g. a metastation) and below there should be all member stations written in italics. Metastations can be uncollapsed via a small arrow to show the member stations.  Default (collapsed). The station name of the members should have a small indent (if not too complicated).

Filter:
When filtering the data, the filter should be applied to the meta station as well as the members. When the filter is only true for a member, the search result should show the respective member and also the higher level metastation.

Sort:
When sorting the data, sorting should be applied on the station and metastation level. The members of the metastation should always be shown below the metastation and only be sorted within the metastation and not over the whole table. Membership to a certain metastation should always be visible.

Dev Note: First try grouping, if it doesn't work talk to PO. During ticket review it will be decided if colleapsed or not.
http://swimlane.github.io/ngx-datatable/# --> Row Grouping

**Comment by ruegenbfr** [comment]
#### Current state (before code change) in contrast to issue introduction:
- Without active filters **all stations/groups are shown in the filter table**, independent from their visibility or their meta station member ship.
- The user **can** filter for group member ship. The station property '**Contained**' is reflecting whether a station belongs to a group ('**Contained**' = **true**) or not ('**Contained**' = **false**) 

#### Solution (in agreement with PO) deviates from the proposed solution as follows:
- rename '**Contained**' to '**Is Meta Member**'
- introduce new property '**Is Meta Station**', which shall reflect whether a station is a group ('**Is Meta Station**' = **true**) or not ('**Is Meta Station**' = **false**) 
- the collapsing/expanding icon is shown in the first column
- the station name of the members **don't** have a small indent, instead the rows representing members do not show a node symbol

**Comment by afalenski** [comment]
Great solution! The visualisation is easy to understand and filtering is intuitive. Done.
