### ISSUE TITLE
Legend activated per default

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#364]
As a user I would like to have the legend activated per default when loading a new dataset.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Using example data, the legend is shown. When uploading baby tea data no legend is shown. In its JSON it says _"showlegend":false_. If we always want to show a legend when a dataset is uploaded (this is the purpose of this ticket) this should be overridden by the web app... The question remains, what the property "showlegend" is needed for if the legend is always shown when uploading data. It would only be needed for temporary changes but would not be needed to be saved in the JSON anymore.

@bfrgottscma What is your opinion on this?

**Comment by bfrgottscma** [comment]
Yes I agree, the "showLegend" and "showZoom" are not needed, when legend and zoom controls are active per default. Hence those properties also do not need to be written in the JSON when downloading the data. Also it needs to be decided if GIS view should be shown (showGis) when saving data from the GIS view or if per default datasets should always be loaded in graph view first. 

New ticket dealing with the setting saved in the JSON file will be created.
