### ISSUE TITLE
Size of arrow heads

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#365]
Big arrow head when uploading data exported from FCL desktop app (or when repeatedly applying F2F layout)

Ideas to think about:
- Fixed arrow head size which is dependend on station size?
or
- put dropdown menu in graph settings tab to adjust arrow head size

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
The arrow size as discussed above was only partially zoom independent. The
A virtual zooming mechanism was implemented (see ticket #479).

**Comment by afalenski** [comment]
Done.

Tested with:
Win10, Firefox Quantum 68.9.0esr (64-Bit)
(and with other browsers while testing fcl-c359 and fcl-c471)
