### ISSUE TITLE
Replace npm-auditor-ci with npm native solution

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/fcl-client#368]
Änderungen:
- dependency-check scripte aus den packacke.json Dateien entfernt
- dependency-check Scripte in den Jenkins Build Pipelines durch npm audit calls ersetzt
- Output von npm audit in separate Log-Dateien gespeichert anstatt direkt in der Konsole auszugeben (da diese sehr groß werden können)
- Build Pipelines dahingehend geändert das Jobs fehlschlagen wenn Sicherheitslücken gefunden werden (siehe weiter unten zum genauen Vorgehen)
- Job-Parameter "AUDIT_FAIL_LEVEL" zur Steuerung des dependency-checks hinzugefügt. Hier kann definiert werden ab wann ein Job failed wenn Sicherheitslücken gefunden werden. Dies ist zum Beispiel für das MiBi-Portal relevant da wir noch mongo-express mit einer ungefixten high risk Lücke benutzen müssen.

Da jetzt die Builds failen wenn Sicherheitslücken gefunden werden sind wir als Entwickler gezwungen Libraries regelmäßig abzudaten. Um das nicht zu zeitintensiv machen schlage ich vor das die continues und nightly Jobs nur fehlschlagen wenn Sicherheitslücken ab dem risk-level high gefunden werden. Hier muss der Entwickler einschreiten und umgehend ein Update der Libraries machen. Ab dem level low werden die Builds als unstable gekennzeichnet. Bei einem Release sind gar keine Sicherheitslücken erlaubt, diese sollten also mit "AUDIT_FAIL_LEVEL=low" gebaut werden.

Ich empfehle dringend eure (FCL, ZooNotify) Pipelines entsprechend anzupassen.

Folgende Änderungen müsst ihr machen:

- dependency-check Scripte aus den packacke.json entfernen

- build pipelines (client+server) anpassen:
Folgende Zeile im Kopf hinzufügen:
choice(name: 'AUDIT_FAIL_LEVEL', choices: ['low', 'moderate', 'high', 'critical'], description: 'The job fails if a security vulnerability is found in production libraries greater or equal then the AUDIT_FAIL_LEVEL')

Folgenden Teil ersetzen:
stage('Dependency check') {
               steps {
                  script {
                     try {
                        sh "npm run dependency-check:${params.ENVIRONMENT}"
                     } catch(Exception except) {
                        currentBuild.result = 'UNSTABLE'
                        // Re-run dependency checker on prod dependencies & fail build if vulnerability is found here
                        sh "npm run dependency-check:production"
                     }
                  }
               }
        }

durch
stage('Dependency check') {
               steps {
                sh 'npm install'
                  script {
                    try {
                        if(params.ENVIRONMENT == 'qa') {
                            sh "npm audit --audit-level=low --parseable > dependency-check-output.log"
                        }
                        if(params.ENVIRONMENT == 'production') {
                            sh "npm audit --audit-level=low --production --parseable > dependency-check-output.log"
                        }
                    } catch(Exception except) {
                        currentBuild.result = 'UNSTABLE'
                        // Re-run dependency checker on prod dependencies & fail build if vulnerability is found here
                        sh "npm audit --audit-level=${params.AUDIT_FAIL_LEVEL} --production --parseable > dependency-check-output-production.log"
                    }
                  }
               }
        }

Dann müsst ihr noch eure automatischen Jobs anpassen, dass sie die build jobs mit dem Parameter "AUDIT_FAIL_LEVEL=high" aufrufen.

**Comment by birgitlewicki** [comment]
the nightly builds work again.
