### ISSUE TITLE
Extend Content-Security-Policy of nginx conf

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#370]
Please update the Content-Security-Policy in the nginx conf (Reason: fcl-client wants to use an additional tile server).
Please allow the  img-src  tiles.wmflabs.org or *.wmflabs.org 

Current Value:

content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; img-src 'self' *.openstreetmap.org *.cloudflare.com *.googleapis.com data:; style-src 'self' 'unsafe-inline' *.cloudflare.com *.googleapis.com; font-src 'self' *.cloudflare.com *.googleapis.com fonts.gstatic.com data:; frame-src 'self' *.d4science.org; object-src 'self'

Required Value:

content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; img-src 'self' *.openstreetmap.org tiles.wmflabs.org *.cloudflare.com *.googleapis.com data:; style-src 'self' 'unsafe-inline' *.cloudflare.com *.googleapis.com; font-src 'self' *.cloudflare.com *.googleapis.com fonts.gstatic.com data:; frame-src 'self' *.d4science.org; object-src 'self'

**Comment by afalenski** [comment]
Already done.
