### ISSUE TITLE
Move fcl-server-audit branch to fcl-server repository on gerrithub

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/fcl-client#397]
The current fcl backend is still located in the fcl-server-audit branch of the mibi-portal-server repository. It should be moved to the fcl-server repository on gerrithub in order to perform code reviews for fcl backend implementations.

If possible the backend code should be adjusted:

- remove institution dependencies
- check if the data build dependencies can be removed including the corresponding jenkins jobs
- remove other not used code like sample management, catalogue etc

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/fcl-server #25](https://github.com/SiLeBAT/fcl-server/issues/25) via [**ZenHub**](https://www.zenhub.com/)
