### ISSUE TITLE
Wrong default color for observed deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#398]
When setting a delivery observed, the delivery is displayed in blue. However, as a user I expect the color for observed deliveries and observed stations should be the same, i.e. green, per default (except if there are other color settings given in the JSON).

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Additionally the color for observed edges was set in the example data.

**Comment by afalenski** [comment]
When setting a trace for a delivery, it becomes green. Done.

**Comment by ruegenbfr** [comment]
This is correct behavior.
Baby tea has a its own highlighting definition within the (json) model. This definition is relevant [see above: 'green, per default (except if there are other color settings given in the JSON)'].
Only if no definition is present in the imported json the web app applies the default settings.

**Comment by afalenski** [comment]
Technically, you are correct. From the point of view of the user it is confusing to have a different colour for observed stations than for observed deliveries. As soon as we have implemented highlighting this problem will be solved. This ticket is done.
