### ISSUE TITLE
Improved score-dependent size of nodes

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#400]
As a user I would like to see more prominent differences in the score-dependent size of nodes.

Please start with score=1 has 3x size of score=0. Then P/O evaluates if this is fine or if we should go higher or lower than 3x.

node size in graph settings should be minimum node size

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
To me 3x size is too large. Please try score = 1 with a size twice as large as score = 0.
@bfrgottscma What is your opinion on this?

**Comment by bfrgottscma** [comment]
Yes, two times are probably enough. In the desktop app it seems like it is 2x as well.
