### ISSUE TITLE
Highlighting: Make anonymise button less prominent

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#404]
As a user I do not want to click the anonymise button by accident. See [#730](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/gh/silebat/fcl-client/730)

<del>To be discussed:</del>
<del>- The very large button could be made smaller</del>
<del>- Another position (not at the top) could be chosen</del>
<del>- A window asking for confirmation to anonymise could pop up</del>

**Comment by bfrgottscma** [comment]
outdated because anonymisation is realized in #731. Closed.
