### ISSUE TITLE
All menu symbols are hidden when on profile page

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#405]
As a user having clicked on the profile page I would like to return to the tracing view more easily. Now I must click on the FoodChain-Lab button (top left), then on the large Tracing View Logo and then I can see the full FCL graph again. 

When on the profile page, please show the Tracing View Button (see below) next to the profile symbol to be able to return to the graph.

The screenshot is from the ROA view:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/e3f9b2b5-3cfd-4582-a7aa-33dbb1c01600)

**Comment by bfrgottscma** [comment]
Tracing view button is displayed, clicking it leads the user to the tracing view and latest UI status is shown. Done
