### ISSUE TITLE
FCL shows in two different accounts the same data

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#406]
As a user with two FCL-Web-App accounts I think it is strange that FCL displays the identical view when I logout from one account and enter with the other account.

To reproduce:
- Log in into FCL-Web-App
- Load example data
- Select 2 stations
- Open the filter menu, click on Highlighting / Deliveries
- Logout
- Log in into FCL-Web-App with your second account
- Click on the FCL logo
Now you get the identical view which you had when logging out from the first account. The same works with uploaded data, too! Is this a security issue?

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by ruegenbfr** [comment]
The tracing state is reseted on logout. So the view after an successful login is always identical.

**Comment by afalenski** [comment]
Reproducing the described test and after logging in with the second account you see the FCL logo and after clicking on this logo you get an empty FCL Web App screen, just as expected. Done.
