### ISSUE TITLE
Filter table column headings are not always above table values

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#407]
As a user I would find reading the filter table easier when its headings are always above the corresponding values.
CASE1:
To reproduce:
- Load the dataset "Scenario_3_All-Stations.json".
- Add 7 more columns so that the horizontal scrollbar appears; one of them should be the column "Outbreak".
- Filter in station names for "cons".
- Use the mouse and drag the horizontal scrollbar to the right so that the column "Outbreak" is in the middle of the filter view.
- Filter in column "Outbreak" for "tr". As no station is marked as outbreak, the filter gets empty.
- Delete "tr".
Now, the column names stay as they are, but the values are from the first columns and the horizontal scrollbar is on the left and not in the middle anymore. By changing the position of the horizontal scrollbar the filter table gets updated and the column headings are correct again.

CASE2:
To reproduce:
- Load the dataset "Scenario_3_All-Stations.json".
- Add 7 more columns so that the horizontal scrollbar appears
- About 6 columns are visible. Click into the column filter of the first column, hit TAB 6 times to be able to enter text into the 7th column.
The column headings move so that the user can see the complete filter text box of column 7. However, the values do not move, so that the 7th column heading is now above the values of column 6.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
Case 1: Bug fixed
Case 2: Bug not fixed. Please fix.

**Comment by ruegenbfr** [comment]
Tab key control was disabled for column headers.

**Comment by afalenski** [comment]
Case 1: Bug fixed
Cae 2: Tab not functional as before (goes vertical instead of horizontal), thus bug does not occur. Done
