### ISSUE TITLE
Consent GDPR: * not part of link

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#410]
Please keep the * for the checkbox for consent to Privacy Policy but do not include it in the link + font color should be black.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The star is black and not part of the link. Done.
