### ISSUE TITLE
Legend does not contain all colours in GIS mode

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/fcl-client#416]
@afalenski commented on [Mon Jun 22 2020](https://github.com/SiLeBAT/fcl-server/issues/22)

As a user I would like to see all station colours in the legend when in the GIS mode. Delivery arrows are always visible in the legend (e.g. if "Set full trace" is activated).

To reproduce:
- Load example data in graph mode
- Switch from graph mode to GIS mode: The yellow dot next to "Common Link" is missing.

Another buggy behaviour:
- Load example data in graph mode
- Right click on Bäcker Haake and click "Mark as outbreak": The yellow dot next to "Common Link" is there, but the red dot next to "Outbreak" is missing.
- Switch to GIS mode: No dot is visible
- Switch back to graph mode: Both dots are visible

Another buggy behaviour:
- Load example data in graph mode
- Switch to GIS mode
- Right click on Bäcker Haake (top left, below Bremen) and set full trace: Station dots for "Observed", "Forward tracce" and "Backward trace" are visible, but not the yellow dot for "Common link".
- Switch to graph mode: The same but vice versa (yellow dot visible, the others not)

**Comment by ruegenbfr** [comment]
Bug was also present in Schema-View.
Bug was reproducible in Edge, Firefox, Chrome but not Safari.

**Comment by afalenski** [comment]
Works fine with the example data.
Uploading the Baby Tea dataset the legend looks strange, see screenshot. In addition, the legend checkbox in the graph settings is not checked although the legend is displayed. When trying to display the context menu on one station the web app crashed. This was reproducible. Please fix.
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a1fe3de5-7d46-4c35-9ea4-6f71aa1f9ab6)

**Comment by afalenski** [comment]
All is fine, now. Done.
