### ISSUE TITLE
Station property dialog shows hidden deliveries

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#417]
User sees hidden deliveries in station properties dialog. 

Reproduce:
- load example,
- Make 'Spices Of The Work Ltd.' invisible
- Open Context Menu above station 'Arno's Spices Sales'
- Choose 'Show Properties'
- See below 'Incoming Deliveries'

The ingoing delivery from the 'Spices Of The Work Ltd.' station is still listed.

**Comment by arne-z** [comment]
Waiting to discuss getIngredientsByLotKey behavior with Marco. 
=> Hopefully Wednesday.

**Comment by bfrgottscma** [comment]
It would be great if invisible deliveries could be displayed in grey in the station property dialogue instead of hiding them.

**Comment by afalenski** [comment]
- In the properties dialogue, invisible deliveries are shown as a grey box, connections between invisible deliveries are shown as grey line (RGB 211, 211, 211). This is the same colour as in the filter table. Good!
- Hovering over **visible** deliveries in the properties dialogue still highlights the deliveries in the graph in the greyed out background.
- Hovering over **invisible** deliveries in the properties dialogue does not highlight the deliveries in the graph in the greyed out background.
Done.
