### ISSUE TITLE
Adapt size, position and visibility of frame indicating stations without gis information

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#418]
The user wants to see the frame (which is indicating stations without gis information) only when stations are display without gis information.
The size and position of the frame shall be fitted to the space containing the station with gis information.
There should be maximal 1 frame in the gis view.

Reproduce visibility issue (A):
- Step 1:
  - reload web app
  - load attached json (which contains both stations with and stations without geo coordinates)
  - Switch to gis view
  --> Frame is shown
- Step 2:
  - load example
  - switch to gis view
  --> Frame is still shown, but all stations have gis information

Reproduce size/positioning issue (B):
- Repeat step 1 from issue A
- make outlier station 'Voggel Anton' invisible
   --> frame is not tight anymore

Reproduce more than 1 frame issue:
- Repeat issue B reproduction
- push 'reset zoom' button
  --> 2 Frames are shown

[JSON](https://app.zenhub.com/files/61294409/0e870217-6a10-42c0-912d-f2b9e515b7e3/download)

**Comment by afalenski** [comment]
The described issues were not visible anymore. Done.

Tested with:
Win10, Firefox Quantum 68.9.0esr (64-Bit)
Win10, Firefox 86.0 (64-Bit)
Win10, Chrome 88.0.4324.190
Win10, Opera 74.0.3911.203
Win10: Edge 89.0.774.45
