### ISSUE TITLE
Show GIS map "Black & White"

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#419]
As a user who has chosen the GIS map "Black & White" I would like to see a map and not only correctly positioned stations and deliveries on a light grey background. If the option "Black & White" is not available anymore I do not want to be able to select this option.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
see ticket #288
