### ISSUE TITLE
Web App: Add mouse over information to buttons

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#42]
Please add the following mouse over information to the buttons:

Top left: Settings Menu, FoodChain-Lab (go to dashboard), Center
Top right: Profile

**Comment by bfrgottscma** [comment]
Update:
Some of the above mentioned mouse overs already implemented.

Remaining
Top left: Settings Menu, FoodChain-Lab (go to dashboard), Center
Top right: Profile

**Comment by ruegenbfr** [comment]
Solution:
Set tooltips for:
**≡** [Toggle button fro graph settings]: 'Show/Hide Graph Settings'
[FoodChain-Lab button]: 'Go To Login' [is not logged in] / 'Go To Dashboard' [otherwise]
[User Profile Icon]: 'Show Account Options'
