### ISSUE TITLE
Begin all station and delivery column names with capital letter

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#422]
As a user who chooses columns to display I am confused why some column names are spelled with a small letter - is information in these columns less reliable?

Write stations and deliveries in complex filter and in the 'choose additional columns' menu with capital letter:
- Standard columns: amount -> Amount
- When deliveries are aggregated and only one delivery line is shown (see Scenario_3_All-Stations.json): Write all columns in the 'properties' window with capital letter at the beginning, e.g. "_chargen.treatment of product during production" -> "_Lots.Treatment of product during production" see also [#421](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/silebat/fcl-client/421)

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/422?planning-poker) with ZenHub @bfrgottscma

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/422?planning-poker) with ZenHub @ruegenbfr @MicheleK17 @GerberI

**Comment by bfrgottscma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/422?planning-poker) with ZenHub @Fusiakja

**Comment by afalenski** [comment]
Is completely contained in #421 and thus duplicate.
