### ISSUE TITLE
Complex Filter: Offer dropdown also for boolean values

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#423]
As a user working with the complex filter I would like to be able to choose from a dropdown list for columns with boolean values (true / false).

Columns: All boolean columns, e.g. selected, backward, forward, cross contamination, kill contamination, oubreak, common link, invisible, simple supplier, dead end, dead start, contained

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
Ticket done in the framework of another ticket --> closed
