### ISSUE TITLE
List existing highlighting conditions (colors+shapes) for stations separately

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#426]
As a user I would like to see which color/shape highlighting conditions are present in the dataset.

Create a list of the  color/shape highlighting conditions for stations (station tab) according to the mockup.

The list should contain columns with
- name of the highlighting condition
- respective symbol which is also used in data table and in legend
- a column showing an exclamation mark when highlighting rules are conflicting (see extra ticket (not written yet))
- a pen symbol (Should be clickable, see extra ticket #429), 
- a box containing "L" (Should be clickable, see extra ticket #427)
- arrows to sort the list (see extra ticket #431)
- the number of stations/deliveries affected  by this highlighting condition (for now only as placeholder, separate ticket will be written).

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by birgitlewicki** [comment]
Arrows to sort the list:
This is not yet implemented and will be done with ticket #431

**Comment by bfrgottscma** [comment]
Kill Contamination is not listed in the hightlighting condition list. Might be caused by the fact, that station can be set as "Kill Contamination" but the station is not marked in grey anymore (bug ticket will be written)?
