### ISSUE TITLE
Add new highlighting condition

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#428]
As a user I would like to add new highlighting conditions.

See mockup and desktop app.

Please add a button under the condition list with a "+". Clicking on th button opens a dialogue. The user can enter a name (free text), select from shapes and colours and set up rules.

Shapes: all Web-App shapes
Colour: Colour picker, RGB entry, colour code entry

Property values and operations should be the same as used for the complex filter function. For the values, offer the values that are true for the respective property. For the Row menu allow and/or/remove. When remove is selected, the rule is deleted.

Apply --> condition is applied
Cancel --> dialogue closed
OK --> condition is applied, dialogue closed

When highlighting dialogue is open, clicking on another condition is blocked --> you have to click Apply/Cancel/OK before.

This dialogue should also have a button that removes the whole highlighting condition.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by birgitlewicki** [comment]
There are still several issues concerning the functionalities. They need further conceptual discussions and should solved in new tickets, e.g. the button to remove the highlighting condition: is present but not functional

=> discussions in the upcoming sprint meeting

**Comment by bfrgottscma** [comment]
Core functionality is present. Some refinement needed --> via separate tickets. I see this ticket as done.
