### ISSUE TITLE
Change existing highlighting conditions

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#429]
As user, I would like to be able to change existing highlighting conditions. When clicking the pen symbol in the condition list, the highlighting rule dialogue opens below the respective condition. The pencil becomes black when in edit mode.  
The highlighting rule dialogue is the same as the dialogue for new highlighting conditions, but filled with the respective settings. As soon as colour or shape is changed, this is shown next to the name in the highlighting condition table.

Add the following buttons: OK (save changes and close edit mode), Apply (save changes and leave edit mode open), Cancel (dont' save changes and close edit mode) 

Pressing OK and Apply changes the graph and the legend

see mockup, page 7

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
Changing existing highlighting conditions is possible now.
- When clicking the pen symbol in the condition list, the highlighting rule dialogue opens below the respective condition. The pencil does not become black when in edit mode. It is greyed out together with all other pencils, dustbins and show-in-legend buttons. Fine for me.
[x] The highlighting rule dialogue is the same as the dialogue for new highlighting conditions, but filled with the respective settings. 
[x] As soon as colour or shape is changed, this is shown next to the name in the highlighting condition table.
[x] Buttons OK, Apply and Cancel are there and work
[x] Pressing OK or Apply both change the graph and the legend

**Comment by bfrgottscma** [comment]
Works fine. Just a minor thing to change: Please change the order of the buttons to OK, Cancel, Apply since this is the order recommended by Windows
