### ISSUE TITLE
Make highlighting conditions sortable

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#431]
As a user I would like to be able to sort the highlighting conditions manually (only one at the same time).

Via drag and drop --> mockup: https://miro.medium.com/max/5568/1*oqCbeehY2NKeeNUCkuaagQ.png
Moving should only be possible inside the highlighting condition list if possible --> only in list should be drop target; in other positions x to show you cant drop it here

The order in the condition list AND in the legend should be affected by sorting. Tooltip (move up/down). 

Sorting of legend: Stations have priority if you have the "same" condition for stations and deliveries (e.g. forward trace).

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
The sorting of highlighting conditions for stations works fine. 
- You can drag and drop the 6dots icon as well as the station names. 
- Dragging is only possible in the highlighting area. It is not possible to drag the highlighting condition out of the area. Good.
- The tooltip is not really a classical tooltip in text form. Instead, the mouse arrow becomes a double-headed arrow, which is understood intuitively.
- After the rearrangement of a station highlighting condition, the legend is also rearranged.
- If the condition contains colouring and if several conditions with colouring apply to a station, the order of the coloured stripes in the station symbol in the graph is changed, too.

To be changed:
- The font in the station highlighting conditions is Roboto **sans serif**. However, when dragging the condition the font changes to a font with serif. This was not defined in the ticket. The font should stay the same. Please change.

The sorting of highlighting conditions could only be tested for stations. Thus, priority of stations over deliveries could not be tested. This ticked is dependent on the completion of the delivery highlighting conditions table.

**Comment by afalenski** [comment]
The font was changes. Looks good. Done for sorting **station** highlighting conditions.
