### ISSUE TITLE
Make deliveries invisible + clear invisibility

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#432]
As a user I would like to be able to make one ore more deliveries as invisible via clicking on it and activating the context menu. 

- New context menu option "Make invisible" for deliveries.
- Invisible deliveries are shown in grey in the deliveries filter table and can be filtered via the 'eye' column.
- The boolean column "Invisible" can be selected in the 'add more columns' menu of the deliveries filter table and in the complex filter; via this column it is possible to filter for invisible = true/false.

Clearing the invisibility should be possible via clicking into the empty space, activating the context menu and clicking "Clear invisible deliveries"
When making a delivery visible again, the connected stations should also be become visible again.

![fcl-c432 Making invisible deliveries visible.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/27889b91-6a67-4832-9bdb-2aebcea639c9)

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Comment by ruegenbfr** [comment]
Done.

**Comment by afalenski** [comment]
- There is a new context menu option "Make invisible" for deliveries.
- Invisible deliveries can be filtered via the eye-symbol in the filter table.
- Filtering via column "Invisible" is possible
- see more tests in fcl-client #439
Done.

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.101 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
