### ISSUE TITLE
Misleading graph context menu

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#434]
The user selects a node and an edge in the graph. If he opens the context menu over the selected node, he can choose e.g. 'Set Trace --> Full Trace'.
But only the selected node is traced.

The point is: A selected option is only applied for the type of element the mouse hovers over. Which might not be transparent enough for the user.

**Comment by bfrgottscma** [comment]
Should be fine if #435 is implemented
