### ISSUE TITLE
Trace setting is not applied on graph context selection

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#435]
If the user selects several nodes/deliveries in the graph and opens the context menu over a selected element, an sets an trace option (Full, Backward or Forward), the option is only applied for the element the mouse hovers over.

Please allow setting of trace for multiple selected elements (several stations, several deliveries, mix of stations and deliveries).

If nothing is selected, then the trace is only set for the one station/delivery the mouse hovers over.

**Comment by ruegenbfr** [comment]
Done.

**Comment by afalenski** [comment]
- The 2 deliveries "Strawberry Cake" and "Cherry Cake" were selected and Trace was set to full trace -> the trace is shown for 2 deliveries.
- Stations "Case 1" and "Case 2" were selected and Trace was set to full trace -> the trace is shown for 2 stations.

**Discussion needed:**
- Right click on station "Case 1" and select "Set Trace" -> "Backward Trace": Only the trace for Case 1 is shown. I expected, that the trace from Case 2 stays active.
- Right click on station "Case 1" and set trace to full trace. Now, right click on station "Case 2" and set trace to full trace. Only the trace for Case 2 is shown. I expected, that the trace for both stations should be displayed. 
In FCL desktop it is possible that every station or delivery can be set or unset to "observed" individually and independent of other stations. Here, all trace settings need to be done at once. If you receive a JSON file with observed stations or deliveries and would like to add more, this would not be possible.

Solutions:
1. Re-write ticket text and write additional one.
2. Discuss and do in this ticket.
@bfrgottscma What are your thoughts about this?
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.101 (Offizieller Build) (64-Bit)

**Comment by ruegenbfr** [comment]
The matter was discussed before implementation with the PO. The PO agreed that on setting new traces all previous traces shall be discarded.

##### Proposed Extension: 
- Add a global setting that prevents the removal of old traces before adding a new one, e.g. like:

- [ ] Reset Traces before Adding New Traces

**Comment by afalenski** [comment]
This ticket is done. A new ticket for global setting will be created.

______
**Re-tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.114 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
