### ISSUE TITLE
Rename column 'observed'

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#436]
As a user not knowing FCL Desktop I am confused about what to expect from column 'Observed' showing mostly the value 'none'. Change column name to 'Trace Type'. Its values can be 'none', 'full', 'forward' and 'backward' and they are only not 'none', if 'Set Trace' is activated for a station.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
Yes, sounds good

**Comment by j-hha** [comment]
branch: story/436-rename-column-observed

**Comment by afalenski** [comment]
@j-hha I see only a column "Observed" in the filter table. There is no "Trace Type" column. What did you change?

**Comment by j-hha** [comment]
@afalenski it's definitely present in the code. I just checked. I assume, the code hasn't been deployed yet. I don't know how your deploy process works yet. The docs just say 'build triggered periodically' and I don't seem to have any access to the respective pipelines yet. So I'll have to ask Marco about this when he gets in later today. Sorry about that.

**Comment by j-hha** [comment]
@afalenski Jetzt ist der deploy durchgelaufen.

**Comment by afalenski** [comment]
- Column name "Observed" was renamed to "Trace Type" for stations and deliveries.
- Entries in legend and highlighting settings are still called "Observed"
- The filter table shows in column "Trace Type" the values none, full, forward and backward.
Done.
