### ISSUE TITLE
Highlighting: Colour for observed should be identical for stations and deliveries

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#437]
FCL DESKTOP TICKET

As a user I find it confusing that the colour for observed ('Set Trace') can be different for stations and deliveries. A default colour (green) is needed for both stations and deliveries. As soon as highlighting is implemented, such cases (usually coming from FCL desktop) should be marked with an exclamation mark in the list of highlighting conditions and there should be a mouse-over message warning that colours differ for observed stations and deliveries.

**Think of Tests**
- [ ] Excel testsheet needed

- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Comment by bfrgottscma** [comment]
Colors for observed statios and deliveries were harmonized in FCL Desktop. Discrepancies can only occur now for older datasets from FCL Desktop or when the user actively changes the default colors. There is no need to adapt FCL Web for such corner cases (cost higher then benefit).
