### ISSUE TITLE
Enhance context menu "Clear Invisibility"

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#439]
The contex menu "Clear invisibility" should have sub menu for "Clear invisible stations", "Clear invisible deliveries", "Clear all".

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Done.

##### Please note:
Menu availability:
The option '**Clear Invisibility**' is only enabled if invisible elements exist.
The sub menu option '**Clear Invisible Station**' is only enabled if invisible stations exist.
The sub menu option '**Clear Invisible Deliveries**' is only enabled if invisible deliveries exist, that there made explicitly invisible (they are not only invisible because their target or source is invisible, but because the user marked them as invisible).

Using the menu entry '**Clear Invisible Deliveries**':
This option effects only deliveries which were set explicitly (by using '**Make Invisible**' on the deliveries) to invisible. They become visible, **only** if the attached stations are visible.

**Comment by afalenski** [comment]
Invisibility tests
1. Single delivery
a) Make a single delivery invisible: Right click on delivery "Flour" between stations "Food Sales Pappenheim" and "Grindel..." -> Make invisible
- [x] Graph: delivery disappears, stations stay visible
- [x] Filter table: delivery is shown in grey, visibility eye is crossed out, invisibility column value = true
- [ ] **hovering over the invisible delivery in the filter table makes it appear in grey**

b) Make a single delivery visible again
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear Invisible Deliveries" -> delivery reappears
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear All" -> delivery reappears

2. Serveral deliveries

a) Make several deliveries invisible, one after another: "Flour" (see above), "Salt";  "Butter-cream Cake" between stations "Grindel..." and "Case 4"
- [x] One delivery after the other disappears, stations stay visible

b) Make all deliveries visible again
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear Invisible Deliveries" -> delivery reappears
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear All" -> delivery reappears

c) Make several deliveries invisible all at once: Select (holding shift) "Flour" (see above), "Salt";  "Butter-cream Cake" between stations "Grindel..." and "Case 4"
- [x]  right click on one of the deliveries -> select "Make Invisible"

d) Make all deliveries visible again
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear Invisible Deliveries" -> delivery reappears
- [x] Right-click into an empty space in the graph, select "Clear Invisibility" -> "Clear All" -> delivery reappears

3. Invisible stations and deliveries: 1 station, 1 delivery

a) Make "Flour" invisible, afterwards "Food Sales Pappenheim"
- [x] All 10 deliveries connected to the station disappear and are shown in grey in the deliveries filter
b) Right click -> Clear Invisibility -> Clear Invisible Deliveries
- [x] Nothing changes
c) Right click -> Clear Invisibility -> Clear Invisible Stations
- [x] The station and all 10 deliveries become visible
d) Settings from (3a), right click -> Clear Invisibility -> Clear All
- [x] The station and all 10 deliveries become visible
e) Settings from (3a), right click -> Clear Invisibility -> Clear Invisible Stations
- [x] The station and 9 deliveries become visible, flour stays invisible

4. Invisible stations and deliveries: 2 stations, 4 deliveries in between of which 1 is made invisible

a) Make "Flour" invisible, afterwards "Food Sales Pappenheim", afterwards "Grindel..."
- [x] 2 stations and 15 deliveries become invisible
b) Right click -> Clear Invisibility -> Clear Invisible Deliveries
- [x] Nothing changes
c) Right click -> Clear Invisibility -> Clear Invisible Stations
- [x] The 2 stations and all 15 deliveries become visible
d) Settings from (4a), right click -> Clear Invisibility -> Clear All
- [x] The 2 stations and all 15 deliveries become visible
e) Settings from (4a), right click -> Clear Invisibility -> Clear Invisible Stations
- [x] The station and 9 deliveries become visible, flour stays invisible

More tests are necessary if it will be possible to make stations and/or deliveries (in)visible via a click on the eye in the filter table.

@ruegenbfr Please have a look at the box in test 1a which is not checked and implement the functionality (or state if it is to be done in another ticket).

**Comment by ruegenbfr** [comment]
The feature Test 1a is part of ticket ...

**Comment by afalenski** [comment]
______
**Re-tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Firefox Quantum 68.9.0esr (64-Bit)
