### ISSUE TITLE
Validate User Registration Information

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#465]
The user should not be allowed to enter anything into user name.

on server side and client side

See ticket: [gitlab#80](https://gitlab.bfr.berlin/gerberi/SecurityConcept/issues/80)

Dev Note: see MibiPortal password check

**Comment by afalenski** [comment]
Entering specific symbols as First Name or Last Name in the user registration form results in an error message in red.
______
**Tested with**
OS: Windows 10

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
