### ISSUE TITLE
Show amount in ROA style 2

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#466]
As a user having generated a ROA report I would like to see the unit from the product amount and not just the number.

Add a dropdown list for units in the ROA Report Configuration. 

In [fcl-client#440](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/silebat/fcl-client/440) the columns "amount" and "lotQuantity" were made selectable in the ROA Report Configuration. For the following columns the amount number is selectable but the unit needs to be added to the ROA report:
- _lieferungen.delivery_amount -> _lieferungen.delivery_unit
- product amount -> product unit
- focus product amount -> focus product unit

Ticket part 1:
These are column pairs. One column makes no sense without the other. They are always exportet in column pairs (from EFSA or from FCL Desktop). Thus, there is no need for the user to select the corresponding unit column. When the user selects the number column, the corresponding unit column should be selected in the unit dropdown list automatically.

Ticket part 2:
For all other columns the default value for the unit dropdown list shall be "None". The user can click on the dropdown list and select other columns, e.g. new columns created by the user in the All-in-one-template (imported to FCL desktop and exported as JSON).

Example:
- Load Baby Tea dataset (Scenario_1_Outbreak-Baby-Tea.json)
- Click on ROA Style
- In the opening ROA Report Configuration window select "_lieferungen.delivery_amount"
- Click on "Generate Report"
- In the ROA report the first box in the top left for station "Primary producer: Organic Herbs Egypt Inc. (OHEI)" shows the product details:
_Dried organic camomille flowers, Lot no. DC 17
Lot: 1799261720
Amount: 6000_
It remains unclear, whether the unit is packages, tons or something else.

Expected result:
_Dried organic camomille flowers, Lot no. DC 17
Lot: 1799261720
Amount: 6000 **kg**_

**Comment by ruegenbfr** [comment]
#### Solution (as requested):
The amount row in lot box label has 2 property selectors now. One for the amount one for the unit.
The default amount prop is 'lotQuantity', since it does not end with 'amount', the default unit is 'None'.

An amount property select action by the user triggers an update of the unit property.
If the new amount property x ends with 'amount' and there is a property y which ends with 'unit' and x without the suffix 'amount' is equal to y without the suffix 'unit', then y is used as unit property 
otherwise 'None' is used as unit property. (Please note: case is ignored for property name comparisons)

An unit property select action by the user triggers nothing.

**Please note:** The amount property selection for the sample boxes is not affected by this ticket.

**Comment by afalenski** [comment]
- choosing column "_lieferungen.delivery_amount" as number, the column "_lieferungen.delivery_unit" is selected automatically as unit, the same with column pairs "product amount" -> "product unit" and "focus product amount" -> "focus product unit"
- the user has the option to change the unit and to do strange things like to display the best before date as unit (which is good and the user's right)
- choosing column "Amount", the unit is not pre-selected.

Great! This is comfortable!
Done.


- "unknown" was stated twice in all browsers with distiller dataset for FocusProductAmount and ProductAmount; in Firefox Quantum 68.9.0esr (64-Bit) also with example dataset and column "_lieferungen.delivery_amount"; also, see #554
- many digits were shown for dataset Scenario_1_Outbreak-Baby-Tea.json, see #553
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset
- Scenario_1_Outbreak-Baby-Tea.json
- Distiller2FCL_Uploaded_FToF_AndDownloaded.json

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by ruegenbfr** [comment]
The describe bug is not an effect of this ticket code change, it also is present in the prod version.

**Comment by afalenski** [comment]
Then this ticket is done.
