### ISSUE TITLE
Delivery properties column filter: Column headers and row contents not in sync

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#467]
**Describe the bug**
When entering something into the deliveries property filters which is not in the table and after deleting this filtertext, column headlines stay where they were while row contents of the first columns are shown (ID, product, lot) below wrong headlines.

**To Reproduce**
- Load example dataset
- Left click on 2 deliveries while holding shift 
- Right click on one of the deliveries -> context menu -> click on "Show Properties" 
- Continue with A or B:
A
- Type "x" into a boolean column filter (e.g. Cross contamination) -> no row is displayed
- Delete the "x" -> column headlines stay where they were while row contents of the first columns are shown (ID, product, lot) below wrong headlines
B
- Slide the horizontal scroll bar to the right until you see the column "Cross contamination"
- Type "qjy" into the general properties filter (or something else which is not in any column) -> no row is displayed
- Delete "qjy" -> column headlines stay where they were while row contents of the first columns are shown (ID, product, lot) below wrong headlines

**Expected behavior**
After having cleared filter texts still only that colum content should be found below column headings which belong there.

**Desktop (please complete the following information):**
Telearbeits-VM, 8 GB RAM, 2,69 GHz, Asus  Monitor
Win10 Enterprise 64-Bit
Firefox Quantum 68.9.0esr (64-Bit)

Note: Bugfix might work like the one which was done on the station filter table.

**Comment by ruegenbfr** [comment]
This problem is present in then mentioned dialog **and in both filter tables**. This issue has not been fixed yet for the station table. Issue #407 is still open.

It can be reproduced additionally on:
- Chrome (86.0.4240)
- Edge (86.0.622)
- Safari (13.1.2)

**Comment by afalenski** [comment]
Very good! Bug fixed. Done.
