### ISSUE TITLE
Selection not displayed in saved image

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#468]
As a user I expect that if I select a station or delivery and click "save image", this selection is not shown in the saved image of the graph.

selection should be conserved

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Issue cannot be reproduced anymore.

#### Tested for schema & gis graph on:
- firefox version 115.3.1esr
- chrome version 117.0.5938.149
- edge version 115.0.1901.200
- safari version 15.4
