### ISSUE TITLE
Password forgotten toaster always identical

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#469]
As a P/O I want the toasters for the "Password forgotten" function identical so hackers cannot guess user names. The toaster when typing in an incorrect email address should be the same as the one when typing i a correct email address.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Please discuss issue further on [#81](https://gitlab.bfr.berlin/gerberi/SecurityConcept/issues/81)

**Comment by birgitlewicki** [comment]
The server response is now also the same (200) for a valid an an invalid email.

**Comment by afalenski** [comment]
When entering a correct email address with wrong password OR 
when entering an incorrect email address with wrong password
the toaster message is identical. Done.
