### ISSUE TITLE
Names of stations/deliveries cut off or overlayed after zooming

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#471]
When loading the example dataset and zooming out, longer names of stations and deliveries are cut-off on both sides.
When zooming in, the letters of station names are partly overlaying each other. This behaviour occurs in Firefox but not in Chrome.

**Screenshots**

Zoomed in: 
![Bug_station and delivery names overlay.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/4c8e8927-f6ff-4224-b27c-e912d5c285ac)

Zoomed out:
![Bug_station and delivery names cut-off.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/ec31eaa6-c4a3-47e4-9263-bb3ed93f1498)

**Desktop:**
 - OS: Windows 10
 - Browser Firefox
 - Version 68.9.0esr (64-Bit)

**Comment by ruegenbfr** [comment]
Could not reproduce the issue with Firefox (81.0.1, 82.0.3) on Mac OSX (10.13.6).

**Comment by afalenski** [comment]
Could reproduce the 'zoom in' part of the described bug on Win10, Firefox Quantum 68.6.1esr (64-Bit) (BfR desktop PC).

**Comment by ruegenbfr** [comment]
Edge and node labels should not be cut off/ or overplayed anymore. 
The edge arrows are zoom independent know.

**Comment by afalenski** [comment]
No text overlay, nothing cut off and - what a fantastic add-on - no gigantic arrowheads, either. Great! Done.

Tested with:
Win10, Firefox Quantum 68.9.0esr (64-Bit)
Win10, Firefox 86.0 (64-Bit)
Win10, Chrome 88.0.4324.190
Win10, Opera 74.0.3911.203
Win10: Edge 89.0.774.45
