### ISSUE TITLE
Filter table displays blank rows

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#472]
As a user I would like to see the row content and not blank rows.

Reproduce issue:
- Load dataset with a lot of deliveries (alternatively load example data and make browser height so small that not all rows fit into filter tableview at once)
- Scroll down in filter table
- Enter '$' in column 'Name' --> table shows 'No data available.'
- Remove '$' from column 'Name' --> the first rows are blank
- Scroll in filter table --> rows become non blank again

The same behavior can be observed in the delivery properties dialog:
- Select all of deliveries in graph
- Open context menu above a selected delivery (usually opened by right click)
- Select 'Show properties'
- Scroll to last row of table
- Enter '$' in column 'Name' --> table shows 'No data available.'
- Remove '$' from column 'Name' --> the first rows are blank
- Scroll in filter table --> rows become non blank again

**Comment by afalenski** [comment]
Testfile: Scenario_3_All-Stations.json
Test Browser: Firefox Quantum 68.9.0esr (64-Bit)

Bug fixed for first test case.
Bug not fixed for second test case. Deleting '$', none of the data roww were visible. Please fix

**Comment by afalenski** [comment]
Done.
