### ISSUE TITLE
Allow Map AND Shape at the same time

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#480]
As a user working on an outbreak situation and wanting to display contamination sites as shapes on a map I would like to get the option to select a map (Black & White or Mapnik) AND a shape which is displayed on top of the map.

**Think of Tests**
- [x] Geojson containing a shape on a known position needed

**Comment by ruegenbfr** [comment]
##### Proposal:
The current menu 
<table>
<tr><td>Mapnik</td></tr>
<tr><td>Shape File</td></tr>
<tr><td>Load Shape File...</td></tr>
<table>
could become this
<table>
<tr><td>Mapnik</td></tr>
<tr><td>Shape File</td></tr>
<tr><td>Map & Shape File</td></tr>
<tr><td>Load Shape File...</td></tr>
<table>
Benefit:
This would allow the easy integration new tile servers.

**Comment by j-hha** [comment]
branch: story/480-shape-layered-on-map

**Comment by j-hha** [comment]
- [ ] layer shape on map
- [ ] remember map in case b&w map gets reactivated

**Comment by j-hha** [comment]
14.10.2024: Deployed on dev environment and ready to be tested.

**Comment by j-hha** [comment]
@j-hha note to self: follow up --> test?

**Comment by afalenski** [comment]
- After a shapefile has been loaded, the option "Map & Shape File" is available.
- The shape is displayed on top of the map.
- In the Graph Settings, the shape's border can be coloured and the line width can be adjusted.
- The shape is cached: Switching to "Mapnik" and back to "Map & Shape File" immediately displays the shape on the map again.
- Being in the "Map & Shape File" view and loading a different shapefile, the shape-only mode becomes active. 
Very cool!
Done.
