### ISSUE TITLE
Display funding sources for FCL Web

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#481]
As product owner I would like to acknowledge the funding bodies for FCL Web (budget funds of BfR, EFSA, EJP COHESIVE; in future also EJP NOVA, NRW):
- include on the **landing page** and on the **dashboard page** 
- on the bottom of the page with some space above footer
- centered
- Font as in footer (Roboto?), font size a bit bigger as in footer

**Text:** 
FCL Web received funding from the EFSA-BfR Framework Partnership Agreement (FPA) GP/EFSA/AMU/2016/01 as well as the European Union’s Horizon 2020 research and innovation programme under Grant Agreement No 773830 (One Health European Joint Programme, COHESIVE) and was supported by budget funds of the BfR. 

![Funding Source.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/049bf9fc-ed08-4561-b7c4-8c8b2c55a18e)

**Comment by ruegenbfr** [comment]
In agreement with PO text was changed to: "FCL Web received ..."

**Comment by bfrgottscma** [comment]
Line break adapts to size of the window, great.  Done.
