### ISSUE TITLE
Fix ui effect in filter table header

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/fcl-client#492]
Due to the update to Angular 10 the header of the filter table shows repeated sort icons that should be removed.

**Comment by afalenski** [comment]
The stations table was sorted by name or ToB, delivery table was sorted by product or lot. The sort icons were seen only once over each column. Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
