### ISSUE TITLE
Browser context menu hides app context menu

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#493]
When right-clicking on stations, the station context menu is hidden by the browser context menu (see screenshot)

**To Reproduce**
1. Right-click on station/delivery/in empty space
2. Browser context menu hides station/delivery/empty space menu

**Expected behavior**
Only station/delivery/empty space context menu should be visible, browser context menu should be disabled

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/ff698813-20d2-426c-b19a-4167618de83e)

**Desktop (please complete the following information):**
 - OS: error present on Windows, error not present on Linux + Mac
 - Browser: error present in Firefox, Chrome, Opera
 - Version: several versions

**Additional context**
Error only occurs on testserver, not on production server
Error is new --> related to Angular update?

**Comment by bfrgottscma** [comment]
Still appears sometimes. Especially when clicking several times with the right mouse button, then click somewhere else and then rightclick a station --> in the last step browser menu again overlays context menu of FCL (but not everytime)

**Comment by afalenski** [comment]
In addition to what Marion wrote: 
- When right-clicking into empty space always both the FCL context menu and the Firefox context menu appear.
- If nothing is selected the FCL context menu always appears without the Firefox context menu when right-clicking on a delivery.
- If the FCL context menu is displayed and the user decides to right-click somewhere else (on another delivery or on a station), then the firefox context menu is shown.
- The same is true for stations: If nothing is selected (left-click into empty space), only the FCL context menu appears when right-clicking on a station. In all other cases the Firefox context menu appears.

**Comment by bfrgottscma** [comment]
Desired behavior: when FCL contex menu is open and you right-click a second time, nothing should happen. You have to left-click somewhere to close FCL context menu before right-click becomes active again. As in productive version.

**Comment by ruegenbfr** [comment]
#### Solution in agreement with PO:
All default context menus in the web app are disabled 

##### Please note:
The behavior is different to the release version.
In the release version the default context menu is disabled only when the tracing view was visible once, but only partially.
A right click on a popup menu (selection box, or graph context menu) opens nethertheless the default context menu.

**Comment by afalenski** [comment]
Done.

Tested with:
    Win10, Firefox Quantum 68.9.0esr (64-Bit)
    Win10, Firefox 86.0 (64-Bit)
    Win10, Chrome 88.0.4324.190
    Win10, Opera 74.0.3911.203
    Win10: Edge 89.0.774.45
