### ISSUE TITLE
(Full/Forward)Trace is not working correctly

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#499]
Graph does not show neither the correct trace nor the observed status when activating flu/forward trace on a specific delivery.
Please note: This problem is also present in the release!!

Reproduce:
- Load example data
- Show context menu of 'Sugar' delivery (id: D30) from 'Hermann Sugar Refinery' to 'Jacob Hill Market Stall'
- Choose Full/Forward trace
- Nothing happens
- But: Show context menu of 'Sugar' delivery (id: D6) from 'Jacob Hill Market Stall' to 'Bakery Roth & Son'
- Choose Full trace
- delivery D30 is on backward trace

**Comment by ruegenbfr** [comment]
Completely done in dev.
Partially done in production (in agreement with PO): 
Example model was updated. So the loaded example model does not show this bug anymore. However, if somebody did download the old example and uploads it again this bug will show again.
The bug will be complete fixed in the next release.

**Comment by afalenski** [comment]
In FCL dev as well as in FCL productive the full trace is shown when activating full trace on delivery D30. Done.

**Comment by afalenski** [comment]
In FCL dev as well as in FCL productive the full trace is shown when activating full trace on delivery D30. Done
