### ISSUE TITLE
New highlighting dialogue: Enable to select no color

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#505]
As a user I would like to be able to only select a shape but not select a color for a station. 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Good. Done.

Tested with datasets

Baby Tea scenario Step 3 (810 stations, 4070 deliveries)
Tested in browsers

Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
Firefox Quantum 68.9.0esr (64-Bit)
Firefox 88.0.1 (64-Bit)
