### ISSUE TITLE
Name of highlighting condition mandatory

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#507]
Please make the name of the highlighting condition a mandatory field. Hence, you can only create a new highlighting if this information is given. Names can be non-unique if needed (e.g. when adding default highlighting rules).

Please add that the name is obligatory to the tooltip for Apply and OK.

DevNote: What if highlighting condition comes without a name from the desktop FCL?

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
1. Check whether highlighting name is mandatory and check mouseover texts
- Reload Web App (F5)
- Load sample data
- Open Highlighting menu
- Click +-Button, configure Shape = Square, colour = BfR colour, property; Name = Case 5
Buttons "Apply" and "OK" are greyed out; mouseover text gives hint to add name, shape/colour and condition
- Add "x" as Highlighting name
Buttons "Apply" and "OK" are white and blue; mouseover text changes

2. Check whether name remains mandatory if existing rule is edited
- see (1)
- click OK button
- click pencil (edit button) of the new rule
- delete "x"
Buttons "Apply" and "OK" are greyed out; mouseover text gives hint to add name, shape/colour and condition
Done.

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
