### ISSUE TITLE
Update data protection officer (dev + prod)

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#508]
Please update the data protection officer in the Data protection declaration AND in the Data protection notice on test AND production system.

The new officer is:
Janina Rochon
German Federal Institute for Risk Assessment (BfR)
PO Box 12 69 42
Tel +49 30 18412 31002
E-mail: dsb@bfr.bund.de

Data of the declaration does not need to be updated, hence the user does not need to consent again.

**Comment by afalenski** [comment]
In FCL dev as well as in FCL prod both the data protection declaration and the data protection notice now contain the present data protection officer. Done.
