### ISSUE TITLE
Filter table rows disappear / are not in sync with table columns

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#512]
The user wants to see rows in the table and column values which are aligned to/in sync with the column headers.

##### Reproduce:
Sync issue:
- load Example
- show station filter
- add some columns
- scroll table body to right
- change tab (e.g. to 'Deliveries')
- change back to tab 'Stations'
  --> column values are not aligned with column headers anymore

Disappearing row issue:
- load Example
- show station filter
- if table shows all rows, decrease window height such that only a subset of rows is visible
- scroll down (rows)
- change tab (e.g. to 'Deliveries')
- change back to tab 'Stations'
  --> some rows are invisible

**Comment by afalenski** [comment]
Bug fixed. Done

Tested with datasets
- Example data
- Baby Tea scenario Step 3 (810 stations, 4070 deliveries)

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
- Firefox 88.0.1 (64-Bit)
