### ISSUE TITLE
Augment meta stations with properties of its members

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#513]
Currently the user can specify a group name / or the group name is set by the web app, but no other properties are set e.g. Country, typeOfBusiness, ...

#### Proposed solution:
- apply consensus from members: e.g. only if all members are in DE, the metastation should become DE. If properties are differing among the members of a metastation, the respective property of the meta station should remain empty.

**Comment by bfrgottscma** [comment]
Done

Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
