### ISSUE TITLE
< or > operators in highlighting/filter conditions do not work properly on numbers 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#516]
The evaluation of filter/highlighting conditions does not work correctly on for **<** or **>** operators on properties of type number (with the exception of 'Score' or 'Weight').

Currently the lexicographical comparison is applied, but not a proper number comparison.

DevNote:
Reason: Properties of type number are converted internally to type string (with the exception of 'Score' or 'Weight');

**Comment by ruegenbfr** [comment]
If the **<** or **>** are used as operators, the web app tries to perform a number comparison (even if the input data is of type string).
Only if the the condition value or the property value cannot be converted to a number a lexicographical comparison is used.

**Comment by afalenski** [comment]
Creating rules with numbers as numbers is possible now. Tested with highlighting rule for longitutde / latitude (stations) and with example highlighting rule from FCL desktop.
Done.

Tested with datasets
- Baby Tea scenario Step 3 (810 stations, 4070 deliveries)
- example highlighting rule from FCL desktop

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
- Firefox 88.0.1 (64-Bit)
