### ISSUE TITLE
Making a merged station invisible leads to errors

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#518]
**To Reproduce**
- Load example data
- open filters menu
- merge Case 2, Case 3 and Case 5, name: 'X'
- make X invisible
- hover over invisible X: It can be seen in the graph
- click on the arrow next to X to see the merged stations
- hover over the merged stations and X starting from below the last station: It is not shown in the graph anymore
- right click in the graph, select Clear invisibility: X is shown in black font in the filter table, but it is not shown in the graph
- Load example data: The filter table is updated, but the graph stays the same. You need to press F5 / reload the FCL webpage to be able to reload the example data

**Expected behavior**
When making merged stations invisible, one should should be able to make them visible again.

**Desktop:**
 - OS: Win10
 - Browser [chrome]
 - Version [e.g. 89.0.4389.90]

**Comment by ruegenbfr** [comment]
The above observed behavior was a symptom not the cause. The error was raised by an insufficient setting of the active ghost station in the filter table.

**Comment by afalenski** [comment]
Invisible merged station is shown when hovering over its names or the contained merged stations in the filter table. Stations can be made visible again. Dataset is updated and fully loaded when clicking on load example data / when uploading the same dataset. Done.

Tested with datasets
- Example data
- Baby Tea scenario Step 1 (9 stations, 16 deliveries)

Tested in browsers
- Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
- Firefox 88.0.1 (64-Bit)
