### ISSUE TITLE
Fix import of node positions

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#523]
If the json was created by the desktop app tracing view, the meta node is not at the proper position in the web app.

##### Reproduce:
- open a non empty model in the desktop app tracing view
- if no meta station exists, create one
- export settings
- load exported json into web app
--> meta node position is not correct

##### Background:
The desktop app stores only non meta node absolute positions. 
The web app works internally with relative positions for all nodes (the position of group members is relative to its group center, the relative position of a non group member is equal to its absolute position).

Consider this aspect during import.

**Comment by afalenski** [comment]
The position of the metanode is correct. 
Also, the meta station name is correct, the station it contains are correctly displayed in the filter table (sub-stations of the meta station, in grey, invisible) and the meta station can be expanded in the Web App.

Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Scenario_3_All-Stations.json

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
