### ISSUE TITLE
Add draft and coming soon labels

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#524]
As a user I want to see directly which feature is coming soon and which feature is only in beta version since this is more transparent and explains why there might be some "buggyness"/incompleteness.

Please add labels as shown in the mockup.

![Draft and Coming soon label.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/e587441c-14b7-4785-85b2-0d87ffe89442)

**Comment by afalenski** [comment]
Draft label, mouseover text for anonymisation and 2x coming soon were added.
However, the red colour is not RGB 192, 0, 0 but 255, 0, 0.
Please fix.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by ruegenbfr** [comment]
Sorry, missed the color. Done.
