### ISSUE TITLE
Highlighting tab: Colors and shapes per default expanded when opened first

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#525]
As a user, I want to have the Colors and shapes dialogue (only feature in the Highlighting tab) expanded per default when first opening the highlighting tab. Afterwards, the last GUI status should be used.

**Comment by afalenski** [comment]
1. Check whether Highlighting Colours and Shapes is the first visible Highlighting dialogue:
- Reload FCL Web (F5)
- Load example data
- Click on Filter Menu
- Click on Highlighting
Colours and Shapes is the first visible dialogue. Labels and Station Size are closed

2. Check whether state is remembered:
- See (1)
- Click on "Labels"
Colours and Shapes remain also open
- Click on Filter
- Click on Highlighting
Labels as well as Colours and Shapes are open.

Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
