### ISSUE TITLE
Show number of stations affected by highlighting - implement functionality

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#527]
At the moment the number of stations affected by a specific highlighting rule is just a fake number in the highlighting list. Please implement functionality.
Numbers should be updated if number of affected stations are changed.

P/O note: If it costs too many story points, this will not be included in the upcoming release but in the release after. Then this column should be hidden.

___________________
If there is a highlighting rule which is not visible for some stations (because of another rule of higher rank = situated above in the highlighting rule list) this number of stations should be stated in brackets and in red font below the number of stations to which the rule generally applies (see mockup below).
- All numbers shall be horizontally centred (not like now right-aligned)
- The column must be so wide that 6 digits plus 2 brackets can be shown in one row (like "(999999)")
- If the highlighting rule is visible for all stations to which the rule applies, the number should be vertically centred as it is now (see "300" in the mockup)
- If the highlighting rule is not visible for some stations to which the rule applies, the red number in brackets should be directly below the black number. Both numbers should stay in line with the top and lower rim of the blue legend symbol.
- A mouseover message for the highlighting rules which are note completely visible has the following text: "For X/Y stations the shape is not visible due to another rule above this one." The wordwrap is between "visible" and "due" (see mockup). The mouseover text for rules without red numbers is: "This highlighting rule applies to X stations". The message box must be flexible so that both small and large numbers fit into it.

![Highlighting-Mockup_Number-of-stations-for-rule-not-active1.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/7c3ad3e0-0500-478d-bf6e-2f1316ae891f)

**Comment by afalenski** [comment]
Numbers

**Comment by afalenski** [comment]
1. Check numbers:
- Load Scenario_3_All-Stations.json
There are 4 primary producers, 3 processors, 5 distribution centres, 3 traders, 1 internet trader, 294 supermarkets, 500 internet consumers, 172 stations from The Netherlands, 155 stations from Belgium, 106 stations from Luxembourg, 193 stations from France, 181 stations from Germany and 3 stations from other countries
- Set full trace to stations "La source des herbes"
There is one observed stations and there are 8 stations on the backward trace and 801 stations on the forward trace.
All numbers are centred horizontally. A mouseover text appears when hovering over the number.

2. Check conflicting highlighting rule
- Add new rule: Name = Consumer 2, Shape = hexagon, no colour, Type of business = Consumer
- click Apply
Directly below the 500 for Consumer 2 a red 500 in red brackets appears with the above mentioned mouseover text with correct wordwrap. Both numbers are vertically in line with the Legend button.
- click OK
- drag the new rule above the rule "Consumer (via Internet)"
The red "(500)" jumps from the new rule to "Consumer (via Internet)"

3. Check whether there is enough space for 6 digits plus brackets:
- via Dev tools the 500 was set to 500000 for the red and the black number.
This number fits into the space and is centred.


4. Check whether numbers are updated
- select the 500 "Consumer 2"
- Make invisible
The numbers next to "Consumer 2" and "Consumer (via Internet)" become 0. Numbers are updated.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Scenario_3_All-Stations.json

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
