### ISSUE TITLE
To JSON node exports latitude and Web App does not understand

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#53]
When you attach a To JSON node to a Tracing View / Supply Chain Reader, the To JSON node leaves the column headers "GeocodingLatitude" and "GeocodingLongitude" as they are. However, the Web App in the browser does not understand this header and thus it does not show the geolocalisation of the stations. The Web App needs "lat" and "lon" as column headers. Either the To JSON node should rename both columns or the Web App should understand "GeocodingLatitude" and "GeocodingLongitude".

**Comment by ruegenbfr** [comment]
New JSON version integrated.
