### ISSUE TITLE
Performance: Changing column width takes 5s

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#532]
As a user who would like to adjust several column width in the filter table I would like to be able to do this without delay. Currently, I have to wait 5 seconds after changing one column width until I can change the width of another column. This is independent of the size of the dataset.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/532?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr
