### ISSUE TITLE
Refine operator != and ==  

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#543]
The user wants to use boolean values ('True', 'False') or numbers ('1', '0') in complex filter or highlighting condition with operators '!=' or '==' and properties of type boolean.

So,
'Cross Contamination' ==/!= '1' should be equivalent to 'Cross Contamination' ==/!= 'true' and
'Cross Contamination' ==/!= '0' should be equivalent to 'Cross Contamination' ==/!= 'false'

**Comment by afalenski** [comment]
Cross Contamination can be selected in the filter table via complex filter Cross Contamination == true or 1 as well as false or 0. 1 and 0 also work with "dead start", for example. It also works in the highlighting conditions.

It also works with Is Meta Station == true or 1 or != false or 0. However, when selecting for Is Meta Station == false or 0 or != true or 1, the number or stations remains the same as if not filtered.
@ruegenbfr Is there a reason for the different behaviour with Is Meta Station?

**Comment by ruegenbfr** [comment]
This is no bug but the consequence of having collapsed stations in the filter table.

The condition 'Is Meta Station' == false is not satisfied for a meta station, but for its members. But as long as a member satisfies the filter conditions the meta station itself is shown also.

**Comment by afalenski** [comment]
Done.
