### ISSUE TITLE
Inactivate "Selected" property in highlighting conditions

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#547]
As a user, I want my highlighting conditions to be consistent. Since a selection in the graph is not consistent, it makes no sense to use this variable to build highlighting conditions. Hence, this variable should not be offered as a property in the highlighting tab.

A function to use selections for highlighting conditions will be handled in a separate ticket.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Removes property 'Selected' **and** property 'Invisible' from highlighting conditions.

**Comment by afalenski** [comment]
"Selected" and "Invisible" cannot be selected in the Highlighting properties.

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset


Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
