### ISSUE TITLE
Round numbers to 3 digits

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#553]
As a user of the data table and the ROA report I would like to see only the first three digits after the comma (e.g. for amount and score) for those numbers which are defined as number (not string) and for columns known to contain only numbers. Please round. Currently, there are many digits after the comma, see screenshot.

Values are rounded for 3 digits if [(value is of type number) OR (value is of type string AND is on the positive list)] AND [rounded value does not become 0 although the non-rounded value is <> 0].

In the properties dialogue of stations and deliveries, the full number with alll digits (without rounding) is shown.

Examples:
"8.6666666" => "8.667" for listed property in positive list
10000.00555 => 10000.006
0.0005 => 0.001
0.3999 => 0.4
but:
0.00046666 => 0.000467 
In case of the last example (rounded 0 and non-rounded <> 0) the value is displayed so that behind the first non-zero digit at maximum 2 additional digits are displayed.

Example columns: 
- Internal columns which contain already numbers (score, weight...)
- Amount
- _lieferungen.delivery_amount
- product amount
- focus product amount

To make it transparent for the user that numbers are displayed in a rounded way, there should be a checkbox in the ROA Configuration dialogue: [] display rounded numbers (three digits) --> per default, the checkbox is active/ticked

![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/605c2308-3aa1-4624-8932-1534defd5c91)

Dataset: Scenario_1_Outbreak-Baby-Tea.json

**Comment by ruegenbfr** [comment]
Done for the roa report. 
In agreement with the PO: The rounding feature for the filter table be will a topic of another topic since it needs concept work.
