### ISSUE TITLE
ROA Report Configuration dialog presets are not reseted on loading a model

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#555]
The user wants to see identical presets in Roa Report Configuration dialog after loading a model.

Reproduce:
- Load distiller datatset, click on button ROA style, in Lot Box Label select column "ProductAmount" and click on Generate Report
- Click on Tracing View
- Upload Baby Tea dataset, click on button ROA style
The column "Product Amount" is selected and in the dropdown menu, although this column does not exist in the Baby tea JSON. There should be not traces of old data when uploading a new dataset.

**Comment by afalenski** [comment]
The column "Product Amount" was not visible anymore at the end of the above mentioned test. Done.

______
**Tested with**
OS: Windows 10

Datasets: 
- Scenario_1_Outbreak-Baby-Tea.json
- Distiller2FCL_Uploaded_FToF_AndDownloaded.json

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox 89.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
