### ISSUE TITLE
Labelling: Create component

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#557]
As a user I would like to see labelling of stations.

Please set up a component for labelling (without functionality, functionality will be dealt with in separate tickets). 

The component should include (see mockup):
- the name of the labeling rule
- the number of affected stations
- a button to switch on/off showing that label in the legend
- a slider to switch on/off the labelling rule
- a button to edit the labeling rule
- a button to delete the labelling rule
- a button to add new labels

![Labelling component.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/ea0fc9c4-eb52-4451-a3d9-91e3d5825dde)

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by ruegenbfr** [comment]
PO does not want anymore the legend symbol. (Label rules shall no be displayed in legend.)

**Comment by afalenski** [comment]
Labelling component is present, but without legend button.
Done.

**Comment by bfrgottscma** [comment]
Done
Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
