### ISSUE TITLE
Labelling: Add functionality to number of affected stations

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#559]
As a user I would like to see, how many stations are affected by a specific labelling rule (similar to #527 for highlighting list). 
Numbers should be updated if number of affected stations are changed.

- All numbers shall be horizontally and vertically centred
- The column must be so wide that 6 digits can be shown in one row (like "999999" 
- The mouseover text for rules is: "This labelling rule applies to X stations". The message box must be flexible so that both small and large numbers fit into it.

We do not need the red brackets since we do not have labelling conflicts (as in shape highlighting). If two labellings apply to the same station, they are listed after each other, separated by slash.

Ghosts/invisible stations are counted as well.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by ruegenbfr** [comment]
Labelling rules are applied on visible and invisible stations but non on member stations.

**Comment by afalenski** [comment]
- Label "Type of Business" added if ToB = "Bakery" -> 3 stations get extra label separated by slash.
- Mouseover text of number is good, but not as in ticket text. It says "This **highlighting** rule applies to 3 station(s)." Okay for me. @bfrgottscma Is this OK for you?

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
