### ISSUE TITLE
Make the complex filter faster

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#560]
If the complex filter has a lot conditions (e.g. 800) the web app becomes unresponsive. This problem is likely to occur in the highlighting edit dialog. (The service function "Add Selection" allows an auto creation of conditions)

Reproduce issue:
- load "Scenario_3_All-Stations.json"
- select all stations in the graph
- open station highlighting tab
- click "+" to open the edit dialog for a new rule
- click "Add Selection"
  --> the web app becomes unresponsive

Dev-Note:
First Guess: Change detection not set properly; if this does not help re-estimate ticket.
Perhaps too many styles on webpage for browser

**Comment by ruegenbfr** [comment]
ChangeDetection is properly set

proposed solution:
- use virtual scroll container
- eventually replace mat-form-fields (one mat-form-field comes more than 20 html elements

**Comment by afalenski** [comment]
The waiting time is reduced from minutes to half a second (Chrome) or just above one second (old Firefox) - fantastic! Well done!
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 3

Browsers:
- Firefox 91.13.0esr (64-Bit)
- Google Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)
