### ISSUE TITLE
Visibility of Apply/Cancel/OK buttons of filter condition list in highlighting edit dialog

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#561]
If a highlighting rule has a lot of conditions, the user has to scroll down to 'Apply', 'Ok' or to 'Cancel' the edit dialog. 

To solve this, the 'Apply', 'Ok' or to 'Cancel' should be "fixed" above the footer and "swimming" within the condition list. The top condition should never be covered by the buttons, the buttons should never be lower than directly below the last condition. In between, it is "swimming" through the list when scrolling (the buttons always change between a fixed and a moving state).

![grafik.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/003383c8-109d-4d93-b79c-2e4d2068e72f)

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/561?planning-poker) with ZenHub @afalenski @Fusiakja @GerberI @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
Done and not needed anymore since height of condition list was limited in ticket #560
