### ISSUE TITLE
Make document title consistent

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#563]
The user wants to see a consistent document title (the document title is shown as window name or tab name).
The web app starts with "FoodChain-Lab", but if an roa report is generated and the report is saved the document title is replaced by "< filename > - FoodChain-Lab" as e.g. "ROA_report_20210812.xml - FoodChain-Lab". The document title is not restored to "FoodChain-Lab" if the user switches back to the tracing view.

Proposed solution: 
Always use "FoodChain-Lab" as document title.

**Comment by afalenski** [comment]
- Load data
- Click on ROA Style and Generate Report
- Click on Tracing View and OK
The whole time the tab name stayed the same: "FoodChain-Lab".
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
Done
Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
