### ISSUE TITLE
Labelling: switch on/off specific labelling condition

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#564]
As a user I want to be able to easily (one click?) switch on/off specific labelling conditions.
E.g. hide names of stations while containing the content of this labelling condition to be able to switch on later. I do not want to repeat the labelling because in case of manually selected stations/deliveries this is very laborious and error prone.

Use slider to "activate" / "inactivate". Mouse-over text "activate" or "inactivate"

Mockup:
Slider: If labelling is set inactive: Font and "number affected" become grey, 

Only applies if we go for a legend button:
L-Button (legend) becomes white (as if inactivated). As soon as the slider is set active, the L-Button becomes blue again (active on legend).

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
- Labels can be activated and deactivated with one click on the slider.
- Mouseover text says "Deactivate Highlighting Rule" or "Activate Highlighting Rule".
- If labelling is set inactive: Font becomes grey, "number affected" becomes invisible. This differs from the ticket text. It is OK for me. @bfrgottscma Is this OK for you.
- There is no legend button, which is good.
Done for me.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
Making the "number affected" invisible whwn inactivating the rule is fine for me. It is consistent with the behaviour of the color/shape functionality.
We decided to leave away the legend button.

Done

Tested with Example Data

Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
