### ISSUE TITLE
Labelling: implement functionality of "delete labelling rule" button

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#565]
Please implement the functionality for "Delete labelling rule" button. When clicking the button, a dialogue appears that asks the user "Are you sure you want to delete the 'StationLabel' highlighting rule?" (yes, no). If yes, the whole labelling rule is deleted and removed from the list. If no, the dialogue is closed, nothing is deleted.

DevNote: Labelling rule needs ID in background --> use index?

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
- Dustbin is visible.
- Clicking the dustbin a small window pops up and asks whether you really want to delete the **highlighting** rule, not label. This is contrary to the ticket text. For me it is OK. @bfrgottscma Is this OK for you, too?
- The user can select as answer "Yes" and "Never ever". According to the ticket text, the latter should say "No". This is not OK for me. @bfrgottscma  What do you think about this?
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/044adff0-6fd3-41cc-951e-833d8dc8aab4)
- The labelling rule can be deleted.

**Comment by bfrgottscma** [comment]
Everything is fine for me except the "Never ever". It is a relict from the color/shape highlighting and not Marcos fault. @ruegenbfr  It would be great if you please could change the "Never ever" to "No" in the labelling section AND in the color/shape section?

If this is done, its also done for me.

Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))

**Comment by bfrgottscma** [comment]
@ruegenbfr I adapted my comment above with the specifications discussed in our meeting

**Comment by ruegenbfr** [comment]
Applies changes as requested.
Additionally the fcl fonts where set for all dialogs.
