### ISSUE TITLE
Labelling: Change existing labelling conditions

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#566]
As user, I would like to be able to change existing labelling conditions. When clicking the pen symbol in the condition list, the labelling rule dialogue opens below the respective condition. 
The labelling rule dialogue is the same as the dialogue for new labelling conditions, but filled with the respective settings. 

Add the following buttons: OK (save changes and close edit mode), Apply (save changes and leave edit mode open), Cancel (dont' save changes and close edit mode)

Pressing OK and Apply changes the graph and the legend

Mockup: see edit mode of highlighting conditions.
instead of checkboxes for use shape/use color, there is a checkbox "Use condition". If "Use condition" is not checked, the condition list below is inactive (greyed out). If it is checked, the condition list becomes active.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by afalenski** [comment]
- Existing labels can be changed when clicking the pen symbol.
- Buttons OK, Apply and Cancel are present and work as expected.
- Checkbox "Use condition" is there. If "Use condition" is not checked, the condition list below is inactive (greyed out). If it is checked, the condition list becomes active.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
Names, properties and conditions can be changed. It is applied to the graph.
Done
Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
