### ISSUE TITLE
change collapse/uncollapse symbol color for selected meta station rows in filter table

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#567]
The user wants to see the collapse/uncollapse symbol for filter table rows, which are show meta stations, in selected and unselected state. Selected rows which are representing visible meta stations have blue background and white text. But the collapse uncollapse symbol does not have a blue blackground, so its color should not change in selected rows.

**Comment by afalenski** [comment]
- Stations Case 2, 3 and 5 merged
- in the filter table the arrow was clicked to uncollapse merged stations
- another station was selected and then the metastation again
- the merged stations were collapsed in the filter table
- another station was selected
In all cases the "arrow" (like '>') which collapses/uncollapses merged stations was visible as black arrow with white background.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
Done
Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
