### ISSUE TITLE
Fix missing collapse symbol for metastations in filter table

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#568]
Metastations in filter table with members have an uncollapse symbol if they are collapsed and they should have an collapse symbol then they are collapsed.

If the user clicks on uncollapse symbol the metastation uncollapses and the collapse symbol disappears but no symbol appears for collapsing.

Add the collapsing symbol.

**Comment by afalenski** [comment]
Tested: Merge Cases 2, 3 and 5, click on arrow. Now, the arrow stays visible in the test and productive portal.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)

**Comment by bfrgottscma** [comment]
Done
Tested with Example Data on Windows 10
Firefox and Chrome
