### ISSUE TITLE
Highlighting: Station/delivery tab disappears when scrolling

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#570]
In the Highlighting tab, the Station/delivery subtab disappears when scrolling down

**To Reproduce**
1. Load example data
2. Open Highlighting tab
3. Uncollapse Labels, Station size, Color and shape dialogue until scroll bar becomes visible on the right side
4. Scroll down -> Tabs visible but subtabs disappear

**Expected behavior**
Respective tabs and subtabs should always be visible when the hamburger menu is open

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [91.0.1 (64-Bit)]

**Comment by afalenski** [comment]
The 'subtabs' (Stations, Deliveries) are now fixed and do not scroll down. They do not disappear.
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 92.0.4515.159 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
Done
Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))
