### ISSUE TITLE
Be able to quickly find a station or delivery

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#572]
As a user I would like to find a station or delivery very fast in a large supply chain network in the graph / on the map.

Double click on a station or delivery in the filter table. This selects the station / delivery AND the graph / map centers/focusses on the station or delivery (center of browser window).

Zoom stays the same as before.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/572?planning-poker) with ZenHub @ruegenbfr @MicheleK17 @bfrgottscma @GerberI

**Comment by ruegenbfr** [comment]
Solution is different from description above:

- The double clicked element is not centered in browser but in graph area (without sidebar).
- The zoom level might change for focus delivery operations. The focus feature tries to preserve the zoom level but if the edge is not shown (because the nodes are to close) or is to short or to big, the zoom level is increased or decreased if applicable.

**Comment by bfrgottscma** [comment]
Proposed solution (center in graph area) works fine. Adapting the zoom level only when deliveries are very short/long works fine as well. Station/delivery is not only centered but also displayed as selected after double click to facilitate visibility. Great! Done.

Tested in Windows 10, Chrome (Version 96.0.4664.45 (Offizieller Build) (64-Bit)) and Firefox (94.0.1 (64-Bit)).

**Comment by bfrgottscma** [comment]
Works now in map view. 
However, performance issues in map view in the filter table of deliveries when focussing one delivery and then subsequently another delivery. When switching back to station table and then again to delivery table (several times), it takes a while until the delivery table is loaded. Sometimes delivery table is not loaded at all. Not easy to reproduce.

Automatic switching between station and delivery table: focus station then focus delivery (do this several times), go back to station table, deselect by clicking into the empty space, double clicking on station -> station AND previous delivery is selected and automatic switching. console doesn't report on this. Not easy to reproduce.

Tested in Windows 10, Firefox 95.0 (64-Bit)

**Comment by afalenski** [comment]
I found the same bug. To reproduce:
- Login into Web App
- Load example data
- Open filter table
- Switch to GIS view
- Double-click on station "Case 2", switch to deliveries and double-click on "Strawberry Cake", switch to stations and double-click on "Case 4", then switch to deliveries and double-click on "Flour F1". 
If you do this as soon as you can see the content of the station / delivery table, you will now see a constant switching between both tables. If you wait 30 seconds after switching and double-clicking, this error could not be seen. Switching to the highlighting tab seemingly stopps the bug, but when you return to the filter tab the bug is still there. If you select the graph settings tab the constant change between tabs is also visible. Changing to graph view does not stop this erroneous behaviour. Only when you click on the FoodChain-Lab button in the top left the switching stops.

Browser:
- Firefox 95.0 (64 bit)
- 78.15.0esr (64-Bit)

**Comment by ruegenbfr** [comment]
The switching problem was not introduced by this feature it is also present in the productive version. (Reproduce: Simply click rapidly Delivery and Station Filter Tabs in alternating sequence and stop after 4 switches ==> auto switching).

In my eyes the switching behaviour is due to bad timing of the the tab selection event of mat-tab-group in firefox. See issue

**Comment by afalenski** [comment]
When re-testing the steps when the bug last described (see comment on 13.12.2021), the Firefox CPU usage rises from 4-5% to 30%. The bug does not appear anymore. Well done!

______
**Tested with**
Machine: SINA

OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Firefox Quantum 78.15.0esr (64-Bit)
