### ISSUE TITLE
Labelling of deliveries: Add new labelling rule

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#581]
As a user I would like to add new labelling rules.

When clicking the "+" button under the list of labelling rules, a dialogue opens (Mockup: as for already existing labelling rules but without any entries).

Mandatory:
    user enters name for rule (free text)
    user defines conditions (either manually or automatically via the "add selection" button).

Conditions dialogue:
    Property values and operations should be the same as used for the highlighting function.
    For the values, offer the values that are true for the respective property.
    For the Row menu allow and/or/remove. When remove is selected, the rule is deleted, or if it is the last remaining row, delete the values for this row.

Apply --> condition is applied
Cancel --> dialogue closed
OK --> condition is applied, dialogue closed

When labelling dialogue is open, clicking on another condition is blocked --> you have to click Apply/Cancel/OK before.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
Works as described. Tested in Firefox. Done.

**Comment by afalenski** [comment]
- + button works
- Name and property are mandatory, conditions not (which is good)
- property values are available and can be selected
- combining conditions via AND or OR is possible
- removing conditions is possible; last row stays but is emptied (good)
- Apply, cancel and OK work
- clicking on another label is blocked while editing a label definition
Done

______
**Tested with**
OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 93.0.4577.82 (Offizieller Build) (64-Bit)
