### ISSUE TITLE
ROA Style: Make landscape view the standard view

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#585]
As a user I would like to be able to print the ROA Style directly without having to take care of the orientation of the paper sheet. As most of the supply chains need in the ROA Style lots of space from left to right and only little space on the top to bottom axis, the default paper orientation should be landscape. Currently, the default orientation is portrait.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/585?planning-poker) with ZenHub @afalenski @Fusiakja @GerberI @MicheleK17 @ruegenbfr

**Comment by afalenski** [comment]
Clicking on File\Page setup the new default orientation is landscape. Unfortunately, the window is truncated on the right (Chrome and Firefox).
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/b458cb56-1d97-48ba-80fd-bcc106b89f5b)
In addition, in Firefox there is not enough space for the number of the grid size (the 0 of the 10 is truncated).
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a7c346dc-33ca-4a98-8759-b108e709046d)
Please fix.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
- Firefox 91.7.0 (64-Bit)

**Comment by birgitlewicki** [comment]
Create a new ticket for fixing the dialog size.
Done!
