### ISSUE TITLE
Fix symbol sort order in station filter table

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#586]
The user symbol sort order should should consider and prioritize the shape of the symbol and than the color.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/586?planning-poker) with ZenHub @afalenski @Fusiakja @GerberI @MicheleK17 @ruegenbfr
