### ISSUE TITLE
Fix sort behaviour of symbol column in station filter table

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#587]
The user wants the sort order to consider and prioritize the shape of the symbol. Currently only the color is considered.

See highlighting mockup, page 2: ""... sorts the table by shape AND colour (in this order)."

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/587?planning-poker) with ZenHub @afalenski @Fusiakja @GerberI @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
Done.

Tested in
