### ISSUE TITLE
Delivery Highlighting: Options, colour presets, button arrangement, sorting

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#590]
As a user I would like to edit the delivery highlighting options, create new ones and sort them.

- [ ] Name box "Colours... click to close" (without shape!)
- [ ] Make colour highlighting the default box which is open when clicking on the highlighting tab and then on the delivery tab.
- [already done: Set default highlighting: Copy colours from station highlighting for "Observed", "Forward Trace" and "Backward Trace".]
- [will become a ticket if needed: Keep in mind that there might be the options "Outbreak", "Cross Contamination", "Kill Contamination" and "Common Link" also for deliveries. This should be possible in the future.]
- [ ] Show colours next to the name, use arrow instead of dots (like the delivery arrow in the legend, see mockup below)
- [ ] Show number of deliveries which use the delivery highlighting.
- [ ] Button "Show in Legend" for all delivery highlightings
- [ ] Button "Activate/Deactivate Highlighting Rule"
- [ ] Button "Edit Highlighting Rule"
- [ ] Button "Delete Highlighting Rule"
- [ ] Grabber to sort delivery highlighting rules. Topmost rule is shown first in the legend and as first / leftmost colour in a multi-colour delivery arrow.
- [ ] Show plus button to add a highlighting rule. When creating a new highlighting rule, as soon as + button is clicked, the dialogue is opened and the + button disappears. As soon as apply/OK is clicked, the + button reappears.
- [ ] To add a highlighting rule the name has to be given, a colour and a condition (obligatory).
- [ ] Instead of a dot an arrow should be shown next to "Enter a name". The colour of the arrow is the same as the colour in the colour picker. Default colour is BfR blue (RGB 3, 78, 162). Write "Colour:" (British English).
- [ ] Add buttons "Add selection", "Remove selection", "property", "operator", "value", "+" (Add condition), "-" (Remove condition", "Apply", "Cancel", "OK". Arrangement: See mockup below.
- [ ] Add mouseover texts for all buttons (like in station highlighting)
- [ ] To add a highlighting rule the name has to be given, a colour and a condition (obligatory).
- [ ] When opening the "new highlighting" dialogue the buttons for apply/OK should be greyed out. They should only become active when the rule is complete (at least name given, a colour selected and one condition filled). For the greyed out buttons the user needs a tool tip ("Please enter name, select colour and define a condition.").

![Delivery Highlighting1.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/e701f700-fdc4-4f9f-b18f-3682d7fa63a7)

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/590?planning-poker) with ZenHub @bfrgottscma @Fusiakja @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
Graph refresh works fine now. Thank you for this great feature.

Tested with example dataset in Firefox (92.0.1 (64-Bit)) and Windows 10
