### ISSUE TITLE
Fix save  station color & shape rule

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#599]
The user cannot save a station color & shape rule without a color. 

##### Reproduce:
- Click 'Add rule' in station color & shape rules
- set name .e.g. to 'x'
- add arbitrary condition
- set a shape & uncheck 'Use color'
--> 'Apply' and 'Ok' button are enabled but don't work

**Comment by bfrgottscma** [comment]
I was able to set up a highlighting rule for shape only. Done.

Tested in Windows 10, Chrome (Version 96.0.4664.45 (Offizieller Build) (64-Bit)) and Firefox (94.0.1 (64-Bit)).
