### ISSUE TITLE
Bring selected deliveries to front

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#601]
As a user, I want to be able to see deliveries that are selected even if they are covered by several stations. Please bring the selected deliveries to the front (including the associated stations) while they are selected. If the deliveries are deselected, they (including the associated stations) should switch back to the background as before. 

If stations and deliveries are selected at the same time, selected stations should have the priority.

Priority rank:
Selected stations > selected deliveries (+ associated stations) > prioritised stations (outbreak, common link -> via score and connectivity of stations) > regular stations > regular deliveries

Include score as rank for deliveries. For joined deliveries use maximum score.

Should apply in graph and GIS view.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Fixed.
#### Please note: Solution is different from the proposal!
Deliveries are never shown in front of the stations (this restriction is imposed by the used graph framework).  
Apart from that all proposed priorities are considered now.

**Comment by bfrgottscma** [comment]
Done although it's a pity we have this constaint of the graph framework (Deliveries never shown in front of stations).
