### ISSUE TITLE
Focus station/delivery feature: Delete preexisting selection when double clicking

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#602]
Additional specification for ticket "Be able to quickly find a station or delivery" #572

When double clicking on a station or delivery in the filter table to focus the respective station/delivery in the graph, a potential preexisting selection of stations and/or deliveries should be deleted and only the station/delivery which is double clicked is in focus and selected.

Should work for graph and map view.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Works fine: All previously selected stations and deliveries are de-selected and the newly selected station or delivery is selected.

Tested:
- Selected station -> double click on delivery in filter menu
- Selected delivery -> double click on station in filter menu
- 1 Delivery and 1 station selected -> double click on delivery in filter menu
- 1 Delivery and 1 station selected -> double click on station in filter menu
- All stations and all deliveries selected -> double click on station in filter menu
- All stations and all deliveries selected -> double click on delivery in filter menu
Tested in graph and in GIS view (GIS view did not show a map)
Done
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Dataset

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
- Firefox 91.7.0 (64-Bit)
