### ISSUE TITLE
Fix endless tab switching in firefox

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#604]
If the user clicks rapidly and in alternating order the **Deliveries** and **Stations** tabs in tab **Filter** in configuration  side bar and stops clicking at some point, the tab switching continues endlessly.

See also ticket: #572

#### Reproduce:
- Login into Web App
- Open TracingView
- Load example data
- Switch to GIS view
- Open filter table
- click in fast succession on the tabs **Deliveries**, **Stations** (Repeat 4 times)
--> switching is endlessly going on

#### Further remarks:
Switching to the highlighting tab seemingly stopps the bug, but when you return to the filter tab the bug is still there. If you select the graph settings tab the constant change between tabs is also visible. Changing to graph view does not stop this erroneous behaviour. Only when you click on the FoodChain-Lab button in the top left the switching stops.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/604?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by ruegenbfr** [comment]
Reason: The **selectedTabChange**-event of the **mat-tab-group** in firefox comes for some reason to late. The user already clicked on tab **Stations**  but before the browser fires the **selectedTabChange**-event for the tab **Deliveries**.  This introduces a loop, because the late **selectedTabChange**-events comes back to the mat-tab-group and sets the **selectedIndex** (to **Deliveries**), now comes the late **selectedTabChange**-event from tab **Stations**.

**Comment by ruegenbfr** [comment]
Fixed.

**Comment by afalenski** [comment]
The switching reaction is still a little laggard, but the error is not visible. Done.
______
**Tested with**
Machine: SINA

OS: Windows 10

Datasets: 
- Example Dataset
- Scenario_3_All-Stations.json

Browsers:
- Firefox Quantum 78.15.0esr (64-Bit)
