### ISSUE TITLE
Reduce cpu consumption on filter table use

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#605]
The web app shows over 50% cpu use in firefox even then the user is doing nothing.

Reproduce: 
- load `Scenario_3_All-Stations.json``
- activate gis view
- open station filter tab, scroll down
- open delivery filter tab, scroll down

Watch cpu use of the web process by using e.g. task manager (start the monitoring before scrolling in the filter table). 
You find the correct process during scrolling because fast scrolling increases cpu consumption. 

After scrolling the cpu use goes to about 50+%, and does not decrease noteworthy.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/605?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by ruegenbfr** [comment]
Now the cpu goes down to 20+%.

**Comment by afalenski** [comment]
On SINA the Firefox CPU usage rises from 6-8% to 30-35% when scrolling. If it was 50% before, this is a great improvement! Done.

______
**Tested with**
Machine: SINA

OS: Windows 10

Datasets: 
- Example Dataset
- Scenario_3_All-Stations.json

Browsers:
- Firefox Quantum 78.15.0esr (64-Bit)
