### ISSUE TITLE
Move e2e tests to extra repo 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#615]
Currently the e2e test are located within fcl-client repo. Move them to a new repo.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/615?planning-poker) with ZenHub @GerberI @MicheleK17 @ruegenbfr
