### ISSUE TITLE
Create pipeline for nightly e2e tests

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#616]
Currently e2e tests do not run automatically on jenkins, they are only triggered by the developers on their local environments.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/616?planning-poker) with ZenHub @GerberI @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
Does not run on Jenkins yet. Decide if tests will be done on GitHub or on Jenkins.
