### ISSUE TITLE
Replace tslint with eslint on client

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#618]
Since angular 11 tslint is also deprecated for angular. It should be replaced with eslint.

Dev-Note:
There is a angular-eslint project with automated migration scripts. Since we have heavily adjusted tslint files it might be easier to remove tslint and then add eslint from scratch.
Also jest and prettier integration into eslint has to be applied.

https://github.com/angular-eslint/angular-eslint

First replace library and then adapt to our rules. If it takes too long, shorten tasks and continue on adaptation of rules later in separate ticket.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/618?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by afalenski** [comment]
I do not know what to test here. Usually tasks do not need to be tested.

**Comment by birgitlewicki** [comment]
I'll put it in Done and will report during next sprint meeting
