### ISSUE TITLE
Adjust border colour of geojson map

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#621]
As a user who has uploaded a NUTS3 geojson map (e.g. NUTS_RG_01M_2021_3857.geojson from https://ec.europa.eu/eurostat/de/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts) I would like to ~~increase opacity~~ change the colour of the map lines in order to see stations and deliveries more easily.

~~For Slider: See Mockup Alex (comment below). If this is not possible, a slider similar to zoom slider can be used which has a grey/black circle on top/at bottom~~

~~Please also add a checkbox to hide/show Opacity controls in Graph settings tab. This checkbox should be greyed out when no shapefile is used.~~

Edit 26.10.2022 after talk with developer:
- Display colour picker in Graph Settings
If no geojson is uploaded, the font colour is grey, the colour picker is empty and has no function:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/8d0f95af-e472-4826-a747-03e2481edd3f)
If a geojson is uploaded, the font colour is black and the colour picker is functional; default colour is black
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/d0c0d812-0a56-4aad-a1e4-40d6fa62f297)

- Add dropdown menu for border width
Function headline: "Geojson border width"
Width options in dropdown menu: Same as "Edge width" menu

- Add Mouseover texts for zoom controls:
+, - and zoom slider: "Zoom controls"
cross: "All stations on one screen"
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a6b80f03-e045-4e2c-ae85-bf875a1cba0d)

**Comment by bfrgottscma** [comment]
@afalenski : Do you have a solution in mind? If not, then my suggestion is to include it in the graph settings tab. Similar to the change in node size you have the possibility to change the opacity of the geojson. This setting should be greyed out when no shapefile is loaded.

**Comment by afalenski** [comment]
I have a dynamic appearance of the slider in mind: When a shapefile is shown, the slider appears next to the zoom controls (see below). The slider disappears when a map is shown or in the graph mode.

Mouseover texts:
- +, - and zoom slider: "Zoom controls"
- cross: "All stations on one screen"
- Opacity slider: "Geojson border opacity"

![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/e632b56b-0035-4d9e-8b8c-07ac9dfabf42)

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/621?planning-poker) with ZenHub @bfrgottscma @GerberI @MicheleK17 @ruegenbfr

**Comment by bfrgottscma** [comment]
- GeoJSON border color and border width dialogue appears in Graph settings when shape file is loaded
- Both dialogues are functional
- Both dialogues disappear when you switch back to graph view + reappear with currents settings when activating shape file view
- when a different shapefile is loaded, the current settings of the dialogue are still set
- when a different dataset is loaded, the shape file with the border color/width settings is still present
Done.

--------
Tested in Firefox and Chrome

**Comment by afalenski** [comment]
Settings and graph view are not in sync when loading a new dataset.

**Comment by ruegenbfr** [comment]
Shape file configuration is not anymore resetted on model load.
Shape file configuration is now resetted on shape file load.

**Comment by afalenski** [comment]
- Settings and graph view ar now in sync when loading a new dataset.
- Shape file and border colour stay the same when loading a new dataset so that reloading the shapefile is not necessary.
- The user can switch between map and shapefile without having to load the shapefile again.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 115.4.0esr (64-Bit)
- Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit)
