### ISSUE TITLE
GIS view: Black&White does not work anymore

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#622]
When selecting the Black&White GIS view, the following bug occurs:

![grafik.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/21a666f7-a207-4ee9-b37e-e22a4e33f910)

**Comment by afalenski** [comment]
Yes, it is the same in the desktop version. Perhaps the web address has changed.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/622?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr

**Comment by ruegenbfr** [comment]
The tile server is out of service, as explained [here](https://phabricator.wikimedia.org/T187601) (Read comment of **TheDJ** from Jan 22th 2022).

**Comment by ruegenbfr** [comment]
Solution: Remove the black & white option.

**Comment by afalenski** [comment]
Option Black&White is not visible anymore (good!)
BUT: Mapnik does not work: There is no map at all. Please fix.

**Comment by afalenski** [comment]
- Mapnik is back, shapefile upload works.
- Uploading a shapefile with example dataset open and changing the dataset to BabyTea: The shapefile is still active - great!
- Stations outside the shapes (station in Egypt in BabyTea sample when using shapes of Europe) are displayed - good!
- Changing between Mapnik and shapefile works fine.
- Uploading a 60 MB shapefile from BfR computer is fast (3.5s in Firefox and Chrome).
Done
______
**Tested with**
Machine: SINA

OS: Windows 10

Datasets: 
- Example Dataset
- Scenario_1_Outbreak-Baby-Tea.json
- TEST not functional Polygon_DE_EPSG3043.geojson
- TEST Polygon_DE_EPSG3857.geojson
- NUTS_RG_01M_2021_3857.geojson

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
- Firefox 91.7.0 (64-Bit)
