### ISSUE TITLE
Create Visio-Layout-Engine

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#64]
Convert the internal foodchain network to a visio like graph, according to the mockups attached mockups and the following rules:

[FCL-Viso_Graph_Mockup_2.pdf](https://github.com/SiLeBAT/fcl-client/files/2667564/FCL-Viso_Graph_Mockup_2.pdf)

Information:

There are 6 kind of non edge objects
- pseudo-country: a container box of companies; 
- company: a container box of samples | products | lots;  an element of an pseudo-country
- product: a container of lots; an element of a company
- lot: a container of samples; an element of company Or product
- sample: a box object representing
- delivery boxes

none edge objects:
delivery: directed edge from source lot to target lot / target company (if no target lot is available)

Layout Rules:
- elements are not allowed to overlap with elements which they do not logically contain (e.g. companies may not overlap with over companies) 
- company shall be positioned on levels according to their hierarchy in the supply chain network
- edges are (directed) polygonal chains, which line segments have to be either horizontal or vertical
- company ingoings (deliveries) which come from other companies have to pass the top border of the company 
- company outgoings (deliveries) which go to other companies have to pass the bottom border of the company 
- intra company deliveries are not allowed to pass the company box boundary

**Comment by GerberI** [comment]
done and partly overcome
