### ISSUE TITLE
Create Wiki for FCL Web: Research ticket

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#651]
As a user I would like to know more on FCL Web. Please create Wiki pages for FCL Web similar as for the Mibi Portal
- Application configuration
- Browser requirements?
- Deployment of FCL Web
- Developer Setup
- Git workflow
- Release workflow
- Review workflow for GerritHub ZenHub
- Scrum
- Server-side logging
- System prerequisites
- Test portfolio

Check if all point of this list are needed and if some points direct to shared wiki.
Then, separate tickets for the single wiki parts will be created.
In fcl-client wiki, there should be a link to fcl-resources wiki.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/651?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
- Application configuration
  Apply structure & adapt content of mibi
- Browser requirements?
  Apply content?
- Deployment of FCL Web
  Adapt structure & content of mibi
- Developer Setup
  Adapt structure & content of mibi
- Git workflow
  Link to devWikiEntry, but devWiki uses mibi as example but it should be repo agnostic
- Release workflow
  Link to devWikiEntry
- Review workflow for GerritHub ZenHub
  Obsolete
- Review workflow for github
  Link to devWiki (Entry does not exist yet)
- Scrum
  Link to devWiki? (Entry needs update), conflict: fcl scrum and mibi scrum are different on the detail level
  Proposition: Link to devWiki and fcl specific info
- Server-side logging
  Link to devWiki
- System prerequisites
  Adapt structure & content of mibi
- Test portfolio
  Link to devWiki and fcl specific info
