### ISSUE TITLE
ROA style: Fix truncated Page setup dialogue

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#652]
Clicking on File\Page setup in the ROA style the new default orientation is landscape. Unfortunately, the window is truncated on the right (Chrome and Firefox).
![b458cb56-1d97-48ba-80fd-bcc106b89f5b_chrome.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/f1ff3a50-c916-49a9-9fc0-6b4a287d32d5)

In addition, in Firefox there is not enough space for the number of the grid size (the 0 of the 10 is truncated).
![a7c346dc-33ca-4a98-8759-b108e709046d_firefox.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/c75da956-f3d5-46de-a3fe-4678a1c7a5b2)

Please fix.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/652?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Fixed issues:
- dialog sizes
- Edit data... dialog restructured (Menu Edit --> Edit Data ...)
- texts on the right sidebar are not cut anymore
- size of font style buttons and selection boxes increased (Select an connector on the graph, open 'Style' or 'Text' tab on right side bar)
- dialog closing icon (x) removed

**Comment by bfrgottscma** [comment]
Tested in Chrome and Firefox. Page setup dialogue not cut anymore and additional changes improved the right side bar a lot. Thank you very much! Done.

Issue with selection fields running out of the sidebar into the graph (right sidebar) when decreasing window size will be handled in a separate ticket.
