### ISSUE TITLE
Implement static symbol for graph loading times

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#653]
As a user I would like to get visual feedback if 
- loading of the dataset/graph

Please include a static symbol in the graph and the map view (loading icon and below "Loading... Please wait.". 

Please include transparency to hide the background as in MibiPortal.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/653?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by j-hha** [comment]
@ruegenbfr --> potentially also something we should consider when researching offscreen canvas

**Comment by bfrgottscma** [comment]
As a dynamic symbol is difficult to implement due to Cytoscape, we changed the ticket scope to implementing a static symbol.

**Comment by bfrgottscma** [comment]
Works fine in graph and GIS view when loading or switching between datasets. Good work. Done

Tested in Windows (Firefox 115.15.0esr (64-Bit) and Chrome Version 128.0.6613.138 (Offizieller Build) (64-Bit)).
