### ISSUE TITLE
Adapt station properties to new list of VIP variables

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#658]
Please change the VIP variables in the station property dialogue according to the new list as described in ticket #420. 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Comment by afalenski** [comment]
- The VIP column name for the station name is missing. Please add.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 91.10.0esr (64-Bit)
