### ISSUE TITLE
Prevent unnecessary appearance of save dialogue

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#668]
As a user who has loaded an example dataset/own data and who has not changed anything and wants to load another example dataset/own dataset, I do not want to be asked whether I want to save the dataset.

Example: 
- Login into FCL web
- Load example dataset "Example Data"
- Load example dataset "Babytea Scenario 1"
The "Save" dialogue appears.

It was agreed to solve this via comparing the initially loaded dataset with the status of the same dataset when loading a different example dataset/own dataset is triggered. It is enough to make a diff for the settings section of the dataset.

Note: Check how selecting a station/delivery affects the settings.
Note: If dataset from FCL Desktop is loaded, additional default settings are set but the user does not notice it. The diff should be made with the dataset after the default settings are added. This should be compared with the current status of the dataset.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/668?planning-poker) with Zenhub @bfrgottscma @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Roa report cannot be opened anymore. Please fix.

DevNote:
toolbar-action.component-template references function that was removed in the commit

**Comment by afalenski** [comment]
FCL Desktop dataset

**Save dialogue is activated**
- Selecting a station or delivery
- Selecting a station or delivery -> select an example dataset -> Cancel -> select an example dataset
- [ ] Graph settings: Merge deliveries; toggle "show merged deliveries counts" without changing "merge deliveries"; toggle "show legend"
- Highlighting: Toggle "Outbreak" off; delete highlighting rule "Outbreak"; edit rule (change colour); toggle "Do not show in legend"

**Save dialogue is not activated**
- Selecting a new example dataset / uploading a dataset without previous interaction with the currently loaded data
- Zooming
- Going to the profile page or welcome page and back to the tracing view
- Switching from Graph to GIS
- Saving an image
- Clicking on ROA report and going back to the tracing view
- Displaying the menu
- Directly after using the option "Download data"; it does not matter whether the user saves or aborts saving.
- Filtering in the menu
- [ ] Graph settings: Change node or text size; edit cross contamination tracing settings; toggle "show zoom controls"
- Highlighting: Click on edit rule without changing anything

**Comment by bfrgottscma** [comment]
@afalenski Thank you for testing.
Save dialogue is activated, if "show merged deliveries counts" is toggled without changing "merge deliveries" (graph settings) _-> behaviour is fine_

Save dialogue is not activated when node or text size are changed or when cross contamination tracing settings are changed (graph settings) _-> save dialogue should be activated -> to deal with in a separate ticket_

**Comment by bfrgottscma** [comment]
Done
