### ISSUE TITLE
Rename "Forward trace" to "On Forward Trace"

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#670]
As a user I would like the naming of columns and context menus to be consistent.

Rename "Forward Trace" to "On Forward Trace" and "Backward Trace" to "On Backward Trace" in default highlighting (stations and deliveries)

Should also the occurrences in the submenu of graph/map context menu "Set Trace" of stations and deliveries be renamed?

**Comment by bfrgottscma** [comment]
Obsolete > Closed
