### ISSUE TITLE
Replace fonts download from external systems 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#675]
Make the fonts from external systems available on web app host.

Steps to do:

- identify required fonts
- download fonts and add them to assets folder
- add google-fonts.css
- remove font links to exterrnal sources 

for fonts download see: [Web-Font-Helper](https://google-webfonts-helper.herokuapp.com/fonts)

Solutions for angular material icons:
- Quick solution with npm package: https://github.com/SiLeBAT/mibi-portal-client/commit/1ff97bca19bcc27c020d1585ccedbdab2b110023
- Manual solution: https://developers.google.com/fonts/docs/material_icons?hl=en#setup_method_2_self_hosting

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/675?planning-poker) with Zenhub @afalenski @GerberI @ruegenbfr
