### ISSUE TITLE
Highlighting: Columns can be selected but have no value

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#676]
As a user I want the columns which I can select in the definition of a highlighting rule to have a value. If I select "Source" there is no autotext in the value and the JSON file contains a null instead of "Source". Please check all delivery and station columns which can be selected in the highlighting menu, there might be more properties which have no function.

**To Reproduce**
- Load "Example Data" dataset
- Open menu and click on Deliveries
- Create a new highlighting rule: Click on "+", Name = "xyz", property = source, op = "==", click into the value field
There is no autotext, no suggestions (in contrast to property = "product" where a click into the value field offers many products to select).
- Keep the blue colour and enter "Groceries Storehouse" as value; click OK.
The delivery arrow "Cherries" should become blue now but it does not. (It works, if you use Source ID and value = "S642")
- Export the JSON file, open it and search for "xyz".
In the JSON file it says `"labelProperty":null,"valueCondition":null`
When re-importing the saved JSON file there is an error:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/38eff0cb-d391-4c13-9cc6-21555e5663e7)

Solution: 
- delete Source and Target properties (from highlighting property list only)

**Comment by ruegenbfr** [comment]
Columns were removed from selection.

**Comment by afalenski** [comment]
- Columns are removed. Thus, the error is not reproducible anymore.
- Downloading data and reloading this dataset is successful.
Done.
