### ISSUE TITLE
Fix password recovery on Dev

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#679]
When starting the process for password recovery, the link in the email the user receives is not functional - neither via clicking the link in the email nor via copying it to the browser. Also the link is different from the usual links (first part is missing). Please check (e.g. config file) and fix.

Only affects FCL Dev. FCL Prod and Mibi is not affected.
Registration fails, too.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/679?planning-poker) with Zenhub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Solution: The deployment pipeline had to be fixed.
