### ISSUE TITLE
Loading of example/own data set: Change save process to two-step approach

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#680]
When loading a new example data file or an own data file, the current data will be discarded to prevent performance issues.
A message box was implemented which informs the user that data are discarded and which asks the user if he/she would like to save the data.

Please change the save process to a two-step approach:

"Do you want to save the changes you made to "[FileName]"? Your changes will be lost, if you do not save them"
 Two buttons should be available in the dialogue:
    Don't save and proceed (close message box and load new dataset without saving)
    Cancel (close message box, stay in old dataset) --> this button should be active by default

Hence, if you want to save the dataset, you have to click Cancel and then trigger the Download Data process.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/680?planning-poker) with Zenhub @afalenski @GerberI @ruegenbfr

**Comment by afalenski** [comment]
- The new save dialogue appears.
- Cancel is highlighted by default
- [ ] Contrary to the ticket text, the filename is not in quotation marks and the filetype (which is part of the filename) is not shown.
@bfrgottscma Do you agree? Should quotation marks and filetype be displayed?

**Comment by bfrgottscma** [comment]
@birgitlewicki: Please add the quotation marks. Filetype doesn't need to be displayed.

**Comment by bfrgottscma** [comment]
Done. Thank you.
