### ISSUE TITLE
Fix Highlighting Condition Property Selector and Value Field

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#697]
The property selector in a highlighting rule condition does not show the selected property when the data is not supplied in the loaded model. Furthermore the Condition Value Field does not appear correctly, only its content.

Reproduce:
- download the attached file 
- rename file suffix to json
- load the model (it contains a highlighting condition that refers to some property `xyz' which is not supplied in the data part in the model)
- open station highlighting 
- click on edit on the listed rule
--> the property selector does not show any selection, and the value field isn't visible anymore

[Attached model](https://app.zenhub.com/files/61294409/6b11b91b-4ac9-42ae-8913-2d41c577b24b/download)

**Comment by bfrgottscma** [comment]
Tested in Chrome and Firefox. Bug does mot appear anymore. Done.
