### ISSUE TITLE
Fix property import of highlighting conditions

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#698]
The user should be able to load/download a model which references in a highlighting condition a property which is not supplied with the station/delivery data. 

DevNote:
- extend import mapping 

Reproduce:
- load model from
- download model
- reload downloaded model
--> error 'File could  not be loaded'

**Comment by afalenski** [comment]
Ärleeedicht. Bug does not exist anymore. Obsolete
