### ISSUE TITLE
Fix complex-row-filter-provider

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#699]
The user should be able to get value proposals in complex filter,  even without a selected operator.

Reproduce (with chrome):
- open developer tools
- load example model
- open complex filter for station table
- choose property in condition property selector
- click on condition value field
- type something
--> error shown in console

**Comment by ruegenbfr** [comment]
Proposal works fine now.

**Comment by afalenski** [comment]
The error is not visible.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Linux

Browsers:
- Chrome Version 106.0.5249.91 (Offizieller Build) (64-Bit)
