### ISSUE TITLE
Fix escape handling on sidebar

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#704]
If the user has a selection list open on the sidebar and presses 'Esc', the sidebar closes, but the selection list is still open and the sidebar is closed. If the user selects in this situation an entry from the presented selection list, the content of the still closed sidebar is suddenly displayed partially on the graph container.

#### Reproduce:
Issue 1:
- load some example model
- open sidebar
- open complex filter
- click on property selector 
- press 'Esc' ==> Sidebar closes, but selection list is still visible

Issue 2:
- click on some entry on the still visible selection list from issue 1 ==> sidebar content is partially displayed on graph container

Dev-Note: Disable escape button

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/704?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Closing of sidebar on `Esc` key press was disabled.

**Comment by afalenski** [comment]
- When clicking Esc while the property selector is open, it closes, but the filter does not close. The same is for the operator list and for the value suggestion list.
- Also when clicking with the left mouse button onto a station in the graph while the property selector is open, it closes. With the second left click the station can be selected.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data

Browsers:
- Firefox 91.13.0esr (64-Bit)
