### ISSUE TITLE
Scroll positions get lost on sidebar tabs

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#705]
The user wants to switch between sidebar tabs without loosing the scroll positions.

#### Reproduce:
- load Baby tea Scenario 3
- open Station highlighting tab
- resize browser window until the sidebar shows a scroll bar
- scroll down
- click on some other sidebar tab
- go back to Station highlighting tab ==> scroll position is lost

The scroll position gets lost for all scrollable components within a tab, with the single exception of the filter table.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/705?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Scrolling is restored now (or never gets lost).

**Comment by bfrgottscma** [comment]
Scroll positions remain active despite switching between the tabs. Done.

Tested in Firefox and Chrome.
