### ISSUE TITLE
Scroll highlighting edit rule into view

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#707]
The user wants to see the new edit rule, without scrolling down first.

**Comment by ruegenbfr** [comment]
Scrolls editRule into view, if a new rule is opened or an old rule is opened.

Please note: The angular version was previously changed from 11 to 13.

**Comment by afalenski** [comment]
- When you add a highlighting rule, the whole adding dialogue is shown in full without having to scroll. Great!
- When you add 1-5 property rules, you have to scroll down during configuration. This is not optimal, but shall stay like this for now.
- Adding the sixth rule, a scrollbar appears and the whole dialogue is shown in full for the whole time. Good!
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Babytea Scenario 3
Browsers:
- Firefox 91.13.0esr (64-Bit)
- Google Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)
