### ISSUE TITLE
fix upload model

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#709]
If the user tries to upload a model and the model is invalid, an error message is shown to the user but the model that was loaded before disappears.
Solution: Keep model if an upload model process fails.

##### Reporoduce:
- load example data
- load an invalid model (e.g. use attachment, but rename suffix to json before)
 --> error toaster is shown but previously loaded data disappears

Attachment: [Invalid model](https://app.zenhub.com/files/61294409/00d256aa-e0c3-4b8f-b56f-a2e50f8f1e0f/download)

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/709?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by afalenski** [comment]
- Example data stays visible.
- Warning is shown in red and stays until a left click is done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data

Browsers:
- Firefox 91.13.0esr (64-Bit)
- Google Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)
