### ISSUE TITLE
Offer two report options - create dialog

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/fcl-client#71]
As a portal user I want to be able to choose between two different visio report options:
1. public
2. confidential
These options could be offered via a configuration dialogue which appears after pressing the "create visio layout" button. 

DevNote: "Radio Buttons", Approve with "OK" -> this should open the graph editor with the visio graph displayed

**Comment by draaw** [comment]
There is a scrollbar visible right next to the radio buttons, it should not be there
