### ISSUE TITLE
Minify Json files in asset folder on build

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#712]
The web app contains example files  in json format. These files are minified in the code base. 

But the minified form makes the changes difficult to track, because the visualization of the changes is usually line oriented. 

Proposed solution (check feasibility):
Use a non minified json in the code base and minify in the build step.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/712?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
Done!
