### ISSUE TITLE
Kill contamination has no colour and is not shown in legend

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#720]
Describe the bug
When activating 'kill contamination', the station is not coloured in grey and the legend does not show that there is a station for which kill contamination is activated

To Reproduce
Open Babytea dataset or upload an own dataset. Set "Kill contamination" for a station.

Expected behavior
The legend shows a new entry 'Kill contamination' next to a grey dot. The respective station in the network should become grey.

CAVE: Kill contamination works for the first Example data set. Bug already appeared two years ago (#477) and was fixed for the Example data set.

**Comment by ruegenbfr** [comment]
The kill contamination highlighting rule was missing in the scenario examples. 

> The bug already appeared 2 years ago

The rule was missing also in the example data set. But at this point in time no example scenarios did exist in the web app.

**Comment by afalenski** [comment]
"Kill contamination" works for the "Example Data" dataset, "Seafood" and "Babytea Scenario 1". The station is coloured in grey. If there is already a colour, the grey colour is added. "Kill contamination" and its colour are shown in the legend.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1
- Seafood

Browsers:
- Firefox 102.12.0esr (64-Bit)
- Google Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)
