### ISSUE TITLE
Fix divider length

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#726]
The divider below the headline of the login, registration, ...  dialog was as wide as the dialog before the angular 14 update. Now it is as wide as the dialog headline.

Please restore the width.

DevNote: The mat-divider styling has changed with angular 14.

**Comment by ruegenbfr** [comment]
Fixed. This artefact was present in all authentification related forms.

**Comment by afalenski** [comment]
Line width fixed.
Done

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10


Browsers:
- Firefox 102.12.0esr (64-Bit)
- Google Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)
