### ISSUE TITLE
Fix account options menu styling

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#727]
If an authentificated user opens the "Show account options" menu, the menu heading text 
`fcl user`
`user-x@company-y.de`
and the menu heading avatar icon are overlapping.

Please remove the overlap.

**Comment by ruegenbfr** [comment]
Please check account options menu style.

**Comment by afalenski** [comment]
Avatar head and text are not overlapping anymore. However, the gap between avatar head and user name / email is narrower than in the profile and logout row. The gap should have the same width in every row. @bfrgottscma What do you think?

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 102.12.0esr (64-Bit)
- Google Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)

**Comment by bfrgottscma** [comment]
As it is only the menu header, I am fine with the smaller gap. Moreover, it saves some space since email addresses might be relatively long. Done.
