### ISSUE TITLE
Condition list missing for station/delivery highlighting

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#729]
When opening the highlighting tab for **stations** or **deliveries**, it is not possible to enter conditions for **labelling** or **color/shape highlighting**. 
![grafik.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/dfe74ca5-bb0f-4aa3-b902-a98e965540a2)

Also, when using the "Add selection" functionality, no (visible) ID list is generated - neither in "create new" nor in "edit" mode. However, the list seems to be generated in the background as it is possible to create a new labelling/highlighting rule via the "Add selection" functionality.

![grafik.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/1a7a4739-915c-4adb-aa6e-f8298ec4583b)

This bug is only present in the test version but not in the productive version.

This bug is most likely connected to the bug for complex filters as described in #728

**Comment by afalenski** [comment]
Adding conditions and adding selected stations via button "Add selection" is possible again.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data

Browsers:
- Firefox 102.12.0esr (64-Bit)
- Google Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)
