### ISSUE TITLE
Anonymisation preset

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#730]
As a user I would like to have an easy method to anonymise data in the graph.

- Delete the button with the key at the top of the highlighting options (both in Station and Delivery)
- Position the button with the blue key in the label section between the on/off slider and the edit pen in the row StationLabel (station tab) and next to the row DeliveryLabel (deliveries tab). Only show the key button in these two rows, never in any added label row.
- Add the option "Free Text" at the bottom of all options in "Set property for Label" (see image 1). Anything which is written in "Enter a name" will be displayed as label (see name in image 1, see "Station 001" in the graph in image 2). Free text shall always be displayed with quotation marks in the list of labels but without quotation marks in the graph (see image 2).
- Show an anonymisation preset if the button with the blue key is clicked. The blue key turns red and a red frame appears showing the preset labels. All can be edited via the pen button. They cannot be deleted, but can be switched on and off via the slider. The order of appearance can be changed within the red frame. 

**Station**
- Four preset labels "Station", Country, Type of Business and Index. 
- If values for country and type of business exist, they are shown just like normal labels, separated by a slash. In this case, the free text "Station" is not shown. If this combination of county and ToB only exists once, no index is displayed (see "DE / Local Market Trader" in image 2). If there are more than one stations with the same combination of country and ToB, an index is added with an empty space (no slash; see "DE / Primary producer 001" in image 2). If no ToB is known for a station or both country and ToB are missing, show the free text and the index (see "Station 001" in image 2). If a country is known, this would be "Station DE 001".
- When the key is red and the labels from the anonymisation preset are activated, still additional labels can be added.

**Delivery**
- One preset label "lot"; if there are product categories available later, the labels "Free Text" (e.g. "Product"), Index and Product Category would make sense.

Image 1: Free Text option
![fcl-c730_Anonymisation preset_Free Text.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/bb6d7350-37e3-4c4e-b65e-492ee4675496)
Image 2: Anonymisation preset
![fcl-c730_Anonymisation preset_Station.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/f91e9cf7-b155-4541-8bca-ecebe99d1c32)

To be discussed:
**Easier realisation:** 
- No key button is added
- The four labels Free Text, Country, Type of Business and Index are preset and deactivated by default. They are normal labels. 
- Anonymisation would mean, that the user deactivates the "StationLabel" and activates the other preset labels one by one.
- Index is added to all stations if activated. 
- A regex rule for Free text is defined (if ToB is null, add free text). This way the user can have a look at this label definition and be inspired to think about own labels defined by regex rules.

Image 3: Pre-defined labels to be used as anonymisation
![fcl-c730_Anonymisation preset_Station2.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a3b9cd64-9abe-4295-829b-d18bfce81f34)

**Comment by afalenski** [comment]
Will be done in a different way. To keep these ideas, this ticket is now being sent into the icebox until.

**Comment by bfrgottscma** [comment]
outdated because anonymisation is realized in #731. Closed
