### ISSUE TITLE
Anonymisation option

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#731]
As a user who would like to publish an image from a FCL web graph in a report I would like to anonymise the stations via a quick and simple option.

- Only for station names
- Delete the anonymisation button with the blue key in the highlighting stations tab.
- An "Anonymisation Label" is added to the label list. It is deactivated by default. It cannot be deleted, but the activation slider and the edit pen can be used.

![fcl-c730_Anonymisation preset_Station6.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/7d8b0a53-da5e-4e38-b8cc-df1157535d44)

- If the anonymisation label is activated, all other station labels are automatically deactivated.
- If the anonymisation label is deactivated, those station labels which were not active before activating the anonymisation label stay deactivated. All other station labels become activated again.
__________________
- If the anonymisation label edit button is clicked, a special label configuration dialogue opens with the options prefix and property. 
- The default anonymisation label contains the following configuration:
-- Prefix = "Station " (ending with empty space), Name = "Country", property = "Country"
-- Prefix = " / ", Name = ToB, property = "Type of Business

- As many rows can be added as the user wishes, using the +button (meaning as many as there are properties). 
- All rows can be sorted with the 6dot handles.
- Always in the last row there is an additional option "Index", enabling the user to differentiate stations, e.g. if there are many stations to which the label "Station DE / Primary producer" would apply. 
-- If index is activated by selecting "Use index" from the dropdown menu (default: "Use index"; other option: "Do not use"), add a number. The maximum number of the index depends on the number of stations with the combination of the defined properties (here: there are 14 stations from Germany which are primary producers, so the index is from 01 to 14).
-- Also the index has a prefix (default: one empty space, e.g. "Station DE / Primary producer **14**". 
-- The index should stay the same when some stations are set invisible. Example: If there are stations "DE01" to "DE12" and station "DE10" is set invisible, stations "DE11" and "DE12" should keep the same index.
-- If stations are merged, the anonymisation label applies also for merged station names. The index is used also for merged station labels, e.g. if there are 12 stations from Germany and stations 2, 4 and 6 are merged, the anonymisation label for the merged station would be "DE13". Stations hidden in merged stations keep their anonymisation labels.
- Below the index a preview shows the current label structure as defined before. Thus, it is not necessary to click on the Apply button to see the result (which might take some seconds in larger datasets.
- If there is no country or type of business in the dataset, do not show a placeholder (not "null", not "N/A"...), only show the first prefix (trim leading and tailing white spaces); example: "Station DE / Primary producer" would become "Station".
- Just like in colour highlighing options it is possible to limit the labels to certain stations by defining conditions.
________________
- Filter table: 
-- When the anonymisation label is active, show in the station filter table an additional column "Anonymisation Label" showing the current station labels. The column should appear on the right next to the column "Name".
-- The anonymisation label of invisible stations (also invisible due to being in a merged station) should be shown in the filter table.
________________
- Saving: If the user has activated the anonymisation label and wants to save data in a JSON file by clicking on the menu button "Download Data", a notification should pop up telling the user: "You are currently displaying anonymised station names. Please note that FCL web saves the original data and not the anonymised data to the JSON file. Would you like to proceed?" Show buttons "Cancel" (as preselection) and "Save".

![fcl-c730_Anonymisation preset_Station8.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/47525586-7f57-4553-a145-bbbd45471a4f)

**Comment by afalenski** [comment]
- [x] Only for station names

**Comment by ruegenbfr** [comment]
#### To the bugs:

> **BUG**: After adding a highlighting rule (label or colours and shapes), the Load Example Data button does not work anymore. It is necessary to reload the webpage (F5).

This is a bug and it will be fixed.

> **BUG**: Go into edit mode of the anonymisation label, delete the row country, click apply and then click Cancel. When you go again into edit mode, the row Country is still not there, although the action was cancelled.

This is **not** a bug but standard behaviour: Cancel discards only changes done after opening the edit dialog or pressing apply.

> **BUG**: Define a condition (e.g. name ==(Regex) "Case.*"), click OK, activate anonymisation label, edit, click on the "-" button next to the condition. It is only possible to click "Cancel". Apply and OK are greyed out. How should the user delete a condition added to the anonymisation label?

This is **not** a bug. In this scenario the user needs to deselect 'Use conditions' before saving the anonymization rule without conditions.

#### Other remarks:

> Always in the last row there is an additional option "Index"

The user can move the index to a different position. If the user adds a new property the property is added after the last property. In case there is no last property the new property is added before the index.

**Comment by ruegenbfr** [comment]
Bug 

> BUG: After adding a highlighting rule (label or colours and shapes), the Load Example Data button does not work anymore. It is necessary to reload the webpage (F5).

was fixed.

**Comment by afalenski** [comment]
- [x] Bug is fixed. Example Data button works again, also after having added a highlighting rule.
- [x] 
____________________________________
**Bug:** 
- load the Example Data
- activate the anonymisation rule
- delete Country and ToB in this rule
- download this variation of the Excample Data
- delete "DE" for Station Case 2 in `{"id":"Country","value":"DE"},` in the JSON file
- upload the file in FCL web
- activate the anonymisation label
- add Country and ToB to the anonymisation rule
- now, try to filter for "station c" in the column header filter of the filter table. The filter table is empty. Entering "station d" also leads to an empty filter table.

However, doing the following, the filter table filters as usual:
- download the default Example Data
- delete "DE" for Station Case 2 in `{"id":"Country","value":"DE"},` in the JSON file
- upload the file in FCL web
- activate the anonymisation label
-  filter in the column header filter table for "Station c". Only "Station Customer" is visible in the filter table as expected. If you delete Country and ToB in the anonymisation rule now, the filter still works as expected.
____________________________________

**Comment by ruegenbfr** [comment]
BUG not reproducable in Firefox 115.3.1esr or Chrome 118.0.

What I did:
- modify the ExampleData-JSON data as described above
- upload the modified JSON
- activate anonymization label
- switch to station filter
- enter "Station c" into column filter for column "Anonymized Name"
  --> Filter table contains 1 entry
- open Anonymization-Rule Edit Dialog, remove properties "Country" and "Type of Business", press "Ok"
- switch to station filter
  --> Filter table contains 0 entries 
-  open Anonymization-Rule Edit Dialog, add properties "Country" and "Type of Business", press "Ok"
-  switch to station filter
  --> Filter table contains 1 entry

**Comment by bfrgottscma** [comment]
Last bug is no bug but a feature request. A separate ticket will be created
