### ISSUE TITLE
Sort columns

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#734]
As a user I would like to sort columns in the filter table in an easy way.

- When clicking on the 3 dots in the filter table, show "Sort columns" menu directly next to "Show columns".
- Only show those column names in "Sort columns", which are ticked in "Show columns". Show them in the same order as in "Show column" by default.
- When ticking a box in "Show columns", directly add this column headline to "Sort columns".
- Add 6dot-sorter icon in front of every column headline in "Sort columns" and allow to sort by drag&drop. Dragging should only be possible within the window width of "Sort columns".
- After clicking "OK", the sorting should be visible in the filter table.
- Ignore checkboxes in sorting list on the right in the mockup.
- Anonymised name column appears by default between ID and Name (in the default order)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK01XQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e902b07ad00b7fc190220a3c070eb1cace1e63c5/fcl-c734_Sort%20columns.png)

**Comment by ruegenbfr** [comment]
Done!

Solution differs from ticket discription (in agreement with ticket author) as follows:
- Instead of 2 major headings ('Show Columns' and 'Sort Columns') only one is used ('Station Columns' or respectively 'Delivery Columns')
- the selection list has a 'Select:' header
- the sort list has a 'Sort:' header

**Comment by afalenski** [comment]
- Looks nice.
- When ticking a box of a station or delivery, this column header appears in the sorting list.
- Only ticked headings appear in the sorting list.
- Newly ticked headers are sorted by default due to the default column order. When dragging "Observed" as first column and ticking "Cross contamination" next, this is sorted after the last of the ticked headings (here: "Common Link"), although "Type of Business" was dragged as last column. Good.
- Column headers can be sorted by drag&drop.
- Sorting by drag&drop is only possible in the vertical direction. Entries cannot be dragged to the left or right. Good.
- When sorting columns in the filter table by drag&drop and opening the Select/sort columns menu, this new order is also represented there.
- When clicking "OK" the new order is shown in the filter table.
- Anonymised name column appears by default between ID and Name (in the default order)

Strange, but still OK: 
- Load Example Data
- Activate Anonymisation Label in the stations highlightings
- Open "Select more columns"
- Tick box at column "Observed" and drag it up as first column
- Tick box at column "Name"
In this special case, the name appears **before** "Anonymized Name", although the default sorting is after (in both Firefox and Chrome). This is surprising, but OK.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 115.4.0esr (64-Bit)
- Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit)
