### ISSUE TITLE
Show checkbox labels in 'Show columns' dialog in grey if not available

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#735]
As someone who has used the anonymisation feature and set up a complex filter rule, I would like the rule to work again when I deactivate anonymisation and reactivate it.
- When deactivated, show the column headline "Anonymisation Name" in grey in the "Show columns" menu and in filter / highlighting menus.
- If a complex filter was setup using "Anonymisation Name" (when anonymisation was active) and if anonymisation is deactivated, the complex filter rule should still be there, but non-functional. The filter table should show all entries. When activating anonymisation again, the complex filter rule should work again.

**Comment by ruegenbfr** [comment]
Check box is disabled now!

**Comment by bfrgottscma** [comment]
Works as described in the ticket. Done.
---
Tested in Forefox and Chrome.
