### ISSUE TITLE
Autocomplete panel stays not close to input field

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#736]
The autocomplete panel in a condition list value field stays not attached to the input field when scrolling input field containing elements.

#### Reproduce:
- load example babytea scenario 1
- open tab station highlighting 
- open new rule
- add new conditions OR decrease browser window height   until vertical scrollbar becomes visible
- click on value field in condition list 
  --> autocomplete panel opens
- scroll container with vertical scrollbar (**NOT** the autocomplete panel) 
  --> input field moves away from autocomplete panel

**Comment by ruegenbfr** [comment]
The changed behaviour of autocomplete panel:
It blocks wheel scrolling outside of the panel, but if a scrolling occures nethertheless the autocomplete panel is closed.

**Comment by bfrgottscma** [comment]
When autocomplete panel is open, scrolling is only allowed within this panel. Hence, the panel stays attached to the input field and does not shift anymore. Done.

Tested in Firefox and Chrome.
