### ISSUE TITLE
Increase width of "Grid Size" field in ROA "Page Setup" dialog for firefox

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#737]
The user sees a truncated number in the "Grid Size" field in ROA "Page Setup" dialog. **BUT** only in firefox (102.15.0esr). Chrome, edge and safari are **NOT** affected.

Solution: Increase field width.

Related to issue: #652

**Comment by ruegenbfr** [comment]
Width was increased.

**Comment by bfrgottscma** [comment]
Grid size not truncated anymore
