### ISSUE TITLE
Refine prefix fields in anonymization rule editor

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#740]
The user does not see whether the prefixes in the anonymization rule editor contain leading or trailing spaces. 
Display the " " [space] character as "∙" in prefix fields in anonymization rule editor. Only in the prefix editor not in label preview.

**Comment by ruegenbfr** [comment]
#### Technical solution:
The underlying html input field was put inside a wrapper element. The underlying html input field only knows the display value and the wrapper knows the true value. So all text operations on the html input field needed to be hooked up. The wrapper replaces the white space by the  "∙" symbol. The prefix editor distinguishes between white space and an entered "∙" symbol.

#### To test:
To following behaviours were affected an need to be tested:
- typing
- copying (the copying process copies not the mask "∙" symbol)
- pasting (white space is displayed as "∙")
- dragging (the dragging does drag the mask "∙" symbol)
- dropping (white space is displayed as "∙")
- entering the "∙" symbol (e.g. by pasting, in opposite to mask symbol this symbol can be copied and be dragged)
- all kinds of key short cuts, e.g.:
  - delete word before cursor (Windows: strg + backspace)
  - delete word after cursor(Windows: strg + delete)
  - delete text until end of line (Windows: strg + shift + delete)

**Comment by bfrgottscma** [comment]
To following behaviours were tested:

    typing *OK*
    copying (the copying process copies not the mask "∙" symbol)
    pasting (white space is displayed as "∙")
    dragging (the dragging does drag the mask "∙" symbol)
    dropping (white space is displayed as "∙")
    entering the "∙" symbol (e.g. by pasting, in opposite to mask symbol this symbol can be copied and be dragged)
    all kinds of key short cuts, e.g.:
        delete word before cursor (Windows: strg + backspace)
        delete word after cursor(Windows: strg + delete)
        delete text until end of line (Windows: strg + shift + delete)
