### ISSUE TITLE
Row ordering changes on row selection in filter table 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#743]
The user does not want the filter table row ordering to change on a simple row selection (or graph element selection),
with the **exception** that there is an active "Selected" column sorting. 

#### Reproduce:
- load example data
- open filter table
- sort column "Name" 
  --> rows are sorted (ip row for "Case 1" is next to row for "Case 2")
- sort column "Country"
  --> row sorting does not changed, since all station have country "DE"
- click on some (not yet selected) row
  --> row ordering changes "Case 1" is not any longer next to "Case 2"

#### DevNote: 
On the second sorting the table appears to respect the first sorting and orders the rows accordingly, 
but on selection the changing row ordering does not respect the previous sortings anymore only the last sorting.

**Comment by ruegenbfr** [comment]
Solution proposal:
- allow multiple column sorting (the used underlying table supports this)
- the sort priority should the reverse of the column sort click order (meaning: the last sorted column has the highest priority)
  the build in priorities are reverse (the first sorting has the highest priority)
- the priority is visualized with descending sort icon opacity (meaning highest priority becomes black, the lesser priorities become lighter)
- the multiple column sorting could be made available only on sort click with 'shift' key:
  which means a sort click without 'shift'-key would discard previous sortings but a click with shift would keep the other column sorting and only add the new one.
  **@PO** Please decide!

**Comment by ruegenbfr** [comment]
The sorting was fixed.

#### Final solution:
The sorting works as before only the mentioned artefact (e.g. sorting is resetted after a row selection) does not occur anymore.

#### Technical solution:
Sorting is not done anymore by ngx-datatable. The sorting is now performed on unfiltered rows and applied on the filtered rows.

**Comment by afalenski** [comment]
- "Reproduce" tested -> no bug
- Mark as outbreak and Full Trace set, several filter sortings tested. No bug.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 3

Browsers:
- Firefox 115.4.0esr (64-Bit)
- Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit)
