### ISSUE TITLE
Refine highlighting of properties in property selector and show columns

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#745]
If station anonymization is inactive the property "Anonymization Name" is grayed out in property selectors (e.g. in complex filter) but selectable.
Other properties might be unavailable too (e.g. "Type Of Business"). Please gray them also out in the property selector if no value is available in the data (in all elements not only the visible ones). In the show columns dialog gray them also out (+add the tool tip "Data is not available.") but leave them selectable (in contrast to unavailable "Anonymization Name" column.

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
- For datasets which do not have any type of business (stations) or amount (deliveries), both are greyed out in the filter table column settings. A mouseover text says "Data is not available.". Columns can still be added and sorted.
- Amount (deliveries) or Type of Business (stations) are greyed out in the highlightings configuration menu, but can still be selected and a new rule can be setup.
- Also labels can be added using the greyed out properties. You can sort the "empty" label to the first position and the station / delivery label stays the same in the graph, which is good.

There is one inconsistency:
- In the column selection menu for the filter table the Anonymisation Label is greyed out and **not** selectable. If there is no amount or type of business in the dataset, the column is greyed out **but it is selectable** and sortable and will also be shown in the filter table. In my opinion also the Anonymisation Label should also be selectable and sortable and be displayed in the filter table, if the user wants to do this. A use case could be that the user switches anonymisation on and off several times and would like the filter table layout to stay the same.
@bfrgottscma What do you think? 
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Dataset without amount and in station table with ID and name only

Browsers:
- Firefox 115.8.0esr (64-Bit)

**Comment by bfrgottscma** [comment]
I agree with @afalenski 's suggestion.

**Comment by afalenski** [comment]
- Load Example Data
- Enable Anonymisation Label
- In the filter table, activate the colum "Name" and position it as first column, before column "Anonymized Name"
- Disable Anonymisation Label
The first two columns in the filter table are named "Name". I expected the second column to keep its name "Anonymized Name" and to be empty.

**Comment by ruegenbfr** [comment]
Bug fixed.
In inactivate anonymization the anonymization label is selectable now. This is contrary to the initial task described in ticket text, but was requested by PO.

**Comment by bfrgottscma** [comment]
The issue with the "duplicate" name column is solved now.  Fine. 
However, in the column selection menu for the filter table the Anonymisation Label is greyed out and is still not selectable although it should be according to afalenskis suggestion on March 1.

**Comment by afalenski** [comment]
The problem described on 12.04. is still the same. And it appears as if you could add the column "name" without a limit using the described method:
<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1h0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5bee59b2910f3915b006a3d7a81706e0075ce34/grafik.png" alt="grafik.png" />

**Comment by afalenski** [comment]
- Duplication of column "name" is not happening anymore.
- Anonymisation label is selectable and sortable, even if it is anonymisation is not active.
Great! Done.
