### ISSUE TITLE
Update BfR logo

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#747]
As a user I would like to see the current BfR logo. The current logo is outdated since October 2021.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTV1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ffc9336b5debd246f6f115eb3d3c7d7b0d9ecc4/grafik.png)

Needs to be updated in graph/map, saved images thereof, ROA view and printed PDF thereof

Sent by AF on 10.11.2023 at 09:36.

**Comment by afalenski** [comment]
Logo is present in 
- Graph view
- GIS view
- ROA style
- ROA style PDF

Grey logo background in graph and on map is slightly transparent as before.
Printing the ROA style as PDF, the logo is at 400% a bit blurred (Firefox) or a bit angular (Chrome). This is handled in a separate ticket.

Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 115.4.0esr (64-Bit)
- Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit)
