### ISSUE TITLE
Rename delivery names in baby tea examples and adapt delivery label

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#753]
For historical reasons the delivery names contain currently a lot no suffix. 
But the delivery name should only contain the product name and not the lot no.

Tasks: 
- strip the lot no suffix from the delivery names
- add a second delivery label highlighting rule to show the lot no additionally

Example:
Old name: **Organic dried rose hip peels, Lot no. R31**
Lot: **R31**
Old label: **Organic dried rose hip peels, Lot no. R31**

New name: **Organic dried rose hip peels**
New label: **Organic dried rose hip peels / R31**

**Please note:** The text `Lot no.` will not be part of the delivery label.

#### Other cleaning tasks:
- merge delivery highlighting rules "Name Smart-T Womens Balance" & "Name 1" and name the merged Rule "Product name"
- name the new rule "Lot"
- drop the conditions in the labeling rules for scenario 1 & 2
- rename station highlighting rule "Name 1" to "Name"
- remove the lot number "Dried organic melissa leaves" from the deliveries with the name "Dried organic melissa leaves"
  **Please note**: If the lot numbers "Dried organic melissa leaves" are removed from the data (this affects 2 deliveries), the web app assigns the 2 deliveries to different lots.

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
So nice that the user can now choose whether to display the lot!
Special rule for Smart-T Women's balance is active.
Renaming done.
Done.
