### ISSUE TITLE
Increase mouse-over text size

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#754]
As a user I find the mouse-over text size from the buttons too small and would like to get a larger font displayed.
This refers to Ticket mpc#42

- Roboto 14px, like the texts in the blue menu bar, but not boldface
- Reduce the size of tooltip from context menu also to 14px
- All tooltips (except for ROA) to the same size: 14px

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
Mouse-over text is better readable.
Sometimes it gets in the way when one wants to click on a button and the button is overlapped by the mouse-over text. but this is not new.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Babytea Scenario 3

Browsers:
- Firefox 115.4.0esr (64-Bit)
- Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit)
