### ISSUE TITLE
Research: Improve display of 'Created with...' banner in PDF from ROA style

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#755]
As an FCL web enthusiast I would like to see the banner "Created with FoodChain-Lab by BfR" in the PDF from the ROA style as sharp as in the online view of the ROA style.

Idea: Use SVG in the ROA style instead of a PNG.

All images at 400%:
ROA style online (in Chrome):

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7741e08bd69b2462c147a07c617e50043eb3a3b7/grafik.png)

PDF from ROA style saved in Firefox 115.4.0esr (64-Bit):
The font is a bit blurred and a little smaller.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWZxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a7053fa30b61056dcdaf36898e0fc54c01faa66/grafik.png)

PDF from ROA style saved in Google Chrome Version 119.0.6045.124 (Offizieller Build) (64-Bit):
The font is a bit angular.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6fec63c1afde3567a06469bc377c4fd7a28bd95/grafik.png)

**Comment by bfrgottscma** [comment]
Check if we have influence on the library that creates PDF in Firefox. Maybe we can provide a different image format to improve it.

**Comment by afalenski** [comment]
Note 11.07.2024: In Firefox 128.0 the logo is much sharper than in previous Firefox versions.

**Comment by arne-z** [comment]
@afalenski do we have an SVG file for the created with fcl banner? If we do it should be possible to exchange it.

**Comment by afalenski** [comment]
All examples at 400% (in Browser or PDF)
- ROA in Firefox Browser
<img width="1632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9305c77df092e81afd6a19db8dff1df2a25edad/grafik.png" alt="grafik.png" />

- ROA PDF "printet" with PDF24 in Firefox:
<img width="839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWpmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5013623d9066c24d9e9ef274c4ae1eef2b9f870c/grafik.png" alt="grafik.png" />

- ROA in Chrome Browser
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8efb99b47ad338afc847678bd02ce60693765277/grafik.png" alt="grafik.png" />

- ROA PDF "printet" with PDF24 in Chrome:
<img width="659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTdmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4877186f47d394fec4592ae03e89f88a9a4c0c6/grafik.png" alt="grafik.png" />

A great improvement!
Done.
