### ISSUE TITLE
Create predefined templates/libraries within the graph editor

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/fcl-client#76]
As a portal user I need specifically for my needs adapted libraries that I can drag and drop onto the editor
Mockups will follow

**Comment by bfrgottscma** [comment]
tool box name: ROA style

Begin with shape "additional information" --> see EFSA Mockup page 12 (yellow box with dashed/dotted line etc.)

Depending on effort later also additional shapes (station, country, lot, sample, connectors)

**Comment by bfrgottscma** [comment]
Please add predefined box for cases (see EFSA mockup (page with "proposed visio-like outout"): white box with red dotted outline).
Please change color of probable sample to orange.
