### ISSUE TITLE
Fix model upload in safari browser

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#761]
The model upload in safari browser (version 15.4 [17613.1.17.1.13]) is not working properly. 

This problem is **not** present in:
- firefox (v115.6.0esr)
- edge (v120.0.2210.91)
- chrome (v120.0.6099.129)

#### Reproduce:
- load some example or upload model
  --> model is loaded
- upload model
  --> File open dialog does not open anymore, console does not show any problems

**Comment by j-hha** [comment]
- note: problem affects Safari v > 15.4 (could reproduce for v18.0)

**Comment by j-hha** [comment]
@bfrgottscma @afalenski could we talk about this real quick today? I'd have to change the behaviour of the upload buttons a bit to fix this bug and I'd like to confer with you on that.

**Comment by j-hha** [comment]
Oct 17, 2024: Decision PO: trigger the async data-altered-check and subsequent the proceed-dialog on click on 'upload data' button rather than on proxy file upload button and only open the menu containing the proxy file upload buttons after this has been sorted
