### ISSUE TITLE
Highlighting Rule Editor looses changes

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#768]
The highlighting rule editor looses changes on changing some tracing settings in the graph.

Reproduce:
- Load Example Data
- Open some highlighting rule editor (.e.g. 'Outbreak' rule)
- Change the rule name (but do **not** use '**Apply**' or '**Ok**') and leave the rule editor open
- Change some tracing setting in the graph (e.g. set the forward trace for some graph element)
  --> the rule name changes vanishes

Expected behaviour: The values in the rule editor should not be affected by any changes in the graph.

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
After changing the highlighting name or colour, you can in the graph...
- assign full trace to a station 
- mark a station as outbreak
The changed highlighting settings stay as entered and you can click "Apply" or "OK" and the new settings are set.
Now, the values in the rule editor are not affected by changes in the graph.
Done.
