### ISSUE TITLE
Station samples are not correctly displayed

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#769]
The ROA report allows the configuration of the labels of lot sample boxes and station sample boxes. The default station sample box label configuration displays in the second row the '**material**' of the sample. However, the roa report misses this line.

#### To reproduce:
- unzip the attached model and load it into the fcl web app
- open ROA configuration
  --> the 'Station Sample Box Label' configuration contains '**material**' in the second row
- click '**Generate Report**'
  --> the report contains 3 sample boxes: the top one is a lot sample from an incoming delivery, the second one is a station sample box and the third one is a lot sample from a lot produced by '**Ottos Gefrierobst**'
  The station sample box is missing the '**material**' line

#### Solution:
Add the missing line to the ROA report.

#### Atachments:
- [Model with samples](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ebcc48c0c9f32ccc998d3cbe850f7b1f9834151/FclData_With_samples.json.zip)

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
I can see the material row "Environmental sampl" in the red box.
@ruegenbfr 
- I do not understand why samples are not shown in one of the filter tables in the graph view.
- Why are samples in the JSON file not below "data", but parallel to "version" and "data"?
