### ISSUE TITLE
Improve header labeling in roa report header boxes

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#771]
The roa report contains on the left side yellow boxes (header) which contain usually a label which reflects the type of business of the stations in their level. In bigger networks these labels exceed often the boundaries of their boxes. So that the layers overlay with each other (and you cannot read them anymore). I some cases if a label exceeds the top boundary of the top box a lot of additional space is added above the report. The printing previews show additional nearly empty pages inn this case.

#### Reproduce:
- load Example data
- generate roa report

#### Solution proposal:
- Wrap text in header cells
- Put type of businesses in seperate lines

**Comment by ruegenbfr** [comment]
Which solution shall it be?
A: (one type of business per header label line)
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34bcf8b892d06eb149f684f1186e49559818f6dd/Bildschirmfoto%202024-02-27%20um%2017.42.45.png" alt="Bildschirmfoto 2024-02-27 um 17.42.45.png" />

or
B: (automatic word wrap in header boxes)
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f029bdefacbf836f1f4848039745d55553017fab/Bildschirmfoto%202024-02-27%20um%2019.04.47.png" alt="Bildschirmfoto 2024-02-27 um 19.04.47.png" />

**Comment by ruegenbfr** [comment]
Done!
As discussed today in the morning with PO, the headers now contain one ToB per line. 
The header width is sensitive to the line count.  

Proposal for a next tickets: 
- Farm to fork should consider a ToB ranking (requires a ToB ranking) ==> reduction of ToB count each header cell 
- The ToB within each header cell should be sorted in some convenient they (requires a ToB ranking)

**Comment by bfrgottscma** [comment]
Done in Chrome.
We will deal with the TOB ranking that @afalenski mentioned in his comment as soon as we have a controlled vocabulary for TOB.
