### ISSUE TITLE
Station anonymisation in ROA

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#772]
As a user I would like to print out anonymised station data as ROA report.

- If the "Anonymisation Label" is activated and the user clicks on the ROA Style button, show a reduced ROA configuration dialogue

**ROA Report Configuration** 
- Deactivate the dropdown arrow (and do not show it) for the Company Box Label, so that no configuration is possible
- Show a triangle with exclamation mark. Mouse over message: "Anonymisation Label is activated. To configure the station information shown in the ROA Style, deactivate this label in the station highlighting menu."

<img width="562" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a597e1df42fe5e39fb8449dc14d5efbf49a969ab/fcl-c772_Station%20anonymisation%20in%20ROA.png" alt="fcl-c772_Station anonymisation in ROA.png" />

- In the ROA Style report only show the anonymised name, not a combination of Type of Business and Station Name:
<img width="558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1ee79bb0375d92d08f19d118abcbc2ef23d4a01/grafik.png" alt="grafik.png" />

**Comment by ruegenbfr** [comment]
Done!
Roa report configuration saves nethertheless the station box label configuration. The station boxy label replacement (in case of active station anonymization) by the '**Anonymized Name**' label is only transient. If the user disables anonymization in the highlighting rules, the last roa report configuration (given the loaded model) is used.

**Comment by afalenski** [comment]
When I load the example data, click on the button "ROA Style" and then on "Generate report", there is only a squared white empty sheet. There are no boxes for country, station or delivery. Please fix.

**Comment by ruegenbfr** [comment]
I am sorry that I did miss to test firefox, but feature works in
chrome (v121.0.6167.184), edge (v121.0.2277.128) and safari (v 15.4).

I will check what's going on in firefox.

**Comment by bfrgottscma** [comment]
Works now in Firefox as well. Anonymised name is transferred to ROA view. Report Configuration shows warning for Company Box Label + you cannot change the company settings in case anonymization is switched on. If switched off, the Report Configuration dialoge restores the old settings for Stations. Done.
