### ISSUE TITLE
Change colour for "Observed" from blue to green in the 3 BabyTea example datasets

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#773]
This is a remnant of former highlighting colours coming from the FCL Desktop application. The default colour for "Observed" is green (RGB 0, 255, 0) and should be used in every example dataset.

**Comment by ruegenbfr** [comment]
Done!

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
Activating "Set Trace" in Baby tea datasets leads to a green station colour, now. Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1
- Babytea Scenario 2
- Babytea Scenario 3

Browsers:
- Firefox 115.11.0esr (64-Bit)
