### ISSUE TITLE
AiO: Data import via FCL AiO template (one template)

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#774]
As a user I would like to be able to load an All in One template (Excel, from FCL Desktop) into FCL Web. This ticket deals with uploading one All-in-one template.

- [x] When clicking "Upload data" a drop-down menu is opened with the entries "FCL file (.json)" and "FCL All-in-one template (.xlsx)"
- [x] When clicking one of those entries, the "Save changes" warning dialogue is opened first
- [x] When selecting "Proceed", the file selection dialogue is opened
- [x] Here the user can select and load an Excel file only .xlsx files are shown
- [x] If the file is not in the correct format, please show an error message as a toaster on the bottom of the page: "Invalid data format. Please select an .xlsx file with the correct format (FCL All-in-one template)!"

Loading several AiO templates will be handled in a separate ticket.
Plausibility checks will be handled in a separate ticket.
Test will be handled in a separate ticket.

**Think of Tests**
- [x] Excel testsheet needed
Provide AiO template + enriched AiO template with additional columns (e.g. GIS columns) but they are empty + enriched AiO template with filled GIS columns
- [x] E2e test needed
- [ ] Integration test needed
- [x] Unit test needed

**Comment by arne-z** [comment]
MVP 1:
- Can read the example a1o template provided by Alex.
- Displays the graph from that template.
- Fails if the template has errors.


Notes: 
- Possibly change error toaster to a summary modal in the future.

**Comment by bfrgottscma** [comment]
@ruegenbfr Thanks for your current work. As decided in todays discussion, the aim of this ticket is to produce a minimum viable product: It should be possible to load the example data file that @afalenski provided and that the testers are able to test this in the GUI.
All additional work on validation etc. will not be lost but will go to follow-up tickets that will be created in the next days.
