### ISSUE TITLE
Allow "Kill contamination" for deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#775]
As a user, I would like to be able to set a delivery as "Kill contamination" as in FCL Desktop.

- [x] When right-clicking on a delivery, a context-sensitive menu is opened. Please add the entry "Set Kill Contamination" in the context menu. The effect should be the same for deliveries as it is currently for stations, except that it should only be active for the single product lot on which the mouse pointed when the context menu was opened.
If "Set Kill Contamination" is activated, 
- [x] the delivery is shown in grey, 
- [x] the scores are recalculated
- [x] the entry appears in the legend
- [x] the trace stops at this delivery
.
- [x] If "Unset Kill Contamination" is selected, the above mentioned steps are made undone 
- [x] Please add the default rule "Kill Contamination" to the delivery highlighting tab (already done)
- [ ] Check if score calculation in FCL Web is still correct after introducing this additional functionality 
- [ ] context menu when clicking on the empty canvas to unset Kill Contamination ("Clear Kill Contaminations" with sub-menu "Clear Kill Contamination Stations", "Clear Kill Contamination Deliveries", "Clear All Kill Contaminations")

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
In general: See tickmarks above.
Scores are recalculated, but I do not understand the calculation for deliveries:
- Set Sugar Sg_70001 "Mark as Outbreak": Score = 1, Weight = 1
- Set Sugar Sug_39 "Mark as Outbreak": Score = 0.5, Weight = 1; values for SG_70001 stay the same
- Set Sugar Sug_39 "Kill Contamination": Score = 0, Weight = 0; SG_70001: Score = 0.5, Weight = 1
Should the Score of SG_70001 not equal 1 again?

**Comment by ruegenbfr** [comment]
Menu entry added.

**Comment by bfrgottscma** [comment]
Unfortunately, deliveries not shown in grey anymore when Kill Contamination is set for them.
