### ISSUE TITLE
Station highlighting tab: Remove station size configuration

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#779]
In the station highlighting tab, the dialogue field on station size configurations can be deleted. Currently, we do not have a use case so far for this. If we have a use case at some point, the functionality can be included later.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment]
Done!

**Comment by afalenski** [comment]
Done.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data

Browsers:
- Firefox 115.11.0esr (64-Bit)
