### ISSUE TITLE
Make mouseover texts "invisible" for the mouse pointer

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#781]
As a user who has got above an element containing a mouseover text I would like to use the left and right mouse buttons on elements / the graph or map background behind the mouseover text.

-Please let mouse over text disappear when moving the mouse pointer off of the respective element (already works if mouse moves in opposite direction of mouse over text but not in the direction of the text)

If this does not work or if it is to complicated to implement, please just change the time delay after which the mouse over text appears::
-  The mouseover text should appear only after 1.5 seconds (currently, it is less than 1 second) (only in the hamburger menu and the header menu)
-  Leave the current timing fo the context menu in the graph

<img width="326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99892f7bc45cb6717712e3a16cbc41df90db0d7a/grafik.png" alt="grafik.png" />

Although the mouse pointer (not visible here) was below the mouseover text box, the station "Case 1" could not be clicked.

<img width="380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NuQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e94ac3fd343ee6e0c07e225760a8894828915ec1/grafik.png" alt="grafik.png" />

The slider of the upper highlighting rule cannot be selected.

**Comment by ruegenbfr** [comment]
Done!

Please note: Due to this change, the tooltip text is not selectable anymore.

**Comment by afalenski** [comment]
Mouseover text disappears quickly as soon as the mouse pointer leaves the mouse over area and thus it is possible to click on buttons which were blocked before. Great! Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Babytea Scenario 3

Browsers:
- Firefox 115.11.0esr (64-Bit)
