### ISSUE TITLE
Data overlay in filter table

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#782]
**Describe the bug**
After loading example data files and opening the data table, all data lines appear as overlay in one data line, the rest of the table is empty. When mousing over this overlay or clicking "select" in this overlay, only the first line is shown, the rest of the table is empty. Filter operations in table header work as expected.

Bug appears on Dev and Prod in Firefox but not in Chrome. Bug appeared during test with slow internet connection on train line.

**To Reproduce**
1. Load Example data
2. Open data table
3. See overlay
4. Test with mouse over and test with select

**Screenshots**
<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGREQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f629d0965cc7ba77de471f60b7132840cc464f10/grafik.png" alt="grafik.png" />
overlay

<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17fbf05a3129a9cab4d8b7422449ce3c0dfadc8c/grafik.png" alt="grafik.png" />
view after selecting in overlay

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: only in Firefox (bug does not appear in Chrome)
 - Version: 126.0.1 (64-Bit)
 - Slow internet connection
 
InstallTrigger sollte nicht mehr verwendet werden und wird in Zukunft entfernt werden. mxClient.js:159
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe https://xhr.spec.whatwg.org/#sync-warning zone.js:2722:30
Angular is running in development mode. Call enableProdMode() to enable production mode. core.mjs:23480:16
You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine. 2 cytoscape.cjs.js:844:12
Fehler beim Verarbeiten des Wertes für '-webkit-text-size-adjust'.  Deklaration ignoriert. normalize.css:13:2
Unbekannte Eigenschaft 'speak'.  Deklaration ignoriert. icons.css:19:2
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. icons.css:22:2
Unbekannte Eigenschaft 'speak'.  Deklaration ignoriert. icons.css:32:2
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. icons.css:35:2
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. _mixins.scss:28:2
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. _typography.scss:330:4
Unbekannte Eigenschaft '-moz-osx-font-smoothing'.  Deklaration ignoriert. _typography.scss:330:4
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. _vendor-prefixes.scss:22:2
Unbekannte Pseudoklasse oder Pseudoelement '-ms-clear'.  Regelsatz wegen ungültigem Selektor ignoriert. grapheditor.css:9
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:62:1
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:88:4
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:272:1
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:294:1
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:300:1
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. grapheditor.css:310:1
Unbekannte Eigenschaft '-moz-box-shadow'.  Deklaration ignoriert. common.css:30:18
Unbekannte Eigenschaft '-moz-box-shadow'.  Deklaration ignoriert. common.css:115:18
Unbekannte Eigenschaft '-moz-box-shadow'.  Deklaration ignoriert. common.css:130:18
Fehler beim Verarbeiten des Wertes für 'overflow'.  Deklaration ignoriert. fcl-portal-dev.bfr.berlin:10:13
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. fcl-portal-dev.bfr.berlin:1:1822
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. fcl-portal-dev.bfr.berlin:1:2802
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. fcl-portal-dev.bfr.berlin:1:2987
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. fcl-portal-dev.bfr.berlin:1:3301
Fehler beim Verarbeiten des Wertes für 'border-radius'.  Deklaration ignoriert.

**Comment by ruegenbfr** [comment]
This bug does also appear in environment:
- OS: Mac OSX 12.3.1
- Browser: Firefox (v. 126.0.1)

However it does not appear in the previous major version of Firefox (v.125.0.3) or in the last ESR version (v.115.11.0.esr)

**BUT**: The underlying external lib **@swimlane/ngx-datatable** seems to operate just fine, [see](http://swimlane.github.io/ngx-datatable/#virtual-scroll)

**Comment by bfrgottscma** [comment]
As discussed, we will not wait for Firefox to fix this issue. Please use the existing solution from a third party as @ruegenbfr suggested.

**Comment by ruegenbfr** [comment]
Done as requested.

**Comment by bfrgottscma** [comment]
Station and delivery table do not show an overlay with regard to the data lines anymore. Filter and sorting operations on the table header are working as expected. Done.

Tested in Windows system with Firefox 115.15.0esr (64-Bit) and Firefox 131.0 (64-Bit).
