### ISSUE TITLE
Refine display of legend entries

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#785]
As a user I would like the position of legend entries to be comprehensible.

At the moment, the position of an entry in the station highlighting list defines its position in the legend. However, if there is only a delivery highlighting active (e.g. Outbreak, Kill Contamination) and if you move this to another position in the Highlightings tab, it does not move in the legend or moves to surprising positions:

Example:
In the highlighting conditions list Outbreak is at the first position in delivery and station highlightings. However, if only deliveries are marked as outbreak, the entry "Outbreak" is the last entry in the legend. If you add an outbreak station, it becomes the first entry. Outbreak should always at the same position in the legend as in the highlighting conditions list.

Could the rule for the position in the legend be amended?
- Station highlighting defines the position of default station and delivery highlightings in the legend (default delivery and stations rules are "connected" for the visualisation)
- Also the positions of additional (non-default) station highlightings in the legend are defined in the station highlighting list.
- Additional (non-default) delivery highlighting rules are always positioned after station highlighting rules in the legend. 
- A jumping of default rules shall not happen, because the positions of station and delivery default rules in the legend ar defined by the order of station highlighting rules. This means that even if "Outbreak" is only set for a delivery, it is (in the default sorting) at the first position.

**Comment by arne-z** [comment]
After discussion with Marion:
The duplicate names issue is will be considered out of scope for this story, and will be handled in a separate ticket.

**Comment by afalenski** [comment]
- Moving a station highlighting in the highlightings list affects station and delivery highlightings in the legend: Outbreak tested, Kill Contamination (delivery) added and tested; delivery "observed" on position one and station "observed" on position 3 -> full tracing on delivery is on position 3.
- A new delivery highlighting (position 1 in the highlighting list) is shown as last entry in the legend.
- Switching station highlighting "outbreak" off (position 2) leaves the arrow of the delivery highlighting "Outbreak" (position 5) on position 2 in the legend.
Great! Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Babytea Scenario 3

Browsers:
- Firefox 115.13.0esr (64-Bit)
