### ISSUE TITLE
Hot fix: Notification on optimal browser on landing page

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#786]
As a user I would like to be informed that currently FCL Web is running optimal on Google Chrome (in Firefox there is currently a visualisation issue #782 that needs to be fixed by Firefox).  

Please include a notification on the landing page of the productive version on FCL Web.

Text (Roboto sans serif, 14Px, Schwarz, Textbox mit Rand (Farbe: 244, 177, 131):
"FCL Web is optimized for the latest version of Google Chrome"

Mockup of the visual appearance can be seen in #685

The notification will be removed when issue #782 is resolved.

**Comment by ruegenbfr** [comment]
Done on production site. 
Text is not bold as discussed with PO.

**Comment by afalenski** [comment]
The text box is centered, colour is fine, the text is correct.
Done.
