### ISSUE TITLE
App does not load in safari

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#787]
The fcl web app does not load anymore in older safari (Version 15.4). Please test if it works in latest Safari version. If it does not load, we will discuss if we really want safari.

**Comment by j-hha** [comment]
09/05/2024: Tested in Safari Version 17.6 --> App loads and seems functional, too. I'd recommend that we close this ticket.

**Comment by afalenski** [comment]
I do not have an apple device with Safari nor a Browserstack login. I cannot test this.

**Comment by j-hha** [comment]
We can test this together tomorrow on my machine @afalenski

**Comment by afalenski** [comment]
@j-hha Thank you! And sorry, I did not read your comment. As you have already tested that FCL Web works, this ticket is done.
