### ISSUE TITLE
Invisible station cannot be made visible again in the graph

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#796]
Invisible station is not made visible in the graph

**To Reproduce**
- Load example data
- Open menu, Filter table
- Make station "Geisler Organic Food" invisible
- Show properties of station "Grindel..."
- Hover over all the deliveries (especially over that from Geisler Organic Food)
- Click somewhere outside of the properties dialogue to close it
- Right-click into the graph background and select "Clear invisibility" -> "Clear All"
Now, station "Geisler Organic Food" is visible in the filter table, but it is still missing in the graph. In addition, it is not possible to select "Clear invisibility" because it is greyed out. For FCL-Web, all stations are visible (although they are not).

**Expected behavior**
Station should also be displayed in the graph again.

Dev Note: ERROR TypeError: newData.delIdToEdgeDataMap[delId] is undefined

**Comment by bfrgottscma** [comment]
When following the steps described above, the bug does not appear anymore. Station is made visible again in the graph and in the data table. Done.

Tested in Firefox on SINA system.

As the bug also appears on Prod and blocks e.g. loading a new example file, we should aim for a new release in the near future.
