### ISSUE TITLE
Station property dialogue: Fit text length of deliveries to boxes

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#804]
Sometimes, the names of deliveries are too long to fit in the delivery text box in the station property dialogue (see Example data set, Station properties of Case 4). 

<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17271ff9274ac86f2d3a6f4af53661fdcc00c9d2/Delivery%20boxes.png" alt="Delivery boxes.png" />

However, as a user, I do not want the text in the delivery boxes running over the margins of the respective text boxes since this looks buggy. Please fit the text length to the boxes (e.g. by adding a line break and another line of text in the box).

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by j-hha** [comment]
Debugging notes: 
- white-space on <text> only seems to work in firefox and not in chrome (test with https://developer.mozilla.org/en-US/play)

**Comment by bfrgottscma** [comment]
Go for the dots and the tool-tip.

**Comment by afalenski** [comment]
I just read this ticket by chance. Great that you like the 3-dot solution. This morning I also thought about this and the functionality adds to readability, see #942.

**Comment by bfrgottscma** [comment]
Tested in Firefox and Chrome. Nicely done. Positioning of the tooltip at the bottom due to constraints in the library is fine.
