### ISSUE TITLE
Baby tea example datasets with Kill Contamination rule for deliveries

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#805]
Please replace the 3 data files for the Baby Tea example with the respective data sets including a Kill Contamination rule for deliveries.

**Comment by afalenski** [comment]
- All three BabyTea datasets contain the "Kill contamination" highlighting.
- Kill contamination works: If a delivery is set to kill contaminations, the trace breaks off for the following products/ingredients.
- The grey shade is correct.
Great! Done.
