### ISSUE TITLE
Update Angular

### ISSUE THREAD

**Issue by arne-z** [SiLeBAT/fcl-client#807]
[Our current version of angular is no longer supported](https://angular.dev/reference/releases#actively-supported-versions), this is now starting to cause security issues, as vulnerabilities in other packages that angular V15 relies on are not fixed in the versions V15 is compatible with.

We need to at least update angular to V16, in order to fix current vulnerabilities (see [this dependabot issue](https://github.com/SiLeBAT/fcl-client/security/dependabot/85)).

Angular V16 is only on long term support until November this year, so this is only a short term solution as well. Preferably we should update to V17 or V18 which are supported until mid or late 2025.

See the [angular update guide](https://angular.dev/update-guide?v=15.0-16.0&l=1) for step by step instructions for updating angular versions. It is recommended to update angular one step at a time, rather than directly jump from 15 to 18.

- [ ] Update angular to V16
- [ ] Maintain compatibility with our other libraries.

In the future we have to Update angular to V17+

DevNote:
Angular V16 supports node.js v16

**Comment by Bazeel-Waris** [comment]
Would you like to share the complete plan to update to the Angular v16 in detail? I mean from which component should I start?
