### ISSUE TITLE
Filter table shows wrong row icon

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#818]
The filter table shows for deliveries and stations an incorrect row icon.

The station table wrong shape and wrong color.
The delivery table shows wrong color.

##### Reproduce:
- Load baby tea 2
- Set Full Trace on some station 
   -  Open GraphContextMenu on some station
   -  Choose Set Trace 
   -  Choose Full Trace
- Look at row icons in first column in filter table

**Comment by afalenski** [comment]
Station icons and delivery colours are updated instantly. No wrong shapes or colours can be seen. 
Done.
