### ISSUE TITLE
AiO: Template validation - Warning for duplicate StationIDs and DeliveryIDs

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#855]
Check for duplicate IDs in spreadsheets "Stations" and "Deliveries".

If duplicate IDs appear, the respective data lines are ignored and not imported since e.g. in case of duplicate StationIDs it is not clear which of the deliveries is connected to which station. 

A warning should be shown in the warning modal (see ticket ...).
"There are duplicate IDs in the [spreadsheet name(s)] spreadsheet ([List of duplicate IDs in this spreadsheet] (e.g. 53, 87, 106)). Data lines with Duplicate IDs were discarded and not imported."
In case of both the Station and the Delivery spreadsheet being affected: "There are duplicate IDs in the Station spreadsheet ([List of duplicate IDs in Station spreadsheet]) and in the Delivery spreadsheet ([List of duplicate IDs in Delivery spreadsheet]). Data lines with Duplicate IDs were discarded and not imported."

To do:
- discard duplicate StationsIDs (+connected deliveries), duplicate DeliveryIDs --> change current behaviour
- prepare data structure for fronend and write into store
- develop warning state that can be accessed by warning modal

Ticket does not contain the UI for the warning modal

**Comment by arne-z** [comment]
Behavior concerning duplicate station IDs:

If two or more stations have the same ID, all of those stations are omitted from the imported dataset.
If a delivery has one of those omitted stations as either source or target, that delivery is omitted as well.

**Comment by arne-z** [comment]
The PR for this Ticket should target the feature-template-warnings feature branch rather than dev.
