### ISSUE TITLE
At login grey out all buttons which cannot be used without data

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#877]
As a user I would like to be guided to which buttons I may use after logging in into FCL web.

If no data is uploaded:
- Grey out the buttons "Download Data", "Save Image" and the menu button; strip the buttons of their functions.
- Hide both the zoom button and slider

As soon as data is available (example data, uploaded data), everything should be visible and work again.

**Comment by bfrgottscma** [comment]
GIS, Download Data, Save Image and menu button are greyed out and not functional as intended and the tooltip still works. All other buttons including dashboard button and buttons in the footer are functional.
After loading Example datasets or own data, the buttons appear white and are functional again.
When only ROA data is loaded and no other data, buttons are still greyed out/unfuctional when returning to the network view.

Great. Done.

Tested in Firefox (128.3.1esr (64-Bit)) and Chrome (Version 130.0.6723.59 (Offizieller Build) (64-Bit)) on Windows system.
