### ISSUE TITLE
UTX: Create menu entry and dialogue for UTX upload

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#887]
As a user I would like to be able to load a UTX file (JSON) into FCL Web. This ticket just deals with creating the menu entry and dialogue. (The actual data import process, plausibility checks and tests will be handled in separate tickets.)

The following functionalities should be implemented.

When clicking "Upload data", one of the following two actions should be triggered.
1) A drop-down menu is opened with the entries "FCL file (.json)", "FCL All-in-one template (.xlsx)", "UTX file (.json)". This action is triggered when no model was loaded before or when loaded model was not changed.
When clicking "UTX file (.json)", the file selection dialogue is opened.

2) The "Save changes" warning dialogue is opened. This action is triggered when a previously loaded model was changed.
When selecting "Proceed", the file selection dialogue is opened.

In the file selection dialogue, the user can select a JSON file. Only .json files are shown

For now, the UTX menu entry button is disabled and a tool tip is showing "Coming soon"

**Think of Tests**

-   [ ] Excel testsheet needed
-   [ ] E2e test needed
-   [ ] Integration test needed
-   [ ] Unit test needed

**Additional context**

-   [ ] Mockup needed

**Comment by arne-z** [comment]
Blocked by: #761

**Comment by ruegenbfr** [comment]
Please note: This feature was deactivated in the release candidate 1.5.0. As long as the release candidate is under test on dev this feature cannot be verified.

**Comment by bfrgottscma** [comment]
Works as intended. Good work. Done.
