### ISSUE TITLE
Bug: AiO: Import of deliveries fails

### ISSUE THREAD

**Issue by j-hha** [SiLeBAT/fcl-client#926]
**Describe the bug**
When uploading an all-in-one-template file, the deliveries are no longer imported.

**To Reproduce**

1. Go to tracing view
2. Click on upload data => all in one template
3. Import a correct template including both stations and deliveries.
4. The stations are imported but the deliveries are missing, despite no warning message.

**Expected behavior**
As a user, I want all correct data to be imported when uploading an all-in-one-template file.

**Comment by afalenski** [comment]
The deliveries are visible again in FCL Web Dev.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- AiO-Template_Minimalbeispiel_20240517.xlsx

Browsers:
- Firefox 128.4.0esr (64-Bit)
- Google Chrome Version 131.0.6778.70 (Offizieller Build) (64-Bit)
