### ISSUE TITLE
Allow switching forward and backward between graph view and roa view

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#98]
The user wants to be able to switch between graph view and roa view.

Currently the user generates a roa report from the graph view. However, if the user switches back to the graph view the graph state is gone and the Example data is shown. 

If switching back from ROA view to graph view:
- the loaded JSON data should be shown, not the Example data. --> due 6th May
- changes made in the graph view should be conserved --> nice to have 6th May

**Comment by birgitlewicki** [comment]
Both functionalities are working now.
Needs a further refactoring.

Suggestions (mail Domenic):

hier erstmal ein erster Schritt:
graph
gis
main-tracing
tracngService
must all get their data from the store - none of it should be passed into the init functions.Avoid passing around mutable state.

Later (but not before the 6th) we can think about removing the init functions completely - they are a code smell & whatever is done in them should probably happen in LifeCycle hooks (for components).  The tracingService itself should be stateless.
